export const CODE_TABS = [
  {
    label: "TypeScript",
    code: [
      { text: "import", kind: "keyword" },
      { text: " { Strait } ", kind: "default" },
      { text: "from", kind: "keyword" },
      { text: ' "@strait/sdk"', kind: "string" },
      { text: ";", kind: "default" },
      { text: "\n\n", kind: "default" },
      { text: "const", kind: "keyword" },
      { text: " strait = ", kind: "default" },
      { text: "new", kind: "keyword" },
      {
        text: " Strait({ apiKey: process.env.STRAIT_API_KEY });",
        kind: "default",
      },
      { text: "\n\n", kind: "default" },
      { text: "await", kind: "keyword" },
      { text: " strait.jobs.trigger(", kind: "default" },
      { text: '"process-order"', kind: "string" },
      { text: ", {\n", kind: "default" },
      { text: "  payload: { orderId: ", kind: "default" },
      { text: '"ord_a3f9"', kind: "string" },
      { text: ", amount: 49.99 },\n", kind: "default" },
      { text: "});", kind: "default" },
    ],
  },
  {
    label: "Python",
    code: [
      { text: "from", kind: "keyword" },
      { text: " strait ", kind: "default" },
      { text: "import", kind: "keyword" },
      { text: " Strait", kind: "default" },
      { text: "\n\n", kind: "default" },
      { text: "strait = Strait(api_key=os.environ[", kind: "default" },
      { text: '"STRAIT_API_KEY"', kind: "string" },
      { text: "])", kind: "default" },
      { text: "\n\n", kind: "default" },
      { text: "strait.jobs.trigger(", kind: "default" },
      { text: '"process-order"', kind: "string" },
      { text: ",\n", kind: "default" },
      { text: "    payload={", kind: "default" },
      { text: '"orderId"', kind: "string" },
      { text: ": ", kind: "default" },
      { text: '"ord_a3f9"', kind: "string" },
      { text: ", ", kind: "default" },
      { text: '"amount"', kind: "string" },
      { text: ": 49.99},\n)", kind: "default" },
    ],
  },
  {
    label: "Go",
    code: [
      { text: "client := strait.New(os.Getenv(", kind: "default" },
      { text: '"STRAIT_API_KEY"', kind: "string" },
      { text: "))", kind: "default" },
      { text: "\n\n", kind: "default" },
      { text: "client.Jobs.Trigger(ctx, ", kind: "default" },
      { text: '"process-order"', kind: "string" },
      { text: ", strait.Payload{\n", kind: "default" },
      { text: "    ", kind: "default" },
      { text: '"orderId"', kind: "string" },
      { text: ": ", kind: "default" },
      { text: '"ord_a3f9"', kind: "string" },
      { text: ", ", kind: "default" },
      { text: '"amount"', kind: "string" },
      { text: ": 49.99,\n})", kind: "default" },
    ],
  },
] as const;

export type CodeToken = { text: string; kind: string };
