package compute

import (
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"maps"
	"regexp"
	"time"

	"github.com/google/uuid"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

// validMachineIDRe matches the format generated by Create: strait-<12 hex chars>.
var validMachineIDRe = regexp.MustCompile(`^strait-[a-f0-9]{12}$`)

// reservedLabels are internal labels that user-supplied labels must not override.
var reservedLabels = map[string]bool{
	"app":      true,
	"job-name": true,
}

// maxCreateRetries is the number of times Create retries on name collision.
const maxCreateRetries = 3

// defaultMaxDeadlineSecs is the hard upper bound for job execution when no timeout is specified.
// Prevents jobs from running indefinitely if the caller doesn't set a timeout.
const defaultMaxDeadlineSecs = 3600

// jobTTLAfterFinished is how long completed/failed jobs persist before K8s garbage-collects them.
// Acts as a safety net for jobs where Destroy is not called (crashes, bugs).
const jobTTLAfterFinished = 600 // 10 minutes

// K8sMetrics is an optional interface for recording K8s runtime metrics.
// Keeps the compute package decoupled from the telemetry package.
type K8sMetrics interface {
	RecordJobCreate(status string, preset string, durationSecs float64)
	RecordJobWait(exitStatus string, durationSecs float64)
	RecordPodScheduling(durationSecs float64)
	IncJobsActive(delta int64)
}

// K8sRuntime implements ContainerRuntime using Kubernetes Jobs via client-go.
type K8sRuntime struct {
	clientset     kubernetes.Interface
	namespace     string
	priorityClass string
	metrics       K8sMetrics // Optional, nil-safe.
}

// NewK8sRuntime creates a new Kubernetes runtime.
// If kubeconfig is empty, falls back to in-cluster config.
func NewK8sRuntime(kubeconfig, namespace, priorityClass string) (*K8sRuntime, error) {
	var cfg *rest.Config
	var err error

	if kubeconfig != "" {
		cfg, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
	} else {
		cfg, err = rest.InClusterConfig()
	}
	if err != nil {
		return nil, fmt.Errorf("k8s config: %w", err)
	}

	clientset, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return nil, fmt.Errorf("k8s clientset: %w", err)
	}

	return &K8sRuntime{
		clientset:     clientset,
		namespace:     namespace,
		priorityClass: priorityClass,
	}, nil
}

// SetMetrics attaches optional metrics recording to the runtime.
func (k *K8sRuntime) SetMetrics(m K8sMetrics) { k.metrics = m }

// NewK8sRuntimeFromClient creates a K8sRuntime from an existing clientset (for testing).
func NewK8sRuntimeFromClient(clientset kubernetes.Interface, namespace, priorityClass string) *K8sRuntime {
	return &K8sRuntime{
		clientset:     clientset,
		namespace:     namespace,
		priorityClass: priorityClass,
	}
}

// Run creates a Kubernetes Job, waits for it to finish, and returns the result.
func (k *K8sRuntime) Run(ctx context.Context, req RunRequest) (*RunResult, error) {
	machineID, err := k.Create(ctx, req)
	if err != nil {
		return nil, err
	}
	return k.Wait(ctx, machineID, req.TimeoutSecs)
}

// Create provisions a Kubernetes Job and returns the job name as machineID.
// Retries up to maxCreateRetries times on name collision.
func (k *K8sRuntime) Create(ctx context.Context, req RunRequest) (string, error) {
	createStart := time.Now()

	if err := validateImageURI(req.ImageURI); err != nil {
		return "", NewFatalError(422, "invalid image URI", err)
	}

	preset, err := PresetFromName(req.MachinePreset)
	if err != nil {
		return "", NewFatalError(422, "invalid machine preset", err)
	}

	requests, limits := preset.K8sResources()
	userLabels := sanitizeUserLabels(req.Labels)

	for attempt := range maxCreateRetries {
		id := uuid.New()
		jobName := "strait-" + hex.EncodeToString(id[:6])

		var backoffLimit int32
		job := &batchv1.Job{
			ObjectMeta: metav1.ObjectMeta{
				Name:      jobName,
				Namespace: k.namespace,
				Labels:    mergeLabels(userLabels, map[string]string{"app": "strait-job"}),
			},
			Spec: batchv1.JobSpec{
				BackoffLimit:            &backoffLimit,
				TTLSecondsAfterFinished: newInt32(jobTTLAfterFinished),
				Template: corev1.PodTemplateSpec{
					ObjectMeta: metav1.ObjectMeta{
						Labels: mergeLabels(userLabels, map[string]string{"app": "strait-job", "job-name": jobName}),
					},
					Spec: corev1.PodSpec{
						RestartPolicy:                corev1.RestartPolicyNever,
						ServiceAccountName:           "strait-job-runner",
						AutomountServiceAccountToken: new(bool),
						SecurityContext: &corev1.PodSecurityContext{
							RunAsNonRoot: newTrue(),
							RunAsUser:    newInt64(65534), // nobody
							SeccompProfile: &corev1.SeccompProfile{
								Type: corev1.SeccompProfileTypeRuntimeDefault,
							},
						},
						Containers: []corev1.Container{
							{
								Name:  "job",
								Image: req.ImageURI,
								Env:   mapToEnvVars(req.Env),
								Resources: corev1.ResourceRequirements{
									Requests: requests,
									Limits:   limits,
								},
								SecurityContext: &corev1.SecurityContext{
									AllowPrivilegeEscalation: new(bool),
									ReadOnlyRootFilesystem:   newTrue(),
									Capabilities: &corev1.Capabilities{
										Drop: []corev1.Capability{"ALL"},
									},
								},
							},
						},
					},
				},
			},
		}

		if k.priorityClass != "" {
			job.Spec.Template.Spec.PriorityClassName = k.priorityClass
		}

		deadline := int64(defaultMaxDeadlineSecs)
		if req.TimeoutSecs > 0 {
			deadline = int64(req.TimeoutSecs)
		}
		job.Spec.ActiveDeadlineSeconds = &deadline

		_, err = k.clientset.BatchV1().Jobs(k.namespace).Create(ctx, job, metav1.CreateOptions{})
		if err == nil {
			if k.metrics != nil {
				k.metrics.RecordJobCreate("success", req.MachinePreset, time.Since(createStart).Seconds())
				k.metrics.IncJobsActive(1)
			}
			return jobName, nil
		}

		if k8serrors.IsAlreadyExists(err) {
			if attempt < maxCreateRetries-1 {
				continue // Retry with a new name.
			}
			k.recordCreateError(req.MachinePreset, createStart)
			return "", NewRetryableError(409, "job name collision after retries", err)
		}
		if k8serrors.IsInvalid(err) {
			k.recordCreateError(req.MachinePreset, createStart)
			return "", NewFatalError(422, fmt.Sprintf("invalid job spec: %v", err), nil)
		}
		k.recordCreateError(req.MachinePreset, createStart)
		return "", NewRetryableError(500, "create k8s job", err)
	}

	k.recordCreateError(req.MachinePreset, createStart)
	return "", NewRetryableError(500, "create k8s job: exhausted retries", nil)
}

// Wait blocks until a Kubernetes Job's pod completes and returns the result.
func (k *K8sRuntime) Wait(ctx context.Context, machineID string, timeoutSecs int) (*RunResult, error) {
	if err := validateMachineID(machineID); err != nil {
		return nil, err
	}

	waitStart := time.Now()
	var podRunningAt time.Time

	now := time.Now()
	result := &RunResult{
		MachineID: machineID,
		StartedAt: &now,
	}

	waitTimeout := 300
	if timeoutSecs > 0 {
		waitTimeout = timeoutSecs + 30
	}

	waitCtx, cancel := context.WithTimeout(ctx, time.Duration(waitTimeout)*time.Second)
	defer cancel()

	// Poll with exponential backoff. Starts at 1s, caps at 10s.
	pollInterval := time.Second
	const maxPollInterval = 10 * time.Second
	ticker := time.NewTicker(pollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-waitCtx.Done():
			if k.metrics != nil {
				k.metrics.RecordJobWait("timeout", time.Since(waitStart).Seconds())
				k.metrics.IncJobsActive(-1)
			}
			return result, NewTimeoutError("wait timed out", waitCtx.Err())
		case <-ticker.C:
			pod, err := k.findJobPod(waitCtx, machineID)
			if err != nil {
				// Pod may not exist yet. Back off.
				pollInterval = min(pollInterval*2, maxPollInterval)
				ticker.Reset(pollInterval)
				continue
			}

			switch pod.Status.Phase {
			case corev1.PodSucceeded, corev1.PodFailed:
				finished := time.Now()
				result.FinishedAt = &finished
				k.extractExitInfo(pod, result)

				if result.ExitCode != 0 {
					logCtx, logCancel := context.WithTimeout(ctx, 10*time.Second)
					logs, logErr := k.GetLogs(logCtx, machineID, 100)
					logCancel()
					if logErr == nil {
						result.Logs = logs
					}
				}

				if k.metrics != nil {
					exitStatus := "success"
					if result.OOMKilled {
						exitStatus = "oom"
					} else if result.ExitCode != 0 {
						exitStatus = "failure"
					}
					k.metrics.RecordJobWait(exitStatus, time.Since(waitStart).Seconds())
					k.metrics.IncJobsActive(-1)
				}

				return result, nil
			case corev1.PodRunning, corev1.PodUnknown:
				// Record pod scheduling duration once (first time we see Running).
				if podRunningAt.IsZero() {
					podRunningAt = time.Now()
					if k.metrics != nil {
						k.metrics.RecordPodScheduling(podRunningAt.Sub(waitStart).Seconds())
					}
				}
				// Reset to faster polling once pod is running.
				pollInterval = time.Second
				ticker.Reset(pollInterval)
			case corev1.PodPending:
				// Check for unrecoverable scheduling issues.
				if reason := k.podFailureReason(pod); reason != "" {
					finished := time.Now()
					result.FinishedAt = &finished
					result.ExitCode = -1
					return result, NewFatalError(422, reason, nil)
				}
				// Back off while pending.
				pollInterval = min(pollInterval*2, maxPollInterval)
				ticker.Reset(pollInterval)
			}
		}
	}
}

// Stop sends a stop signal by deleting the Job with a grace period.
func (k *K8sRuntime) Stop(ctx context.Context, machineID string) error {
	if err := validateMachineID(machineID); err != nil {
		return err
	}
	gracePeriod := int64(30)
	propagation := metav1.DeletePropagationForeground
	err := k.clientset.BatchV1().Jobs(k.namespace).Delete(ctx, machineID, metav1.DeleteOptions{
		GracePeriodSeconds: &gracePeriod,
		PropagationPolicy:  &propagation,
	})
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return ErrMachineGone
		}
		return NewRetryableError(500, "stop k8s job", err)
	}
	return nil
}

// Start always returns ErrMachineGone because Kubernetes Jobs are one-shot.
func (k *K8sRuntime) Start(_ context.Context, _ string, _ map[string]string) error {
	return ErrMachineGone
}

// Destroy deletes a Kubernetes Job and its pods immediately.
func (k *K8sRuntime) Destroy(ctx context.Context, machineID string) error {
	if err := validateMachineID(machineID); err != nil {
		return err
	}
	gracePeriod := int64(0)
	propagation := metav1.DeletePropagationBackground
	err := k.clientset.BatchV1().Jobs(k.namespace).Delete(ctx, machineID, metav1.DeleteOptions{
		GracePeriodSeconds: &gracePeriod,
		PropagationPolicy:  &propagation,
	})
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return ErrMachineGone
		}
		return NewRetryableError(500, "destroy k8s job", err)
	}
	return nil
}

// Status returns the current state of a Kubernetes Job.
func (k *K8sRuntime) Status(ctx context.Context, machineID string) (MachineStatus, error) {
	if err := validateMachineID(machineID); err != nil {
		return MachineStatusUnknown, err
	}
	pod, err := k.findJobPod(ctx, machineID)
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return MachineStatusDestroyed, nil
		}
		// No pod found for this job.
		return MachineStatusUnknown, nil
	}

	switch pod.Status.Phase {
	case corev1.PodPending:
		return MachineStatusCreated, nil
	case corev1.PodRunning:
		return MachineStatusRunning, nil
	case corev1.PodSucceeded, corev1.PodFailed:
		return MachineStatusStopped, nil
	default:
		return MachineStatusUnknown, nil
	}
}

// GetLogs returns the last N lines of a Job pod's stdout/stderr.
func (k *K8sRuntime) GetLogs(ctx context.Context, machineID string, lines int) (string, error) {
	if err := validateMachineID(machineID); err != nil {
		return "", err
	}
	pod, err := k.findJobPod(ctx, machineID)
	if err != nil {
		return "", fmt.Errorf("find pod for logs: %w", err)
	}

	tailLines := int64(lines)
	logReq := k.clientset.CoreV1().Pods(k.namespace).GetLogs(pod.Name, &corev1.PodLogOptions{
		TailLines: &tailLines,
	})

	stream, err := logReq.Stream(ctx)
	if err != nil {
		return "", fmt.Errorf("open log stream: %w", err)
	}
	defer stream.Close()

	body, err := io.ReadAll(io.LimitReader(stream, 1<<20)) // Cap at 1MB.
	if err != nil {
		return "", fmt.Errorf("read logs: %w", err)
	}

	return string(body), nil
}

func (k *K8sRuntime) recordCreateError(preset string, start time.Time) {
	if k.metrics != nil {
		k.metrics.RecordJobCreate("error", preset, time.Since(start).Seconds())
	}
}

// validateMachineID rejects machineIDs that don't match the expected format.
// Prevents label selector injection via malformed IDs.
func validateMachineID(id string) error {
	if !validMachineIDRe.MatchString(id) {
		return NewFatalError(422, fmt.Sprintf("invalid machineID format: %q", id), nil)
	}
	return nil
}

// findJobPod returns the first pod belonging to the given job.
// The caller must validate jobName before calling this function.
func (k *K8sRuntime) findJobPod(ctx context.Context, jobName string) (*corev1.Pod, error) {
	selector := labels.Set{"job-name": jobName}.String()
	pods, err := k.clientset.CoreV1().Pods(k.namespace).List(ctx, metav1.ListOptions{
		LabelSelector: selector,
		Limit:         1,
	})
	if err != nil {
		return nil, err
	}
	if len(pods.Items) == 0 {
		return nil, fmt.Errorf("no pods found for job %s", jobName)
	}
	return &pods.Items[0], nil
}

// extractExitInfo populates RunResult from pod container statuses.
func (k *K8sRuntime) extractExitInfo(pod *corev1.Pod, result *RunResult) {
	for _, cs := range pod.Status.ContainerStatuses {
		if cs.Name != "job" {
			continue
		}
		if cs.State.Terminated != nil {
			result.ExitCode = int(cs.State.Terminated.ExitCode)
			if cs.State.Terminated.Signal > 0 {
				result.ExitSignal = fmt.Sprintf("signal-%d", cs.State.Terminated.Signal)
			}
			if cs.State.Terminated.Reason == "OOMKilled" {
				result.OOMKilled = true
			}
		}
	}
}

// podFailureReason returns a reason string if the pod is in an unrecoverable state.
func (k *K8sRuntime) podFailureReason(pod *corev1.Pod) string {
	for _, cond := range pod.Status.Conditions {
		if cond.Type == corev1.PodScheduled && cond.Status == corev1.ConditionFalse {
			if cond.Reason == "Unschedulable" {
				return fmt.Sprintf("pod unschedulable: %s", cond.Message)
			}
		}
	}
	for _, cs := range pod.Status.ContainerStatuses {
		if cs.State.Waiting != nil {
			switch cs.State.Waiting.Reason {
			case "ImagePullBackOff", "ErrImagePull", "InvalidImageName":
				return fmt.Sprintf("image error: %s: %s", cs.State.Waiting.Reason, cs.State.Waiting.Message)
			}
		}
	}
	return ""
}

// sanitizeUserLabels removes reserved keys from user-supplied labels.
func sanitizeUserLabels(userLabels map[string]string) map[string]string {
	if len(userLabels) == 0 {
		return nil
	}
	clean := make(map[string]string, len(userLabels))
	for k, v := range userLabels {
		if !reservedLabels[k] {
			clean[k] = v
		}
	}
	return clean
}

// mapToEnvVars converts a map to Kubernetes EnvVar slice.
func mapToEnvVars(env map[string]string) []corev1.EnvVar {
	if len(env) == 0 {
		return nil
	}
	vars := make([]corev1.EnvVar, 0, len(env))
	for k, v := range env {
		vars = append(vars, corev1.EnvVar{Name: k, Value: v})
	}
	return vars
}

// mergeLabels merges base labels with overrides.
func mergeLabels(base, overrides map[string]string) map[string]string {
	merged := make(map[string]string, len(base)+len(overrides))
	maps.Copy(merged, base)
	maps.Copy(merged, overrides)
	return merged
}

// newTrue returns a pointer to true. Cannot use new(bool) for true values.
func newTrue() *bool { v := true; return &v }

// newInt32 returns a pointer to an int32 value.
//
//nolint:modernize // Cannot use new(int32) for non-zero values.
func newInt32(v int32) *int32 { return &v }

// newInt64 returns a pointer to an int64 value.
//
//nolint:modernize // Cannot use new(int64) for non-zero values.
func newInt64(v int64) *int64 { return &v }

// Ensure K8sRuntime implements ContainerRuntime.
var _ ContainerRuntime = (*K8sRuntime)(nil)
