package compute

import (
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"maps"
	"regexp"
	"strings"
	"time"

	"github.com/google/uuid"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

// validMachineIDRe matches the format generated by Create: strait-<12 hex chars>.
var validMachineIDRe = regexp.MustCompile(`^strait-[a-f0-9]{12}$`)

// reservedLabels are internal labels that user-supplied labels must not override.
var reservedLabels = map[string]bool{
	"app":      true,
	"job-name": true,
}

// maxCreateRetries is the number of times Create retries on name collision.
const maxCreateRetries = 3

// defaultMaxDeadlineSecs is the hard upper bound for job execution when no timeout is specified.
// Prevents jobs from running indefinitely if the caller doesn't set a timeout.
const defaultMaxDeadlineSecs = 3600

// jobTTLAfterFinished is how long completed/failed jobs persist before K8s garbage-collects them.
// Acts as a safety net for jobs where Destroy is not called (crashes, bugs).
const jobTTLAfterFinished = 600 // 10 minutes

// K8sMetrics is an optional interface for recording K8s runtime metrics.
// Keeps the compute package decoupled from the telemetry package.
type K8sMetrics interface {
	RecordJobCreate(status string, preset string, durationSecs float64)
	RecordJobWait(exitStatus string, durationSecs float64)
	RecordPodScheduling(durationSecs float64)
	IncJobsActive(delta int64)
}

// K8sRuntime implements ContainerRuntime using Kubernetes Jobs via client-go.
type K8sRuntime struct {
	clientset       kubernetes.Interface
	namespace       string
	priorityClass   string
	imagePullPolicy corev1.PullPolicy
	metrics         K8sMetrics // Optional, nil-safe.
}

// BuildK8sClientset creates a Kubernetes clientset from a kubeconfig path.
// If kubeconfig is empty, falls back to in-cluster config.
func BuildK8sClientset(kubeconfig string) (kubernetes.Interface, error) {
	var cfg *rest.Config
	var err error

	if kubeconfig != "" {
		cfg, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
	} else {
		cfg, err = rest.InClusterConfig()
	}
	if err != nil {
		return nil, fmt.Errorf("k8s config: %w", err)
	}

	clientset, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return nil, fmt.Errorf("k8s clientset: %w", err)
	}
	return clientset, nil
}

// NewK8sRuntime creates a new Kubernetes runtime.
// If kubeconfig is empty, falls back to in-cluster config.
// imagePullPolicy should be a Kubernetes PullPolicy value ("Always", "IfNotPresent",
// "Never"). An empty string leaves the field unset, deferring to Kubernetes defaults.
func NewK8sRuntime(kubeconfig, namespace, priorityClass, imagePullPolicy string) (*K8sRuntime, error) {
	clientset, err := BuildK8sClientset(kubeconfig)
	if err != nil {
		return nil, err
	}

	return &K8sRuntime{
		clientset:       clientset,
		namespace:       namespace,
		priorityClass:   priorityClass,
		imagePullPolicy: corev1.PullPolicy(imagePullPolicy),
	}, nil
}

// Clientset returns the underlying Kubernetes clientset for shared use (e.g. GC).
func (k *K8sRuntime) Clientset() kubernetes.Interface { return k.clientset }

// SetMetrics attaches optional metrics recording to the runtime.
func (k *K8sRuntime) SetMetrics(m K8sMetrics) { k.metrics = m }

// NewK8sRuntimeFromClient creates a K8sRuntime from an existing clientset (for testing).
// imagePullPolicy should be a Kubernetes PullPolicy value ("Always", "IfNotPresent",
// "Never"). An empty string leaves the field unset, deferring to Kubernetes defaults.
func NewK8sRuntimeFromClient(clientset kubernetes.Interface, namespace, priorityClass, imagePullPolicy string) *K8sRuntime {
	return &K8sRuntime{
		clientset:       clientset,
		namespace:       namespace,
		priorityClass:   priorityClass,
		imagePullPolicy: corev1.PullPolicy(imagePullPolicy),
	}
}

// Run creates a Kubernetes Job, waits for it to finish, and returns the result.
func (k *K8sRuntime) Run(ctx context.Context, req RunRequest) (*RunResult, error) {
	machineID, err := k.Create(ctx, req)
	if err != nil {
		return nil, err
	}
	return k.Wait(ctx, machineID, req.TimeoutSecs)
}

// Create provisions a Kubernetes Job and returns the job name as machineID.
// Retries up to maxCreateRetries times on name collision.
func (k *K8sRuntime) Create(ctx context.Context, req RunRequest) (string, error) {
	createStart := time.Now()

	if err := validateImageURI(req.ImageURI); err != nil {
		return "", NewFatalError(422, "invalid image URI", err)
	}

	preset, err := PresetFromName(req.MachinePreset)
	if err != nil {
		return "", NewFatalError(422, "invalid machine preset", err)
	}

	ns := k.resolveNamespace(req.Namespace)
	requests, limits := preset.K8sResources()
	userLabels := sanitizeUserLabels(req.Labels)

	for attempt := range maxCreateRetries {
		id := uuid.New()
		jobName := "strait-" + hex.EncodeToString(id[:6])

		var backoffLimit int32
		job := &batchv1.Job{
			ObjectMeta: metav1.ObjectMeta{
				Name:      jobName,
				Namespace: ns,
				Labels:    mergeLabels(userLabels, map[string]string{"app": "strait-job"}),
			},
			Spec: batchv1.JobSpec{
				BackoffLimit:            &backoffLimit,
				TTLSecondsAfterFinished: newInt32(jobTTLAfterFinished),
				Template: corev1.PodTemplateSpec{
					ObjectMeta: metav1.ObjectMeta{
						Labels: mergeLabels(userLabels, map[string]string{"app": "strait-job", "job-name": jobName}),
					},
					Spec: corev1.PodSpec{
						RestartPolicy:                corev1.RestartPolicyNever,
						ServiceAccountName:           "strait-job-runner",
						AutomountServiceAccountToken: new(bool),
						SecurityContext: &corev1.PodSecurityContext{
							RunAsNonRoot: newTrue(),
							RunAsUser:    newInt64(65534), // nobody
							SeccompProfile: &corev1.SeccompProfile{
								Type: corev1.SeccompProfileTypeRuntimeDefault,
							},
						},
						Containers: []corev1.Container{
							{
								Name:            "job",
								Image:           req.ImageURI,
								ImagePullPolicy: k.imagePullPolicy,
								Env:             mapToEnvVars(req.Env),
								Resources: corev1.ResourceRequirements{
									Requests: requests,
									Limits:   limits,
								},
								SecurityContext: &corev1.SecurityContext{
									AllowPrivilegeEscalation: new(bool),
									ReadOnlyRootFilesystem:   newTrue(),
									Capabilities: &corev1.Capabilities{
										Drop: []corev1.Capability{"ALL"},
									},
								},
							},
						},
					},
				},
			},
		}

		if k.priorityClass != "" {
			job.Spec.Template.Spec.PriorityClassName = k.priorityClass
		}

		if affinity := preset.K8sNodeAffinity(); affinity != nil {
			job.Spec.Template.Spec.Affinity = affinity
		}

		deadline := int64(defaultMaxDeadlineSecs)
		if req.TimeoutSecs > 0 {
			deadline = int64(req.TimeoutSecs)
		}
		job.Spec.ActiveDeadlineSeconds = &deadline

		_, err = k.clientset.BatchV1().Jobs(ns).Create(ctx, job, metav1.CreateOptions{})
		if err == nil {
			if k.metrics != nil {
				k.metrics.RecordJobCreate("success", req.MachinePreset, time.Since(createStart).Seconds())
				k.metrics.IncJobsActive(1)
			}
			return jobName, nil
		}

		if k8serrors.IsAlreadyExists(err) {
			if attempt < maxCreateRetries-1 {
				continue // Retry with a new name.
			}
			k.recordCreateError(req.MachinePreset, createStart)
			return "", NewRetryableError(409, "job name collision after retries", err)
		}
		if k8serrors.IsInvalid(err) {
			k.recordCreateError(req.MachinePreset, createStart)
			return "", NewFatalError(422, fmt.Sprintf("invalid job spec: %v", err), nil)
		}
		k.recordCreateError(req.MachinePreset, createStart)
		return "", NewRetryableError(500, "create k8s job", err)
	}

	k.recordCreateError(req.MachinePreset, createStart)
	return "", NewRetryableError(500, "create k8s job: exhausted retries", nil)
}

// waitState holds shared state for wait operations.
type waitState struct {
	result       *RunResult
	waitStart    time.Time
	podRunningAt time.Time
}

// Wait blocks until a Kubernetes Job's pod completes and returns the result.
// Tries K8s watch API first for efficiency; falls back to polling on watch errors.
func (k *K8sRuntime) Wait(ctx context.Context, machineID string, timeoutSecs int) (*RunResult, error) {
	if err := validateMachineID(machineID); err != nil {
		return nil, err
	}

	now := time.Now()
	ws := &waitState{
		result: &RunResult{
			MachineID: machineID,
			StartedAt: &now,
		},
		waitStart: now,
	}

	waitTimeout := 300
	if timeoutSecs > 0 {
		waitTimeout = timeoutSecs + 30
	}

	waitCtx, cancel := context.WithTimeout(ctx, time.Duration(waitTimeout)*time.Second)
	defer cancel()

	// Try watch-based waiting first (efficient, event-driven).
	selector := labels.Set{"job-name": machineID}.String()
	watcher, err := k.clientset.CoreV1().Pods(k.namespace).Watch(waitCtx, metav1.ListOptions{
		LabelSelector: selector,
	})
	if err == nil {
		result, watchErr := k.waitWatch(ctx, waitCtx, machineID, watcher, ws)
		if watchErr == nil {
			return result, nil
		}
		// Watch closed or errored -- fall through to polling.
	}

	// Fallback: polling with exponential backoff.
	return k.waitPoll(ctx, waitCtx, machineID, ws)
}

// waitWatch uses the K8s watch API to wait for pod completion.
func (k *K8sRuntime) waitWatch(ctx, waitCtx context.Context, machineID string, watcher watch.Interface, ws *waitState) (*RunResult, error) {
	defer watcher.Stop()

	for {
		select {
		case <-waitCtx.Done():
			k.recordWaitTimeout(ws)
			return ws.result, NewTimeoutError("wait timed out", waitCtx.Err())

		case event, ok := <-watcher.ResultChan():
			if !ok {
				// Watch channel closed -- fall back to polling.
				return nil, fmt.Errorf("watch closed")
			}

			pod, isPod := event.Object.(*corev1.Pod)
			if !isPod {
				continue
			}

			action := k.handlePodPhase(ctx, machineID, pod, ws)
			switch action {
			case podActionComplete:
				return ws.result, nil
			case podActionFatal:
				return ws.result, NewFatalError(422, k.podFailureReason(pod), nil)
			case podActionContinue:
				continue
			}
		}
	}
}

// waitPoll uses polling with exponential backoff to wait for pod completion.
func (k *K8sRuntime) waitPoll(ctx, waitCtx context.Context, machineID string, ws *waitState) (*RunResult, error) {
	pollInterval := time.Second
	const maxPollInterval = 10 * time.Second
	ticker := time.NewTicker(pollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-waitCtx.Done():
			k.recordWaitTimeout(ws)
			return ws.result, NewTimeoutError("wait timed out", waitCtx.Err())
		case <-ticker.C:
			pod, err := k.findJobPod(waitCtx, machineID)
			if err != nil {
				pollInterval = min(pollInterval*2, maxPollInterval)
				ticker.Reset(pollInterval)
				continue
			}

			action := k.handlePodPhase(ctx, machineID, pod, ws)
			switch action {
			case podActionComplete:
				return ws.result, nil
			case podActionFatal:
				return ws.result, NewFatalError(422, k.podFailureReason(pod), nil)
			case podActionContinue:
				// Reset to faster polling once pod is running.
				if pod.Status.Phase == corev1.PodRunning {
					pollInterval = time.Second
				} else {
					pollInterval = min(pollInterval*2, maxPollInterval)
				}
				ticker.Reset(pollInterval)
			}
		}
	}
}

type podAction int

const (
	podActionContinue podAction = iota
	podActionComplete
	podActionFatal
)

// handlePodPhase processes a pod status update and returns what the caller should do.
func (k *K8sRuntime) handlePodPhase(ctx context.Context, machineID string, pod *corev1.Pod, ws *waitState) podAction {
	switch pod.Status.Phase {
	case corev1.PodSucceeded, corev1.PodFailed:
		finished := time.Now()
		ws.result.FinishedAt = &finished
		k.extractExitInfo(pod, ws.result)

		if ws.result.ExitCode != 0 {
			logCtx, logCancel := context.WithTimeout(ctx, 10*time.Second)
			logs, logErr := k.GetLogs(logCtx, machineID, 100)
			logCancel()
			if logErr == nil {
				ws.result.Logs = logs
			}
		}

		if k.metrics != nil {
			exitStatus := "success"
			if ws.result.OOMKilled {
				exitStatus = "oom"
			} else if ws.result.ExitCode != 0 {
				exitStatus = "failure"
			}
			k.metrics.RecordJobWait(exitStatus, time.Since(ws.waitStart).Seconds())
			k.metrics.IncJobsActive(-1)
		}
		return podActionComplete

	case corev1.PodRunning, corev1.PodUnknown:
		if ws.podRunningAt.IsZero() {
			ws.podRunningAt = time.Now()
			if k.metrics != nil {
				k.metrics.RecordPodScheduling(ws.podRunningAt.Sub(ws.waitStart).Seconds())
			}
		}
		return podActionContinue

	case corev1.PodPending:
		if reason := k.podFailureReason(pod); reason != "" {
			finished := time.Now()
			ws.result.FinishedAt = &finished
			ws.result.ExitCode = -1
			return podActionFatal
		}
		return podActionContinue
	}

	return podActionContinue
}

// recordWaitTimeout records timeout metrics.
func (k *K8sRuntime) recordWaitTimeout(ws *waitState) {
	if k.metrics != nil {
		k.metrics.RecordJobWait("timeout", time.Since(ws.waitStart).Seconds())
		k.metrics.IncJobsActive(-1)
	}
}

// Stop sends a stop signal by deleting the Job with a grace period.
func (k *K8sRuntime) Stop(ctx context.Context, machineID string) error {
	if err := validateMachineID(machineID); err != nil {
		return err
	}
	gracePeriod := int64(30)
	propagation := metav1.DeletePropagationForeground
	err := k.clientset.BatchV1().Jobs(k.namespace).Delete(ctx, machineID, metav1.DeleteOptions{
		GracePeriodSeconds: &gracePeriod,
		PropagationPolicy:  &propagation,
	})
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return ErrMachineGone
		}
		return NewRetryableError(500, "stop k8s job", err)
	}
	return nil
}

// Start always returns ErrMachineGone because Kubernetes Jobs are one-shot.
func (k *K8sRuntime) Start(_ context.Context, _ string, _ map[string]string) error {
	return ErrMachineGone
}

// Destroy deletes a Kubernetes Job and its pods immediately.
func (k *K8sRuntime) Destroy(ctx context.Context, machineID string) error {
	if err := validateMachineID(machineID); err != nil {
		return err
	}
	gracePeriod := int64(0)
	propagation := metav1.DeletePropagationBackground
	err := k.clientset.BatchV1().Jobs(k.namespace).Delete(ctx, machineID, metav1.DeleteOptions{
		GracePeriodSeconds: &gracePeriod,
		PropagationPolicy:  &propagation,
	})
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return ErrMachineGone
		}
		return NewRetryableError(500, "destroy k8s job", err)
	}
	return nil
}

// Status returns the current state of a Kubernetes Job.
func (k *K8sRuntime) Status(ctx context.Context, machineID string) (MachineStatus, error) {
	if err := validateMachineID(machineID); err != nil {
		return MachineStatusUnknown, err
	}
	pod, err := k.findJobPod(ctx, machineID)
	if err != nil {
		if k8serrors.IsNotFound(err) {
			return MachineStatusDestroyed, nil
		}
		// No pod found for this job.
		return MachineStatusUnknown, nil
	}

	switch pod.Status.Phase {
	case corev1.PodPending:
		return MachineStatusCreated, nil
	case corev1.PodRunning:
		return MachineStatusRunning, nil
	case corev1.PodSucceeded, corev1.PodFailed:
		return MachineStatusStopped, nil
	default:
		return MachineStatusUnknown, nil
	}
}

// GetLogs returns the last N lines of a Job pod's stdout/stderr.
func (k *K8sRuntime) GetLogs(ctx context.Context, machineID string, lines int) (string, error) {
	if err := validateMachineID(machineID); err != nil {
		return "", err
	}
	pod, err := k.findJobPod(ctx, machineID)
	if err != nil {
		return "", fmt.Errorf("find pod for logs: %w", err)
	}

	tailLines := int64(lines)
	logReq := k.clientset.CoreV1().Pods(k.namespace).GetLogs(pod.Name, &corev1.PodLogOptions{
		TailLines: &tailLines,
	})

	stream, err := logReq.Stream(ctx)
	if err != nil {
		return "", fmt.Errorf("open log stream: %w", err)
	}
	defer stream.Close()

	body, err := io.ReadAll(io.LimitReader(stream, 1<<20)) // Cap at 1MB.
	if err != nil {
		return "", fmt.Errorf("read logs: %w", err)
	}

	return string(body), nil
}

// resolveNamespace returns the override namespace if set, otherwise the default.
func (k *K8sRuntime) resolveNamespace(override string) string {
	if override != "" {
		return override
	}
	return k.namespace
}

func (k *K8sRuntime) recordCreateError(preset string, start time.Time) {
	if k.metrics != nil {
		k.metrics.RecordJobCreate("error", preset, time.Since(start).Seconds())
	}
}

// validateMachineID rejects machineIDs that don't match the expected format.
// Prevents label selector injection via malformed IDs.
func validateMachineID(id string) error {
	if !validMachineIDRe.MatchString(id) {
		return NewFatalError(422, fmt.Sprintf("invalid machineID format: %q", id), nil)
	}
	return nil
}

// findJobPod returns the first pod belonging to the given job.
// The caller must validate jobName before calling this function.
func (k *K8sRuntime) findJobPod(ctx context.Context, jobName string) (*corev1.Pod, error) {
	selector := labels.Set{"job-name": jobName}.String()
	pods, err := k.clientset.CoreV1().Pods(k.namespace).List(ctx, metav1.ListOptions{
		LabelSelector: selector,
		Limit:         1,
	})
	if err != nil {
		return nil, err
	}
	if len(pods.Items) == 0 {
		return nil, fmt.Errorf("no pods found for job %s", jobName)
	}
	return &pods.Items[0], nil
}

// extractExitInfo populates RunResult from pod container statuses.
func (k *K8sRuntime) extractExitInfo(pod *corev1.Pod, result *RunResult) {
	for _, cs := range pod.Status.ContainerStatuses {
		if cs.Name != "job" {
			continue
		}
		if cs.State.Terminated != nil {
			result.ExitCode = int(cs.State.Terminated.ExitCode)
			if cs.State.Terminated.Signal > 0 {
				result.ExitSignal = fmt.Sprintf("signal-%d", cs.State.Terminated.Signal)
			}
			if cs.State.Terminated.Reason == "OOMKilled" {
				result.OOMKilled = true
			}
		}
	}
}

// podFailureReason returns a reason string if the pod is in an unrecoverable state.
func (k *K8sRuntime) podFailureReason(pod *corev1.Pod) string {
	for _, cond := range pod.Status.Conditions {
		if cond.Type == corev1.PodScheduled && cond.Status == corev1.ConditionFalse {
			if cond.Reason == "Unschedulable" {
				return fmt.Sprintf("pod unschedulable: %s", cond.Message)
			}
		}
	}
	for _, cs := range pod.Status.ContainerStatuses {
		if cs.State.Waiting != nil {
			switch cs.State.Waiting.Reason {
			case "ImagePullBackOff", "ErrImagePull", "InvalidImageName":
				return fmt.Sprintf("image error: %s: %s", cs.State.Waiting.Reason, cs.State.Waiting.Message)
			}
		}
	}
	return ""
}

// sanitizeUserLabels removes reserved keys and dangerous characters from user-supplied labels.
func sanitizeUserLabels(userLabels map[string]string) map[string]string {
	if len(userLabels) == 0 {
		return nil
	}
	clean := make(map[string]string, len(userLabels))
	for k, v := range userLabels {
		if reservedLabels[k] {
			continue
		}
		// Strip null bytes, newlines, and control characters from keys and values.
		k = stripControlChars(k)
		v = stripControlChars(v)
		if k == "" {
			continue
		}
		// K8s label values must be <= 63 characters.
		if len(v) > 63 {
			v = v[:63]
		}
		clean[k] = v
	}
	return clean
}

// stripControlChars removes null bytes, newlines, and other control characters.
func stripControlChars(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r >= 32 && r != 127 {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// mapToEnvVars converts a map to Kubernetes EnvVar slice.
func mapToEnvVars(env map[string]string) []corev1.EnvVar {
	if len(env) == 0 {
		return nil
	}
	vars := make([]corev1.EnvVar, 0, len(env))
	for k, v := range env {
		vars = append(vars, corev1.EnvVar{Name: k, Value: v})
	}
	return vars
}

// mergeLabels merges base labels with overrides.
func mergeLabels(base, overrides map[string]string) map[string]string {
	merged := make(map[string]string, len(base)+len(overrides))
	maps.Copy(merged, base)
	maps.Copy(merged, overrides)
	return merged
}

// newTrue returns a pointer to true. Cannot use new(bool) for true values.
func newTrue() *bool { v := true; return &v }

// newInt32 returns a pointer to an int32 value.
//
//nolint:modernize // Cannot use new(int32) for non-zero values.
func newInt32(v int32) *int32 { return &v }

// newInt64 returns a pointer to an int64 value.
//
//nolint:modernize // Cannot use new(int64) for non-zero values.
func newInt64(v int64) *int64 { return &v }

// Ensure K8sRuntime implements ContainerRuntime.
var _ ContainerRuntime = (*K8sRuntime)(nil)
