/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/app/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as InvitationIdRouteImport } from './routes/invitation/$id'
import { Route as InternalTransactionalEmailRouteImport } from './routes/internal/transactional-email'
import { Route as AppUpgradeRouteImport } from './routes/app/upgrade'
import { Route as AppEnterpriseContactRouteImport } from './routes/app/enterprise-contact'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authTwoFactorRouteImport } from './routes/(auth)/two-factor'
import { Route as authSsoRouteImport } from './routes/(auth)/sso'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authDeviceRouteImport } from './routes/(auth)/device'
import { Route as AppWorkflowsIndexRouteImport } from './routes/app/workflows/index'
import { Route as AppWebhooksIndexRouteImport } from './routes/app/webhooks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSchedulesIndexRouteImport } from './routes/app/schedules/index'
import { Route as AppRunsIndexRouteImport } from './routes/app/runs/index'
import { Route as AppLogsIndexRouteImport } from './routes/app/logs/index'
import { Route as AppJobsIndexRouteImport } from './routes/app/jobs/index'
import { Route as AppEventsIndexRouteImport } from './routes/app/events/index'
import { Route as AppDlqIndexRouteImport } from './routes/app/dlq/index'
import { Route as AppBillingIndexRouteImport } from './routes/app/billing/index'
import { Route as AppWorkflowsIdRouteImport } from './routes/app/workflows/$id'
import { Route as AppWebhooksNewRouteImport } from './routes/app/webhooks/new'
import { Route as AppWebhooksIdRouteImport } from './routes/app/webhooks/$id'
import { Route as AppSchedulesIdRouteImport } from './routes/app/schedules/$id'
import { Route as AppRunsIdRouteImport } from './routes/app/runs/$id'
import { Route as AppPricingCompareRouteImport } from './routes/app/pricing/compare'
import { Route as AppOrgIdRouteImport } from './routes/app/org/$id'
import { Route as AppJobsIdRouteImport } from './routes/app/jobs/$id'
import { Route as ApiAuthJwksRouteImport } from './routes/api/auth/jwks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authOauthConsentRouteImport } from './routes/(auth)/oauth/consent'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/app/projects/$projectId/settings'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalTransactionalEmailRoute =
  InternalTransactionalEmailRouteImport.update({
    id: '/internal/transactional-email',
    path: '/internal/transactional-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEnterpriseContactRoute = AppEnterpriseContactRouteImport.update({
  id: '/enterprise-contact',
  path: '/enterprise-contact',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppLayoutRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authTwoFactorRoute = authTwoFactorRouteImport.update({
  id: '/(auth)/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const authSsoRoute = authSsoRouteImport.update({
  id: '/(auth)/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/(auth)/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authDeviceRoute = authDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSchedulesIndexRoute = AppSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDlqIndexRoute = AppDlqIndexRouteImport.update({
  id: '/dlq/',
  path: '/dlq/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWorkflowsIdRoute = AppWorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWebhooksNewRoute = AppWebhooksNewRouteImport.update({
  id: '/webhooks/new',
  path: '/webhooks/new',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWebhooksIdRoute = AppWebhooksIdRouteImport.update({
  id: '/webhooks/$id',
  path: '/webhooks/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSchedulesIdRoute = AppSchedulesIdRouteImport.update({
  id: '/schedules/$id',
  path: '/schedules/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPricingCompareRoute = AppPricingCompareRouteImport.update({
  id: '/pricing/compare',
  path: '/pricing/compare',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgIdRoute = AppOrgIdRouteImport.update({
  id: '/org/$id',
  path: '/org/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiAuthJwksRoute = ApiAuthJwksRouteImport.update({
  id: '/api/auth/jwks',
  path: '/api/auth/jwks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authOauthConsentRoute = authOauthConsentRouteImport.update({
  id: '/(auth)/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/device': typeof authDeviceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/sso': typeof authSsoRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/enterprise-contact': typeof AppEnterpriseContactRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/internal/transactional-email': typeof InternalTransactionalEmailRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/oauth/consent': typeof authOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/jwks': typeof ApiAuthJwksRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/pricing/compare': typeof AppPricingCompareRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/dlq/': typeof AppDlqIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof authDeviceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/sso': typeof authSsoRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/enterprise-contact': typeof AppEnterpriseContactRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/internal/transactional-email': typeof InternalTransactionalEmailRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app': typeof AppIndexRoute
  '/oauth/consent': typeof authOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/jwks': typeof ApiAuthJwksRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/pricing/compare': typeof AppPricingCompareRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/billing': typeof AppBillingIndexRoute
  '/app/dlq': typeof AppDlqIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/app/logs': typeof AppLogsIndexRoute
  '/app/runs': typeof AppRunsIndexRoute
  '/app/schedules': typeof AppSchedulesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/webhooks': typeof AppWebhooksIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/(auth)/device': typeof authDeviceRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/sso': typeof authSsoRoute
  '/(auth)/two-factor': typeof authTwoFactorRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/enterprise-contact': typeof AppEnterpriseContactRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/internal/transactional-email': typeof InternalTransactionalEmailRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/(auth)/oauth/consent': typeof authOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/jwks': typeof ApiAuthJwksRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/pricing/compare': typeof AppPricingCompareRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/webhooks/$id': typeof AppWebhooksIdRoute
  '/app/webhooks/new': typeof AppWebhooksNewRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/dlq/': typeof AppDlqIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/reset-password'
    | '/signup'
    | '/sso'
    | '/two-factor'
    | '/verify-email'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/enterprise-contact'
    | '/app/upgrade'
    | '/internal/transactional-email'
    | '/invitation/$id'
    | '/app/'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/api/auth/jwks'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/pricing/compare'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/webhooks/$id'
    | '/app/webhooks/new'
    | '/app/workflows/$id'
    | '/app/billing/'
    | '/app/dlq/'
    | '/app/events/'
    | '/app/jobs/'
    | '/app/logs/'
    | '/app/runs/'
    | '/app/schedules/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/workflows/'
    | '/app/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/reset-password'
    | '/signup'
    | '/sso'
    | '/two-factor'
    | '/verify-email'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/enterprise-contact'
    | '/app/upgrade'
    | '/internal/transactional-email'
    | '/invitation/$id'
    | '/app'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/api/auth/jwks'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/pricing/compare'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/webhooks/$id'
    | '/app/webhooks/new'
    | '/app/workflows/$id'
    | '/app/billing'
    | '/app/dlq'
    | '/app/events'
    | '/app/jobs'
    | '/app/logs'
    | '/app/runs'
    | '/app/schedules'
    | '/app/settings'
    | '/app/webhooks'
    | '/app/workflows'
    | '/app/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/(auth)/device'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/sso'
    | '/(auth)/two-factor'
    | '/(auth)/verify-email'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/enterprise-contact'
    | '/app/upgrade'
    | '/internal/transactional-email'
    | '/invitation/$id'
    | '/app/'
    | '/(auth)/oauth/consent'
    | '/api/auth/$'
    | '/api/auth/jwks'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/pricing/compare'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/webhooks/$id'
    | '/app/webhooks/new'
    | '/app/workflows/$id'
    | '/app/billing/'
    | '/app/dlq/'
    | '/app/events/'
    | '/app/jobs/'
    | '/app/logs/'
    | '/app/runs/'
    | '/app/schedules/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/workflows/'
    | '/app/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  authDeviceRoute: typeof authDeviceRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authSsoRoute: typeof authSsoRoute
  authTwoFactorRoute: typeof authTwoFactorRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  InternalTransactionalEmailRoute: typeof InternalTransactionalEmailRoute
  InvitationIdRoute: typeof InvitationIdRoute
  authOauthConsentRoute: typeof authOauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthJwksRoute: typeof ApiAuthJwksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/transactional-email': {
      id: '/internal/transactional-email'
      path: '/internal/transactional-email'
      fullPath: '/internal/transactional-email'
      preLoaderRoute: typeof InternalTransactionalEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/enterprise-contact': {
      id: '/app/enterprise-contact'
      path: '/enterprise-contact'
      fullPath: '/app/enterprise-contact'
      preLoaderRoute: typeof AppEnterpriseContactRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/two-factor': {
      id: '/(auth)/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof authTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sso': {
      id: '/(auth)/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof authSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/device': {
      id: '/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof authDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/workflows'
      fullPath: '/app/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/webhooks/': {
      id: '/app/webhooks/'
      path: '/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/schedules/': {
      id: '/app/schedules/'
      path: '/schedules'
      fullPath: '/app/schedules/'
      preLoaderRoute: typeof AppSchedulesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/runs/': {
      id: '/app/runs/'
      path: '/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/logs/': {
      id: '/app/logs/'
      path: '/logs'
      fullPath: '/app/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/dlq/': {
      id: '/app/dlq/'
      path: '/dlq'
      fullPath: '/app/dlq/'
      preLoaderRoute: typeof AppDlqIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/billing/': {
      id: '/app/billing/'
      path: '/billing'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/workflows/$id': {
      id: '/app/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/app/workflows/$id'
      preLoaderRoute: typeof AppWorkflowsIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/webhooks/new': {
      id: '/app/webhooks/new'
      path: '/webhooks/new'
      fullPath: '/app/webhooks/new'
      preLoaderRoute: typeof AppWebhooksNewRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/webhooks/$id': {
      id: '/app/webhooks/$id'
      path: '/webhooks/$id'
      fullPath: '/app/webhooks/$id'
      preLoaderRoute: typeof AppWebhooksIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/schedules/$id': {
      id: '/app/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/app/schedules/$id'
      preLoaderRoute: typeof AppSchedulesIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/pricing/compare': {
      id: '/app/pricing/compare'
      path: '/pricing/compare'
      fullPath: '/app/pricing/compare'
      preLoaderRoute: typeof AppPricingCompareRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/org/$id': {
      id: '/app/org/$id'
      path: '/org/$id'
      fullPath: '/app/org/$id'
      preLoaderRoute: typeof AppOrgIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/auth/jwks': {
      id: '/api/auth/jwks'
      path: '/api/auth/jwks'
      fullPath: '/api/auth/jwks'
      preLoaderRoute: typeof ApiAuthJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/oauth/consent': {
      id: '/(auth)/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof authOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$projectId/settings': {
      id: '/app/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/app/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnterpriseContactRoute: typeof AppEnterpriseContactRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppOrgIdRoute: typeof AppOrgIdRoute
  AppPricingCompareRoute: typeof AppPricingCompareRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppSchedulesIdRoute: typeof AppSchedulesIdRoute
  AppWebhooksIdRoute: typeof AppWebhooksIdRoute
  AppWebhooksNewRoute: typeof AppWebhooksNewRoute
  AppWorkflowsIdRoute: typeof AppWorkflowsIdRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppDlqIndexRoute: typeof AppDlqIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
  AppSchedulesIndexRoute: typeof AppSchedulesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnterpriseContactRoute: AppEnterpriseContactRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppOrgIdRoute: AppOrgIdRoute,
  AppPricingCompareRoute: AppPricingCompareRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppSchedulesIdRoute: AppSchedulesIdRoute,
  AppWebhooksIdRoute: AppWebhooksIdRoute,
  AppWebhooksNewRoute: AppWebhooksNewRoute,
  AppWorkflowsIdRoute: AppWorkflowsIdRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppDlqIndexRoute: AppDlqIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
  AppSchedulesIndexRoute: AppSchedulesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  authDeviceRoute: authDeviceRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authSsoRoute: authSsoRoute,
  authTwoFactorRoute: authTwoFactorRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  InternalTransactionalEmailRoute: InternalTransactionalEmailRoute,
  InvitationIdRoute: InvitationIdRoute,
  authOauthConsentRoute: authOauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthJwksRoute: ApiAuthJwksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
