/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as InvitationIdRouteImport } from './routes/invitation/$id'
import { Route as AppUpgradeRouteImport } from './routes/app/upgrade'
import { Route as AppLayoutRouteImport } from './routes/app/layout'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authTwoFactorRouteImport } from './routes/(auth)/two-factor'
import { Route as authSsoRouteImport } from './routes/(auth)/sso'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authDeviceRouteImport } from './routes/(auth)/device'
import { Route as AppWorkflowsIndexRouteImport } from './routes/app/workflows/index'
import { Route as AppWebhooksIndexRouteImport } from './routes/app/webhooks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSchedulesIndexRouteImport } from './routes/app/schedules/index'
import { Route as AppRunsIndexRouteImport } from './routes/app/runs/index'
import { Route as AppLogsIndexRouteImport } from './routes/app/logs/index'
import { Route as AppJobsIndexRouteImport } from './routes/app/jobs/index'
import { Route as AppEventsIndexRouteImport } from './routes/app/events/index'
import { Route as AppDlqIndexRouteImport } from './routes/app/dlq/index'
import { Route as AppWorkflowsIdRouteImport } from './routes/app/workflows/$id'
import { Route as AppSchedulesIdRouteImport } from './routes/app/schedules/$id'
import { Route as AppRunsIdRouteImport } from './routes/app/runs/$id'
import { Route as AppOrgIdRouteImport } from './routes/app/org/$id'
import { Route as AppJobsIdRouteImport } from './routes/app/jobs/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/app/upgrade',
  path: '/app/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/layout',
  path: '/app/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authTwoFactorRoute = authTwoFactorRouteImport.update({
  id: '/(auth)/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const authSsoRoute = authSsoRouteImport.update({
  id: '/(auth)/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/(auth)/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authDeviceRoute = authDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/app/workflows/',
  path: '/app/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/app/webhooks/',
  path: '/app/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchedulesIndexRoute = AppSchedulesIndexRouteImport.update({
  id: '/app/schedules/',
  path: '/app/schedules/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/app/runs/',
  path: '/app/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/app/logs/',
  path: '/app/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/app/jobs/',
  path: '/app/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/app/events/',
  path: '/app/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDlqIndexRoute = AppDlqIndexRouteImport.update({
  id: '/app/dlq/',
  path: '/app/dlq/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIdRoute = AppWorkflowsIdRouteImport.update({
  id: '/app/workflows/$id',
  path: '/app/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchedulesIdRoute = AppSchedulesIdRouteImport.update({
  id: '/app/schedules/$id',
  path: '/app/schedules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/app/runs/$id',
  path: '/app/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgIdRoute = AppOrgIdRouteImport.update({
  id: '/app/org/$id',
  path: '/app/org/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/app/jobs/$id',
  path: '/app/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof authDeviceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/sso': typeof authSsoRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/layout': typeof AppLayoutRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/dlq/': typeof AppDlqIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof authDeviceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/sso': typeof authSsoRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/layout': typeof AppLayoutRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/dlq': typeof AppDlqIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/app/logs': typeof AppLogsIndexRoute
  '/app/runs': typeof AppRunsIndexRoute
  '/app/schedules': typeof AppSchedulesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/webhooks': typeof AppWebhooksIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/device': typeof authDeviceRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/sso': typeof authSsoRoute
  '/(auth)/two-factor': typeof authTwoFactorRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/layout': typeof AppLayoutRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/app/org/$id': typeof AppOrgIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/schedules/$id': typeof AppSchedulesIdRoute
  '/app/workflows/$id': typeof AppWorkflowsIdRoute
  '/app/dlq/': typeof AppDlqIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/logs/': typeof AppLogsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
  '/app/schedules/': typeof AppSchedulesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/webhooks/': typeof AppWebhooksIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/reset-password'
    | '/signup'
    | '/sso'
    | '/two-factor'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/layout'
    | '/app/upgrade'
    | '/invitation/$id'
    | '/app/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/workflows/$id'
    | '/app/dlq/'
    | '/app/events/'
    | '/app/jobs/'
    | '/app/logs/'
    | '/app/runs/'
    | '/app/schedules/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/magic-link'
    | '/reset-password'
    | '/signup'
    | '/sso'
    | '/two-factor'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/layout'
    | '/app/upgrade'
    | '/invitation/$id'
    | '/app'
    | '/onboarding'
    | '/api/auth/$'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/workflows/$id'
    | '/app/dlq'
    | '/app/events'
    | '/app/jobs'
    | '/app/logs'
    | '/app/runs'
    | '/app/schedules'
    | '/app/settings'
    | '/app/webhooks'
    | '/app/workflows'
  id:
    | '__root__'
    | '/'
    | '/(auth)/device'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/sso'
    | '/(auth)/two-factor'
    | '/(auth)/verify-email'
    | '/app/dashboard'
    | '/app/layout'
    | '/app/upgrade'
    | '/invitation/$id'
    | '/app/'
    | '/onboarding/'
    | '/api/auth/$'
    | '/app/jobs/$id'
    | '/app/org/$id'
    | '/app/runs/$id'
    | '/app/schedules/$id'
    | '/app/workflows/$id'
    | '/app/dlq/'
    | '/app/events/'
    | '/app/jobs/'
    | '/app/logs/'
    | '/app/runs/'
    | '/app/schedules/'
    | '/app/settings/'
    | '/app/webhooks/'
    | '/app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authDeviceRoute: typeof authDeviceRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authSsoRoute: typeof authSsoRoute
  authTwoFactorRoute: typeof authTwoFactorRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLayoutRoute: typeof AppLayoutRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  InvitationIdRoute: typeof InvitationIdRoute
  AppIndexRoute: typeof AppIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppOrgIdRoute: typeof AppOrgIdRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppSchedulesIdRoute: typeof AppSchedulesIdRoute
  AppWorkflowsIdRoute: typeof AppWorkflowsIdRoute
  AppDlqIndexRoute: typeof AppDlqIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
  AppSchedulesIndexRoute: typeof AppSchedulesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/app/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/layout': {
      id: '/app/layout'
      path: '/app/layout'
      fullPath: '/app/layout'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/two-factor': {
      id: '/(auth)/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof authTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sso': {
      id: '/(auth)/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof authSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/device': {
      id: '/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof authDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/app/workflows'
      fullPath: '/app/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/webhooks/': {
      id: '/app/webhooks/'
      path: '/app/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedules/': {
      id: '/app/schedules/'
      path: '/app/schedules'
      fullPath: '/app/schedules/'
      preLoaderRoute: typeof AppSchedulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/runs/': {
      id: '/app/runs/'
      path: '/app/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/logs/': {
      id: '/app/logs/'
      path: '/app/logs'
      fullPath: '/app/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/app/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/app/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dlq/': {
      id: '/app/dlq/'
      path: '/app/dlq'
      fullPath: '/app/dlq/'
      preLoaderRoute: typeof AppDlqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/$id': {
      id: '/app/workflows/$id'
      path: '/app/workflows/$id'
      fullPath: '/app/workflows/$id'
      preLoaderRoute: typeof AppWorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedules/$id': {
      id: '/app/schedules/$id'
      path: '/app/schedules/$id'
      fullPath: '/app/schedules/$id'
      preLoaderRoute: typeof AppSchedulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/app/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/$id': {
      id: '/app/org/$id'
      path: '/app/org/$id'
      fullPath: '/app/org/$id'
      preLoaderRoute: typeof AppOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/app/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authDeviceRoute: authDeviceRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authSsoRoute: authSsoRoute,
  authTwoFactorRoute: authTwoFactorRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLayoutRoute: AppLayoutRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  InvitationIdRoute: InvitationIdRoute,
  AppIndexRoute: AppIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppOrgIdRoute: AppOrgIdRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppSchedulesIdRoute: AppSchedulesIdRoute,
  AppWorkflowsIdRoute: AppWorkflowsIdRoute,
  AppDlqIndexRoute: AppDlqIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
  AppSchedulesIndexRoute: AppSchedulesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
