# frozen_string_literal: true

module Strait
  module FSM
    WORKFLOW_RUN_PENDING = "pending"
    WORKFLOW_RUN_RUNNING = "running"
    WORKFLOW_RUN_PAUSED = "paused"
    WORKFLOW_RUN_COMPLETED = "completed"
    WORKFLOW_RUN_FAILED = "failed"
    WORKFLOW_RUN_TIMED_OUT = "timed_out"
    WORKFLOW_RUN_CANCELED = "canceled"

    WORKFLOW_RUN_EVENT_START = "START"
    WORKFLOW_RUN_EVENT_PAUSE = "PAUSE"
    WORKFLOW_RUN_EVENT_RESUME = "RESUME"
    WORKFLOW_RUN_EVENT_COMPLETE = "COMPLETE"
    WORKFLOW_RUN_EVENT_FAIL = "FAIL"
    WORKFLOW_RUN_EVENT_TIMEOUT = "TIMEOUT"
    WORKFLOW_RUN_EVENT_CANCEL = "CANCEL"

    TERMINAL_WORKFLOW_RUN_STATUSES = [
      WORKFLOW_RUN_COMPLETED, WORKFLOW_RUN_FAILED,
      WORKFLOW_RUN_TIMED_OUT, WORKFLOW_RUN_CANCELED
    ].freeze

    WORKFLOW_RUN_TRANSITIONS = {
      [WORKFLOW_RUN_PENDING, WORKFLOW_RUN_EVENT_START] => WORKFLOW_RUN_RUNNING,
      [WORKFLOW_RUN_PENDING, WORKFLOW_RUN_EVENT_CANCEL] => WORKFLOW_RUN_CANCELED,
      [WORKFLOW_RUN_RUNNING, WORKFLOW_RUN_EVENT_PAUSE] => WORKFLOW_RUN_PAUSED,
      [WORKFLOW_RUN_RUNNING, WORKFLOW_RUN_EVENT_COMPLETE] => WORKFLOW_RUN_COMPLETED,
      [WORKFLOW_RUN_RUNNING, WORKFLOW_RUN_EVENT_FAIL] => WORKFLOW_RUN_FAILED,
      [WORKFLOW_RUN_RUNNING, WORKFLOW_RUN_EVENT_TIMEOUT] => WORKFLOW_RUN_TIMED_OUT,
      [WORKFLOW_RUN_RUNNING, WORKFLOW_RUN_EVENT_CANCEL] => WORKFLOW_RUN_CANCELED,
      [WORKFLOW_RUN_PAUSED, WORKFLOW_RUN_EVENT_RESUME] => WORKFLOW_RUN_RUNNING,
      [WORKFLOW_RUN_PAUSED, WORKFLOW_RUN_EVENT_CANCEL] => WORKFLOW_RUN_CANCELED,
    }.freeze

    def self.can_transition_workflow_run?(from, event)
      WORKFLOW_RUN_TRANSITIONS.key?([from, event])
    end

    def self.transition_workflow_run(from, event)
      to = WORKFLOW_RUN_TRANSITIONS[[from, event]]
      raise ArgumentError, "invalid workflow run transition: #{from} + #{event}" unless to
      to
    end

    def self.terminal_workflow_run_status?(status)
      TERMINAL_WORKFLOW_RUN_STATUSES.include?(status)
    end
  end
end
