// Code generated by packages/billing/scripts/generate-catalog.mjs; DO NOT EDIT.
// Source: packages/billing/catalog/strait-pricing.json
// Catalog SHA256: 78501aa16e50f7cf06e2e0cbb2dc807cbe237b804aa5291c273611628493f76d
package billing

import "strait/internal/domain"

const PricingCatalogVersion = "2026-05-21"
const PricingCatalogHash = "78501aa16e50f7cf06e2e0cbb2dc807cbe237b804aa5291c273611628493f76d"
const MeteredUnit = "orchestration_run"

// HTTPCostPerRunMicrousd is the per-run cost for HTTP execution mode.
// 20 micro-USD = $0.00002/run = $20/1M runs.
const HTTPCostPerRunMicrousd int64 = 20

// WorkerCostPerRunMicrousd is the per-run cost for Worker execution mode.
// Flat rate matching HTTP dispatch.
const WorkerCostPerRunMicrousd int64 = 20

// WebhookDeliveryCostPerRunMicrousd is the per-successful-delivery cost for
// outbound webhook deliveries. Billed once on eventual success; failed
// deliveries that never succeed are not billed.
const WebhookDeliveryCostPerRunMicrousd int64 = 20

const DefaultOveragePerKMicrousd int64 = 500_000

const (
	PriceFreeMonthlyCents         = 0
	PriceFreeAnnualCents          = 0
	CreditFreeMicrousd      int64 = 1000000
	MaxRunsPerMonthFree           = 5000
	ConcurrentFree                = 3
	FreeOveragePerKMicrousd int64 = 500000
	RetentionFree                 = 7
	MaxOrgsFree                   = 1
	MaxProjectsFree               = 1
	MaxMembersFree                = 1
	MaxSpendingFree         int64 = 50000000
	MaxDAGStepsFree               = 10
	MaxScheduledFree              = 1
	CronMinIntervalFreeSec        = 300
	MaxDispatchPriorityFree       = 10
	WorkerConnectionsFree         = 1
	APIRateFree                   = 60

	PriceStarterMonthlyCents         = 1900
	PriceStarterAnnualCents          = 18000
	CreditStarterMicrousd      int64 = 19000000
	MaxRunsPerMonthStarter           = 50000
	ConcurrentStarter                = 15
	StarterOveragePerKMicrousd int64 = 400000
	RetentionStarter                 = 14
	MaxOrgsStarter                   = 2
	MaxProjectsStarter               = 3
	MaxMembersStarter                = 3
	MaxSpendingStarter         int64 = 100000000
	MaxDAGStepsStarter               = 25
	MaxScheduledStarter              = 5
	CronMinIntervalStarterSec        = 60
	MaxDispatchPriorityStarter       = 10
	WorkerConnectionsStarter         = 5
	APIRateStarter                   = 300

	PriceProMonthlyCents         = 9900
	PriceProAnnualCents          = 94800
	CreditProMicrousd      int64 = 99000000
	MaxRunsPerMonthPro           = 1000000
	ConcurrentPro                = 100
	ProOveragePerKMicrousd int64 = 200000
	RetentionPro                 = 30
	MaxOrgsPro                   = 5
	MaxProjectsPro               = 10
	MaxMembersPro                = 10
	MaxSpendingPro         int64 = 200000000
	MaxDAGStepsPro               = 100
	MaxScheduledPro              = 25
	CronMinIntervalProSec        = 30
	MaxDispatchPriorityPro       = 10
	WorkerConnectionsPro         = 25
	APIRatePro                   = 1000

	PriceScaleMonthlyCents         = 29900
	PriceScaleAnnualCents          = 286800
	CreditScaleMicrousd      int64 = 299000000
	MaxRunsPerMonthScale           = 5000000
	ConcurrentScale                = 300
	ScaleOveragePerKMicrousd int64 = 60000
	RetentionScale                 = 60
	MaxOrgsScale                   = 10
	MaxProjectsScale               = 50
	MaxMembersScale                = 50
	MaxSpendingScale         int64 = 500000000
	MaxDAGStepsScale               = 500
	MaxScheduledScale              = 100
	CronMinIntervalScaleSec        = 1
	MaxDispatchPriorityScale       = 10
	WorkerConnectionsScale         = 100
	APIRateScale                   = 3000

	PriceBusinessMonthlyCents         = 49900
	PriceBusinessAnnualCents          = 478800
	CreditBusinessMicrousd      int64 = 499000000
	MaxRunsPerMonthBusiness           = 25000000
	ConcurrentBusiness                = 500
	BusinessOveragePerKMicrousd int64 = 30000
	RetentionBusiness                 = 90
	MaxOrgsBusiness                   = -1
	MaxProjectsBusiness               = -1
	MaxMembersBusiness                = -1
	MaxSpendingBusiness         int64 = 1500000000
	MaxDAGStepsBusiness               = -1
	MaxScheduledBusiness              = -1
	CronMinIntervalBusinessSec        = 0
	MaxDispatchPriorityBusiness       = 10
	WorkerConnectionsBusiness         = -1
	APIRateBusiness                   = -1

	PriceEnterpriseMonthlyCents         = 0
	PriceEnterpriseAnnualCents          = 0
	CreditEnterpriseMicrousd      int64 = 0
	MaxRunsPerMonthEnterprise           = -1
	ConcurrentEnterprise                = -1
	EnterpriseOveragePerKMicrousd int64 = 30000
	RetentionEnterprise                 = -1
	MaxOrgsEnterprise                   = -1
	MaxProjectsEnterprise               = -1
	MaxMembersEnterprise                = -1
	MaxSpendingEnterprise         int64 = -1
	MaxDAGStepsEnterprise               = -1
	MaxScheduledEnterprise              = -1
	CronMinIntervalEnterpriseSec        = 0
	MaxDispatchPriorityEnterprise       = 10
	WorkerConnectionsEnterprise         = -1
	APIRateEnterprise                   = -1
)

// Plans maps plan tiers to their limits.
var Plans = map[domain.PlanTier]OrgPlanLimits{
	domain.PlanFree: {
		PlanTier:                domain.PlanFree,
		DisplayName:             "Free",
		PriceMonthlyUsd:         PriceFreeMonthlyCents,
		PriceAnnualUsd:          PriceFreeAnnualCents,
		MaxOrgsPerUser:          MaxOrgsFree,
		MaxProjectsPerOrg:       MaxProjectsFree,
		MaxMembersPerOrg:        MaxMembersFree,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthFree,
		OveragePerKMicrousd:     FreeOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentFree,
		RetentionDays:           RetentionFree,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   0,
		MaxLogDrainsPerOrg:      0,
		MaxNotificationChannels: 0,
		HasRBAC:                 false,
		RBACLevel:               "",
		HasAuditLogs:            false,
		HasSSO:                  false,
		HasSLA:                  false,
		RequiresCreditCard:      false,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     false,
		MaxDispatchPriority:     MaxDispatchPriorityFree,
		WorkerConnections:       WorkerConnectionsFree,
		SupportLevel:            "community",
		MaxWorkflowDAGSteps:     MaxDAGStepsFree,
		HasApprovalGates:        false,
		HasSubWorkflows:         false,
		HasJobChaining:          false,
		MaxJobChainDepth:        0,
		HasCompensatingTxns:     false,
		HasCanaryDeployments:    false,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledFree,
		CronMinIntervalSec:      CronMinIntervalFreeSec,
		AllCronOverlapPolicies:  false,
		MaxEnvironments:         1,
		MaxWebhookEndpoints:     0,
		WebhookEventLevel:       "none",
		APIRateLimit:            APIRateFree,
		MaxAddonPacks:           nil,
	},
	domain.PlanStarter: {
		PlanTier:                domain.PlanStarter,
		DisplayName:             "Starter",
		PriceMonthlyUsd:         PriceStarterMonthlyCents,
		PriceAnnualUsd:          PriceStarterAnnualCents,
		MaxOrgsPerUser:          MaxOrgsStarter,
		MaxProjectsPerOrg:       MaxProjectsStarter,
		MaxMembersPerOrg:        MaxMembersStarter,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthStarter,
		OveragePerKMicrousd:     StarterOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentStarter,
		RetentionDays:           RetentionStarter,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   3,
		MaxLogDrainsPerOrg:      1,
		MaxNotificationChannels: 1,
		HasRBAC:                 true,
		RBACLevel:               "basic",
		HasAuditLogs:            false,
		HasSSO:                  false,
		HasSLA:                  false,
		RequiresCreditCard:      true,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     true,
		MaxDispatchPriority:     MaxDispatchPriorityStarter,
		WorkerConnections:       WorkerConnectionsStarter,
		SupportLevel:            "email_72h",
		MaxWorkflowDAGSteps:     MaxDAGStepsStarter,
		HasApprovalGates:        false,
		HasSubWorkflows:         false,
		HasJobChaining:          false,
		MaxJobChainDepth:        0,
		HasCompensatingTxns:     false,
		HasCanaryDeployments:    false,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledStarter,
		CronMinIntervalSec:      CronMinIntervalStarterSec,
		AllCronOverlapPolicies:  true,
		MaxEnvironments:         1,
		MaxWebhookEndpoints:     3,
		WebhookEventLevel:       "basic",
		APIRateLimit:            APIRateStarter,
		MaxAddonPacks:           nil,
	},
	domain.PlanPro: {
		PlanTier:                domain.PlanPro,
		DisplayName:             "Pro",
		PriceMonthlyUsd:         PriceProMonthlyCents,
		PriceAnnualUsd:          PriceProAnnualCents,
		MaxOrgsPerUser:          MaxOrgsPro,
		MaxProjectsPerOrg:       MaxProjectsPro,
		MaxMembersPerOrg:        MaxMembersPro,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthPro,
		OveragePerKMicrousd:     ProOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentPro,
		RetentionDays:           RetentionPro,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   10,
		MaxLogDrainsPerOrg:      5,
		MaxNotificationChannels: 5,
		HasRBAC:                 true,
		RBACLevel:               "full",
		HasAuditLogs:            false,
		HasSSO:                  false,
		HasSLA:                  false,
		RequiresCreditCard:      true,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     true,
		MaxDispatchPriority:     MaxDispatchPriorityPro,
		WorkerConnections:       WorkerConnectionsPro,
		SupportLevel:            "priority_24h",
		MaxWorkflowDAGSteps:     MaxDAGStepsPro,
		HasApprovalGates:        true,
		HasSubWorkflows:         true,
		HasJobChaining:          true,
		MaxJobChainDepth:        10,
		HasCompensatingTxns:     true,
		HasCanaryDeployments:    false,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledPro,
		CronMinIntervalSec:      CronMinIntervalProSec,
		AllCronOverlapPolicies:  true,
		MaxEnvironments:         3,
		MaxWebhookEndpoints:     10,
		WebhookEventLevel:       "all",
		APIRateLimit:            APIRatePro,
		MaxAddonPacks: map[AddonType]int{
			AddonConcurrency100: -1,
			AddonEnvironments5:  -1,
		},
	},
	domain.PlanScale: {
		PlanTier:                domain.PlanScale,
		DisplayName:             "Scale",
		PriceMonthlyUsd:         PriceScaleMonthlyCents,
		PriceAnnualUsd:          PriceScaleAnnualCents,
		MaxOrgsPerUser:          MaxOrgsScale,
		MaxProjectsPerOrg:       MaxProjectsScale,
		MaxMembersPerOrg:        MaxMembersScale,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthScale,
		OveragePerKMicrousd:     ScaleOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentScale,
		RetentionDays:           RetentionScale,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   25,
		MaxLogDrainsPerOrg:      10,
		MaxNotificationChannels: 10,
		HasRBAC:                 true,
		RBACLevel:               "full",
		HasAuditLogs:            true,
		HasSSO:                  false,
		HasSLA:                  false,
		RequiresCreditCard:      true,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     true,
		MaxDispatchPriority:     MaxDispatchPriorityScale,
		WorkerConnections:       WorkerConnectionsScale,
		SupportLevel:            "priority_slack_8h",
		MaxWorkflowDAGSteps:     MaxDAGStepsScale,
		HasApprovalGates:        true,
		HasSubWorkflows:         true,
		HasJobChaining:          true,
		MaxJobChainDepth:        10,
		HasCompensatingTxns:     true,
		HasCanaryDeployments:    true,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledScale,
		CronMinIntervalSec:      CronMinIntervalScaleSec,
		AllCronOverlapPolicies:  true,
		MaxEnvironments:         10,
		MaxWebhookEndpoints:     25,
		WebhookEventLevel:       "all",
		APIRateLimit:            APIRateScale,
		MaxAddonPacks: map[AddonType]int{
			AddonConcurrency100: -1,
			AddonHistory30d:     10,
			AddonEnvironments5:  -1,
		},
	},
	domain.PlanBusiness: {
		PlanTier:                domain.PlanBusiness,
		DisplayName:             "Business",
		PriceMonthlyUsd:         PriceBusinessMonthlyCents,
		PriceAnnualUsd:          PriceBusinessAnnualCents,
		MaxOrgsPerUser:          MaxOrgsBusiness,
		MaxProjectsPerOrg:       MaxProjectsBusiness,
		MaxMembersPerOrg:        MaxMembersBusiness,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthBusiness,
		OveragePerKMicrousd:     BusinessOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentBusiness,
		RetentionDays:           RetentionBusiness,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   -1,
		MaxLogDrainsPerOrg:      -1,
		MaxNotificationChannels: -1,
		HasRBAC:                 true,
		RBACLevel:               "advanced",
		HasAuditLogs:            true,
		HasSSO:                  false,
		HasSLA:                  true,
		RequiresCreditCard:      true,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     true,
		MaxDispatchPriority:     MaxDispatchPriorityBusiness,
		WorkerConnections:       WorkerConnectionsBusiness,
		SupportLevel:            "priority_slack_8h",
		MaxWorkflowDAGSteps:     MaxDAGStepsBusiness,
		HasApprovalGates:        true,
		HasSubWorkflows:         true,
		HasJobChaining:          true,
		MaxJobChainDepth:        -1,
		HasCompensatingTxns:     true,
		HasCanaryDeployments:    true,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledBusiness,
		CronMinIntervalSec:      CronMinIntervalBusinessSec,
		AllCronOverlapPolicies:  true,
		MaxEnvironments:         -1,
		MaxWebhookEndpoints:     -1,
		WebhookEventLevel:       "all",
		APIRateLimit:            APIRateBusiness,
		MaxAddonPacks: map[AddonType]int{
			AddonConcurrency100: -1,
			AddonHistory30d:     9,
		},
	},
	domain.PlanEnterprise: {
		PlanTier:                domain.PlanEnterprise,
		DisplayName:             "Enterprise",
		PriceMonthlyUsd:         PriceEnterpriseMonthlyCents,
		PriceAnnualUsd:          PriceEnterpriseAnnualCents,
		MaxOrgsPerUser:          MaxOrgsEnterprise,
		MaxProjectsPerOrg:       MaxProjectsEnterprise,
		MaxMembersPerOrg:        MaxMembersEnterprise,
		MaxRunsPerDay:           -1,
		MaxRunsPerMonth:         MaxRunsPerMonthEnterprise,
		OveragePerKMicrousd:     EnterpriseOveragePerKMicrousd,
		MaxConcurrentRuns:       ConcurrentEnterprise,
		RetentionDays:           RetentionEnterprise,
		AllowedRegions:          []string{"iad"},
		MaxAlertRulesPerProj:    0,
		MaxWebhookSubsPerProj:   -1,
		MaxLogDrainsPerOrg:      -1,
		MaxNotificationChannels: -1,
		HasRBAC:                 true,
		RBACLevel:               "full",
		HasAuditLogs:            true,
		HasSSO:                  false,
		HasSLA:                  true,
		RequiresCreditCard:      false,
		AllowsHTTPMode:          true,
		LogStreamingEnabled:     true,
		MaxDispatchPriority:     MaxDispatchPriorityEnterprise,
		WorkerConnections:       WorkerConnectionsEnterprise,
		SupportLevel:            "dedicated",
		MaxWorkflowDAGSteps:     MaxDAGStepsEnterprise,
		HasApprovalGates:        true,
		HasSubWorkflows:         true,
		HasJobChaining:          true,
		MaxJobChainDepth:        -1,
		HasCompensatingTxns:     true,
		HasCanaryDeployments:    true,
		HasDedicatedCompute:     false,
		HasStaticIPs:            false,
		HasVPCPeering:           false,
		HasSCIM:                 false,
		HasDataResidency:        false,
		HasCustomRBAC:           false,
		HasPriorityQueue:        false,
		HasIPAllowlisting:       false,
		HasSessionManagement:    false,
		HasSecretRotation:       false,
		HasSIEMExport:           false,
		MaxScheduledJobs:        MaxScheduledEnterprise,
		CronMinIntervalSec:      CronMinIntervalEnterpriseSec,
		AllCronOverlapPolicies:  true,
		MaxEnvironments:         -1,
		MaxWebhookEndpoints:     -1,
		WebhookEventLevel:       "all_custom",
		APIRateLimit:            APIRateEnterprise,
		MaxAddonPacks:           nil,
	},
}
