/* eslint-disable */
// This file is generated by scripts/generate-contracts.ts

import type { GeneratedOperationId } from "../../contracts/_generated/contracts";
import type {
  OperationRequestBodyById,
  OperationResponseBodyById,
} from "../../schema/_generated/schema";

export type OperationPathParamsById = {
  "getHealth": undefined;
  "getHealthReady": undefined;
  "getMetrics": undefined;
  "postSdkV1RunsByRunIDAnnotate": { "runID": string };
  "postSdkV1RunsByRunIDCheckpoint": { "runID": string };
  "postSdkV1RunsByRunIDComplete": { "runID": string };
  "postSdkV1RunsByRunIDContinue": { "runID": string };
  "postSdkV1RunsByRunIDFail": { "runID": string };
  "postSdkV1RunsByRunIDHeartbeat": { "runID": string };
  "postSdkV1RunsByRunIDIteration": { "runID": string };
  "postSdkV1RunsByRunIDLog": { "runID": string };
  "getSdkV1RunsByRunIDMemory": { "runID": string };
  "deleteSdkV1RunsByRunIDMemoryByKey": { "runID": string; "key": string };
  "getSdkV1RunsByRunIDMemoryByKey": { "runID": string; "key": string };
  "postSdkV1RunsByRunIDMemoryByKey": { "runID": string; "key": string };
  "postSdkV1RunsByRunIDOutput": { "runID": string };
  "getSdkV1RunsByRunIDPayload": { "runID": string };
  "postSdkV1RunsByRunIDProgress": { "runID": string };
  "postSdkV1RunsByRunIDResourceSnapshot": { "runID": string };
  "postSdkV1RunsByRunIDResources": { "runID": string };
  "postSdkV1RunsByRunIDSpawn": { "runID": string };
  "getSdkV1RunsByRunIDState": { "runID": string };
  "postSdkV1RunsByRunIDState": { "runID": string };
  "deleteSdkV1RunsByRunIDStateByKey": { "runID": string; "key": string };
  "getSdkV1RunsByRunIDStateByKey": { "runID": string; "key": string };
  "postSdkV1RunsByRunIDStream": { "runID": string };
  "postSdkV1RunsByRunIDToolCall": { "runID": string };
  "postSdkV1RunsByRunIDUsage": { "runID": string };
  "postSdkV1RunsByRunIDWaitForEvent": { "runID": string };
  "getV1AnalyticsApprovals": undefined;
  "getV1AnalyticsCompute": undefined;
  "getV1AnalyticsCostInsights": undefined;
  "getV1AnalyticsCosts": undefined;
  "getV1AnalyticsCostsTop": undefined;
  "getV1AnalyticsCostsTrends": undefined;
  "getV1AnalyticsPerformance": undefined;
  "getV1ApiKeys": undefined;
  "postV1ApiKeys": undefined;
  "deleteV1ApiKeysByKeyID": { "keyID": string };
  "postV1ApiKeysByKeyIDRotate": { "keyID": string };
  "getV1AuditEvents": undefined;
  "getV1AuditEventsExport": undefined;
  "getV1BatchOperations": undefined;
  "getV1BatchOperationsByBatchID": { "batchID": string };
  "getV1Deployments": undefined;
  "postV1Deployments": undefined;
  "postV1DeploymentsByDeploymentIDFinalize": { "deploymentID": string };
  "postV1DeploymentsByDeploymentIDPromote": { "deploymentID": string };
  "postV1DeploymentsByDeploymentIDRollback": { "deploymentID": string };
  "getV1Environments": undefined;
  "postV1Environments": undefined;
  "deleteV1EnvironmentsByEnvID": { "envID": string };
  "getV1EnvironmentsByEnvID": { "envID": string };
  "patchV1EnvironmentsByEnvID": { "envID": string };
  "getV1EnvironmentsByEnvIDVariables": { "envID": string };
  "getV1EventSources": undefined;
  "postV1EventSources": undefined;
  "deleteV1EventSourcesBySourceID": { "sourceID": string };
  "getV1EventSourcesBySourceID": { "sourceID": string };
  "patchV1EventSourcesBySourceID": { "sourceID": string };
  "postV1EventSourcesBySourceIDSubscribe": { "sourceID": string };
  "getV1EventSourcesBySourceIDSubscriptions": { "sourceID": string };
  "deleteV1EventSourcesBySourceIDSubscriptionsBySubID": { "sourceID": string; "subID": string };
  "getV1Events": undefined;
  "deleteV1EventsByEventKey": { "eventKey": string };
  "getV1EventsByEventKey": { "eventKey": string };
  "postV1EventsByEventKeySend": { "eventKey": string };
  "getV1EventsByEventKeyStream": { "eventKey": string };
  "postV1EventsDispatch": undefined;
  "postV1EventsPrefixByPrefixSend": { "prefix": string };
  "postV1EventsPurge": undefined;
  "getV1EventsStats": undefined;
  "getV1JobGroups": undefined;
  "postV1JobGroups": undefined;
  "deleteV1JobGroupsByGroupID": { "groupID": string };
  "getV1JobGroupsByGroupID": { "groupID": string };
  "patchV1JobGroupsByGroupID": { "groupID": string };
  "getV1JobGroupsByGroupIDJobs": { "groupID": string };
  "postV1JobGroupsByGroupIDPauseAll": { "groupID": string };
  "postV1JobGroupsByGroupIDResumeAll": { "groupID": string };
  "getV1JobGroupsByGroupIDStats": { "groupID": string };
  "getV1Jobs": undefined;
  "postV1Jobs": undefined;
  "deleteV1JobsByJobID": { "jobID": string };
  "getV1JobsByJobID": { "jobID": string };
  "patchV1JobsByJobID": { "jobID": string };
  "postV1JobsByJobIDClone": { "jobID": string };
  "getV1JobsByJobIDDependencies": { "jobID": string };
  "postV1JobsByJobIDDependencies": { "jobID": string };
  "deleteV1JobsByJobIDDependenciesByDepID": { "jobID": string; "depID": string };
  "getV1JobsByJobIDHealth": { "jobID": string };
  "postV1JobsByJobIDTrigger": { "jobID": string };
  "postV1JobsByJobIDTriggerBulk": { "jobID": string };
  "getV1JobsByJobIDVersions": { "jobID": string };
  "getV1JobsByJobIDVersionsByVersionID": { "jobID": string; "versionID": string };
  "postV1JobsBatch": undefined;
  "postV1JobsBatchDisable": undefined;
  "postV1JobsBatchEnable": undefined;
  "getV1LogDrains": undefined;
  "postV1LogDrains": undefined;
  "deleteV1LogDrainsByDrainID": { "drainID": string };
  "getV1LogDrainsByDrainID": { "drainID": string };
  "patchV1LogDrainsByDrainID": { "drainID": string };
  "getV1Members": undefined;
  "postV1Members": undefined;
  "deleteV1MembersByUserID": { "userID": string };
  "postV1MembersBulk": undefined;
  "getV1NotificationChannels": undefined;
  "postV1NotificationChannels": undefined;
  "deleteV1NotificationChannelsByChannelID": { "channelID": string };
  "getV1NotificationChannelsByChannelID": { "channelID": string };
  "patchV1NotificationChannelsByChannelID": { "channelID": string };
  "getV1NotificationDeliveries": undefined;
  "getV1ProjectsByProjectIDSettings": { "projectID": string };
  "putV1ProjectsByProjectIDSettings": { "projectID": string };
  "getV1Regions": undefined;
  "getV1ResourcePolicies": undefined;
  "postV1ResourcePolicies": undefined;
  "deleteV1ResourcePoliciesByPolicyID": { "policyID": string };
  "getV1Roles": undefined;
  "postV1Roles": undefined;
  "deleteV1RolesByRoleID": { "roleID": string };
  "getV1RolesByRoleID": { "roleID": string };
  "patchV1RolesByRoleID": { "roleID": string };
  "getV1Runs": undefined;
  "deleteV1RunsByRunID": { "runID": string };
  "getV1RunsByRunID": { "runID": string };
  "getV1RunsByRunIDCheckpoints": { "runID": string };
  "getV1RunsByRunIDChildren": { "runID": string };
  "postV1RunsByRunIDDebug": { "runID": string };
  "getV1RunsByRunIDDebugBundle": { "runID": string };
  "getV1RunsByRunIDDependencyStatus": { "runID": string };
  "postV1RunsByRunIDDlqReplay": { "runID": string };
  "getV1RunsByRunIDEvents": { "runID": string };
  "deleteV1RunsByRunIDIdempotencyKey": { "runID": string };
  "getV1RunsByRunIDLineage": { "runID": string };
  "getV1RunsByRunIDOutputs": { "runID": string };
  "postV1RunsByRunIDPause": { "runID": string };
  "postV1RunsByRunIDReplay": { "runID": string };
  "postV1RunsByRunIDReschedule": { "runID": string };
  "getV1RunsByRunIDResources": { "runID": string };
  "postV1RunsByRunIDRestart": { "runID": string };
  "postV1RunsByRunIDResume": { "runID": string };
  "getV1RunsByRunIDState": { "runID": string };
  "getV1RunsByRunIDStream": { "runID": string };
  "getV1RunsByRunIDStreamChunks": { "runID": string };
  "getV1RunsByRunIDToolCalls": { "runID": string };
  "getV1RunsByRunIDUsage": { "runID": string };
  "postV1RunsBulkCancel": undefined;
  "postV1RunsBulkCancelAll": undefined;
  "postV1RunsBulkDlqReplay": undefined;
  "postV1RunsBulkReplay": undefined;
  "getV1RunsDlq": undefined;
  "getV1Secrets": undefined;
  "postV1Secrets": undefined;
  "deleteV1SecretsBySecretID": { "secretID": string };
  "postV1SeedRoles": undefined;
  "getV1Stats": undefined;
  "getV1TagPolicies": undefined;
  "postV1TagPolicies": undefined;
  "deleteV1TagPoliciesByPolicyID": { "policyID": string };
  "getV1WebhookDeliveries": undefined;
  "postV1WebhookDeliveriesByDeliveryIDRetry": { "deliveryID": string };
  "getV1WebhooksDeliveries": undefined;
  "getV1WebhooksDeliveriesById": { "id": string };
  "postV1WebhooksDeliveriesByIdReplay": { "id": string };
  "postV1WebhooksDeliveriesByIdRetry": { "id": string };
  "getV1WebhooksSubscriptions": undefined;
  "postV1WebhooksSubscriptions": undefined;
  "deleteV1WebhooksSubscriptionsById": { "id": string };
  "postV1WebhooksTest": undefined;
  "getV1WorkflowPoliciesByProjectID": { "projectID": string };
  "putV1WorkflowPoliciesByProjectID": { "projectID": string };
  "getV1WorkflowRuns": undefined;
  "deleteV1WorkflowRunsByWorkflowRunID": { "workflowRunID": string };
  "getV1WorkflowRunsByWorkflowRunID": { "workflowRunID": string };
  "getV1WorkflowRunsByWorkflowRunIDExplain": { "workflowRunID": string };
  "getV1WorkflowRunsByWorkflowRunIDGraph": { "workflowRunID": string };
  "getV1WorkflowRunsByWorkflowRunIDLabels": { "workflowRunID": string };
  "postV1WorkflowRunsByWorkflowRunIDPause": { "workflowRunID": string };
  "postV1WorkflowRunsByWorkflowRunIDResume": { "workflowRunID": string };
  "postV1WorkflowRunsByWorkflowRunIDRetry": { "workflowRunID": string };
  "getV1WorkflowRunsByWorkflowRunIDSteps": { "workflowRunID": string };
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefApprove": { "workflowRunID": string; "stepRef": string };
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefForceComplete": { "workflowRunID": string; "stepRef": string };
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefReplaySubtree": { "workflowRunID": string; "stepRef": string };
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefRetry": { "workflowRunID": string; "stepRef": string };
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefSkip": { "workflowRunID": string; "stepRef": string };
  "getV1WorkflowRunsByWorkflowRunIDTimeline": { "workflowRunID": string };
  "postV1WorkflowRunsBulkCancel": undefined;
  "postV1WorkflowRunsBulkReplay": undefined;
  "getV1Workflows": undefined;
  "postV1Workflows": undefined;
  "deleteV1WorkflowsByWorkflowID": { "workflowID": string };
  "getV1WorkflowsByWorkflowID": { "workflowID": string };
  "patchV1WorkflowsByWorkflowID": { "workflowID": string };
  "getV1WorkflowsByWorkflowIDActiveVersions": { "workflowID": string };
  "postV1WorkflowsByWorkflowIDClone": { "workflowID": string };
  "postV1WorkflowsByWorkflowIDDryRun": { "workflowID": string };
  "getV1WorkflowsByWorkflowIDGraph": { "workflowID": string };
  "postV1WorkflowsByWorkflowIDPlan": { "workflowID": string };
  "getV1WorkflowsByWorkflowIDRuns": { "workflowID": string };
  "postV1WorkflowsByWorkflowIDSimulate": { "workflowID": string };
  "postV1WorkflowsByWorkflowIDTrigger": { "workflowID": string };
  "getV1WorkflowsByWorkflowIDVersions": { "workflowID": string };
  "getV1WorkflowsByWorkflowIDVersionsByFromVersionIDDiffByToVersionID": { "workflowID": string; "fromVersionID": string; "toVersionID": string };
  "getV1WorkflowsByWorkflowIDVersionsByVersionID": { "workflowID": string; "versionID": string };
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDImpact": { "workflowID": string; "versionID": string };
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDSteps": { "workflowID": string; "versionID": string };
};

export type OperationQueryParamsById = {
  "getHealth": undefined;
  "getHealthReady": undefined;
  "getMetrics": undefined;
  "postSdkV1RunsByRunIDAnnotate": undefined;
  "postSdkV1RunsByRunIDCheckpoint": undefined;
  "postSdkV1RunsByRunIDComplete": undefined;
  "postSdkV1RunsByRunIDContinue": undefined;
  "postSdkV1RunsByRunIDFail": undefined;
  "postSdkV1RunsByRunIDHeartbeat": undefined;
  "postSdkV1RunsByRunIDIteration": undefined;
  "postSdkV1RunsByRunIDLog": undefined;
  "getSdkV1RunsByRunIDMemory": undefined;
  "deleteSdkV1RunsByRunIDMemoryByKey": undefined;
  "getSdkV1RunsByRunIDMemoryByKey": undefined;
  "postSdkV1RunsByRunIDMemoryByKey": undefined;
  "postSdkV1RunsByRunIDOutput": undefined;
  "getSdkV1RunsByRunIDPayload": undefined;
  "postSdkV1RunsByRunIDProgress": undefined;
  "postSdkV1RunsByRunIDResourceSnapshot": undefined;
  "postSdkV1RunsByRunIDResources": undefined;
  "postSdkV1RunsByRunIDSpawn": undefined;
  "getSdkV1RunsByRunIDState": undefined;
  "postSdkV1RunsByRunIDState": undefined;
  "deleteSdkV1RunsByRunIDStateByKey": undefined;
  "getSdkV1RunsByRunIDStateByKey": undefined;
  "postSdkV1RunsByRunIDStream": undefined;
  "postSdkV1RunsByRunIDToolCall": undefined;
  "postSdkV1RunsByRunIDUsage": undefined;
  "postSdkV1RunsByRunIDWaitForEvent": undefined;
  "getV1AnalyticsApprovals": { "from": string; "to": string };
  "getV1AnalyticsCompute": { "from": string; "to": string };
  "getV1AnalyticsCostInsights": { "from": string; "to": string; "threshold"?: number };
  "getV1AnalyticsCosts": { "from": string; "to": string };
  "getV1AnalyticsCostsTop": { "from": string; "to": string; "limit"?: number };
  "getV1AnalyticsCostsTrends": { "from": string; "to": string };
  "getV1AnalyticsPerformance": { "period_hours"?: number };
  "getV1ApiKeys": { "project_id": string };
  "postV1ApiKeys": undefined;
  "deleteV1ApiKeysByKeyID": undefined;
  "postV1ApiKeysByKeyIDRotate": undefined;
  "getV1AuditEvents": { "project_id"?: string; "actor_id"?: string; "resource_type"?: string; "resource_id"?: string; "limit"?: number; "cursor"?: string; "from"?: string; "to"?: string; "order"?: "asc" | "desc" };
  "getV1AuditEventsExport": { "from": string; "to": string; "format"?: "json" | "csv" | "ndjson" };
  "getV1BatchOperations": { "project_id": string; "limit"?: number; "cursor"?: string };
  "getV1BatchOperationsByBatchID": { "project_id": string };
  "getV1Deployments": { "project_id": string; "environment"?: string; "limit"?: number; "cursor"?: string };
  "postV1Deployments": undefined;
  "postV1DeploymentsByDeploymentIDFinalize": undefined;
  "postV1DeploymentsByDeploymentIDPromote": undefined;
  "postV1DeploymentsByDeploymentIDRollback": undefined;
  "getV1Environments": { "project_id": string };
  "postV1Environments": undefined;
  "deleteV1EnvironmentsByEnvID": undefined;
  "getV1EnvironmentsByEnvID": undefined;
  "patchV1EnvironmentsByEnvID": undefined;
  "getV1EnvironmentsByEnvIDVariables": undefined;
  "getV1EventSources": { "project_id": string };
  "postV1EventSources": undefined;
  "deleteV1EventSourcesBySourceID": { "project_id": string };
  "getV1EventSourcesBySourceID": { "project_id": string };
  "patchV1EventSourcesBySourceID": { "project_id": string };
  "postV1EventSourcesBySourceIDSubscribe": undefined;
  "getV1EventSourcesBySourceIDSubscriptions": undefined;
  "deleteV1EventSourcesBySourceIDSubscriptionsBySubID": undefined;
  "getV1Events": { "project_id": string; "status"?: "waiting" | "received" | "timed_out" | "canceled"; "workflow_run_id"?: string; "source_type"?: "workflow_step" | "job_run"; "limit"?: number; "cursor"?: string };
  "deleteV1EventsByEventKey": undefined;
  "getV1EventsByEventKey": undefined;
  "postV1EventsByEventKeySend": undefined;
  "getV1EventsByEventKeyStream": undefined;
  "postV1EventsDispatch": undefined;
  "postV1EventsPrefixByPrefixSend": undefined;
  "postV1EventsPurge": undefined;
  "getV1EventsStats": undefined;
  "getV1JobGroups": { "project_id": string };
  "postV1JobGroups": undefined;
  "deleteV1JobGroupsByGroupID": undefined;
  "getV1JobGroupsByGroupID": undefined;
  "patchV1JobGroupsByGroupID": undefined;
  "getV1JobGroupsByGroupIDJobs": undefined;
  "postV1JobGroupsByGroupIDPauseAll": undefined;
  "postV1JobGroupsByGroupIDResumeAll": undefined;
  "getV1JobGroupsByGroupIDStats": undefined;
  "getV1Jobs": { "project_id": string; "tag_key"?: string; "tag_value"?: string };
  "postV1Jobs": undefined;
  "deleteV1JobsByJobID": undefined;
  "getV1JobsByJobID": undefined;
  "patchV1JobsByJobID": undefined;
  "postV1JobsByJobIDClone": undefined;
  "getV1JobsByJobIDDependencies": undefined;
  "postV1JobsByJobIDDependencies": undefined;
  "deleteV1JobsByJobIDDependenciesByDepID": undefined;
  "getV1JobsByJobIDHealth": { "window"?: string };
  "postV1JobsByJobIDTrigger": undefined;
  "postV1JobsByJobIDTriggerBulk": undefined;
  "getV1JobsByJobIDVersions": undefined;
  "getV1JobsByJobIDVersionsByVersionID": undefined;
  "postV1JobsBatch": undefined;
  "postV1JobsBatchDisable": undefined;
  "postV1JobsBatchEnable": undefined;
  "getV1LogDrains": { "project_id": string };
  "postV1LogDrains": undefined;
  "deleteV1LogDrainsByDrainID": { "project_id": string };
  "getV1LogDrainsByDrainID": { "project_id": string };
  "patchV1LogDrainsByDrainID": { "project_id": string };
  "getV1Members": undefined;
  "postV1Members": undefined;
  "deleteV1MembersByUserID": undefined;
  "postV1MembersBulk": undefined;
  "getV1NotificationChannels": undefined;
  "postV1NotificationChannels": undefined;
  "deleteV1NotificationChannelsByChannelID": undefined;
  "getV1NotificationChannelsByChannelID": undefined;
  "patchV1NotificationChannelsByChannelID": undefined;
  "getV1NotificationDeliveries": { "limit"?: number; "cursor"?: string };
  "getV1ProjectsByProjectIDSettings": undefined;
  "putV1ProjectsByProjectIDSettings": undefined;
  "getV1Regions": undefined;
  "getV1ResourcePolicies": { "project_id": string; "user_id"?: string; "limit"?: number; "cursor"?: string };
  "postV1ResourcePolicies": undefined;
  "deleteV1ResourcePoliciesByPolicyID": undefined;
  "getV1Roles": undefined;
  "postV1Roles": undefined;
  "deleteV1RolesByRoleID": undefined;
  "getV1RolesByRoleID": { "include_lineage"?: boolean };
  "patchV1RolesByRoleID": undefined;
  "getV1Runs": { "project_id": string; "status"?: "delayed" | "queued" | "dequeued" | "executing" | "waiting" | "completed" | "failed" | "timed_out" | "crashed" | "system_failed" | "canceled" | "expired" | "dead_letter"; "metadata_key"?: string; "metadata_value"?: string; "limit"?: number; "cursor"?: string; "triggered_by"?: string; "batch_id"?: string; "payload_contains"?: string };
  "deleteV1RunsByRunID": undefined;
  "getV1RunsByRunID": undefined;
  "getV1RunsByRunIDCheckpoints": undefined;
  "getV1RunsByRunIDChildren": undefined;
  "postV1RunsByRunIDDebug": undefined;
  "getV1RunsByRunIDDebugBundle": undefined;
  "getV1RunsByRunIDDependencyStatus": undefined;
  "postV1RunsByRunIDDlqReplay": undefined;
  "getV1RunsByRunIDEvents": { "level"?: string; "type"?: string };
  "deleteV1RunsByRunIDIdempotencyKey": undefined;
  "getV1RunsByRunIDLineage": undefined;
  "getV1RunsByRunIDOutputs": undefined;
  "postV1RunsByRunIDPause": undefined;
  "postV1RunsByRunIDReplay": undefined;
  "postV1RunsByRunIDReschedule": undefined;
  "getV1RunsByRunIDResources": { "from"?: string; "to"?: string; "limit"?: number };
  "postV1RunsByRunIDRestart": undefined;
  "postV1RunsByRunIDResume": undefined;
  "getV1RunsByRunIDState": undefined;
  "getV1RunsByRunIDStream": undefined;
  "getV1RunsByRunIDStreamChunks": undefined;
  "getV1RunsByRunIDToolCalls": undefined;
  "getV1RunsByRunIDUsage": undefined;
  "postV1RunsBulkCancel": undefined;
  "postV1RunsBulkCancelAll": { "project_id": string };
  "postV1RunsBulkDlqReplay": undefined;
  "postV1RunsBulkReplay": undefined;
  "getV1RunsDlq": { "project_id": string };
  "getV1Secrets": { "project_id": string; "job_id"?: string; "environment"?: string };
  "postV1Secrets": undefined;
  "deleteV1SecretsBySecretID": undefined;
  "postV1SeedRoles": undefined;
  "getV1Stats": undefined;
  "getV1TagPolicies": { "project_id": string; "user_id"?: string; "resource_type"?: string; "limit"?: number; "cursor"?: string };
  "postV1TagPolicies": undefined;
  "deleteV1TagPoliciesByPolicyID": undefined;
  "getV1WebhookDeliveries": { "project_id": string; "status"?: string; "limit"?: number };
  "postV1WebhookDeliveriesByDeliveryIDRetry": undefined;
  "getV1WebhooksDeliveries": { "project_id": string; "status"?: "pending" | "delivered" | "failed" | "dead"; "limit"?: number; "cursor"?: string };
  "getV1WebhooksDeliveriesById": undefined;
  "postV1WebhooksDeliveriesByIdReplay": undefined;
  "postV1WebhooksDeliveriesByIdRetry": undefined;
  "getV1WebhooksSubscriptions": { "project_id": string };
  "postV1WebhooksSubscriptions": undefined;
  "deleteV1WebhooksSubscriptionsById": undefined;
  "postV1WebhooksTest": undefined;
  "getV1WorkflowPoliciesByProjectID": undefined;
  "putV1WorkflowPoliciesByProjectID": undefined;
  "getV1WorkflowRuns": { "project_id": string; "status"?: "pending" | "running" | "paused" | "completed" | "failed" | "timed_out" | "canceled"; "limit"?: number };
  "deleteV1WorkflowRunsByWorkflowRunID": undefined;
  "getV1WorkflowRunsByWorkflowRunID": undefined;
  "getV1WorkflowRunsByWorkflowRunIDExplain": { "step_ref"?: string; "decision_type"?: "scheduler" | "concurrency" | "resource" | "condition" };
  "getV1WorkflowRunsByWorkflowRunIDGraph": undefined;
  "getV1WorkflowRunsByWorkflowRunIDLabels": undefined;
  "postV1WorkflowRunsByWorkflowRunIDPause": undefined;
  "postV1WorkflowRunsByWorkflowRunIDResume": undefined;
  "postV1WorkflowRunsByWorkflowRunIDRetry": undefined;
  "getV1WorkflowRunsByWorkflowRunIDSteps": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefApprove": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefForceComplete": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefReplaySubtree": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefRetry": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefSkip": undefined;
  "getV1WorkflowRunsByWorkflowRunIDTimeline": undefined;
  "postV1WorkflowRunsBulkCancel": undefined;
  "postV1WorkflowRunsBulkReplay": undefined;
  "getV1Workflows": { "project_id": string };
  "postV1Workflows": undefined;
  "deleteV1WorkflowsByWorkflowID": undefined;
  "getV1WorkflowsByWorkflowID": undefined;
  "patchV1WorkflowsByWorkflowID": undefined;
  "getV1WorkflowsByWorkflowIDActiveVersions": undefined;
  "postV1WorkflowsByWorkflowIDClone": undefined;
  "postV1WorkflowsByWorkflowIDDryRun": undefined;
  "getV1WorkflowsByWorkflowIDGraph": { "format"?: "json" | "dot" };
  "postV1WorkflowsByWorkflowIDPlan": undefined;
  "getV1WorkflowsByWorkflowIDRuns": undefined;
  "postV1WorkflowsByWorkflowIDSimulate": undefined;
  "postV1WorkflowsByWorkflowIDTrigger": undefined;
  "getV1WorkflowsByWorkflowIDVersions": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByFromVersionIDDiffByToVersionID": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionID": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDImpact": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDSteps": undefined;
};

export type OperationHeaderParamsById = {
  "getHealth": undefined;
  "getHealthReady": undefined;
  "getMetrics": undefined;
  "postSdkV1RunsByRunIDAnnotate": undefined;
  "postSdkV1RunsByRunIDCheckpoint": undefined;
  "postSdkV1RunsByRunIDComplete": undefined;
  "postSdkV1RunsByRunIDContinue": undefined;
  "postSdkV1RunsByRunIDFail": undefined;
  "postSdkV1RunsByRunIDHeartbeat": undefined;
  "postSdkV1RunsByRunIDIteration": undefined;
  "postSdkV1RunsByRunIDLog": undefined;
  "getSdkV1RunsByRunIDMemory": undefined;
  "deleteSdkV1RunsByRunIDMemoryByKey": undefined;
  "getSdkV1RunsByRunIDMemoryByKey": undefined;
  "postSdkV1RunsByRunIDMemoryByKey": undefined;
  "postSdkV1RunsByRunIDOutput": undefined;
  "getSdkV1RunsByRunIDPayload": undefined;
  "postSdkV1RunsByRunIDProgress": undefined;
  "postSdkV1RunsByRunIDResourceSnapshot": undefined;
  "postSdkV1RunsByRunIDResources": undefined;
  "postSdkV1RunsByRunIDSpawn": undefined;
  "getSdkV1RunsByRunIDState": undefined;
  "postSdkV1RunsByRunIDState": undefined;
  "deleteSdkV1RunsByRunIDStateByKey": undefined;
  "getSdkV1RunsByRunIDStateByKey": undefined;
  "postSdkV1RunsByRunIDStream": undefined;
  "postSdkV1RunsByRunIDToolCall": undefined;
  "postSdkV1RunsByRunIDUsage": undefined;
  "postSdkV1RunsByRunIDWaitForEvent": undefined;
  "getV1AnalyticsApprovals": undefined;
  "getV1AnalyticsCompute": undefined;
  "getV1AnalyticsCostInsights": undefined;
  "getV1AnalyticsCosts": undefined;
  "getV1AnalyticsCostsTop": undefined;
  "getV1AnalyticsCostsTrends": undefined;
  "getV1AnalyticsPerformance": undefined;
  "getV1ApiKeys": undefined;
  "postV1ApiKeys": undefined;
  "deleteV1ApiKeysByKeyID": undefined;
  "postV1ApiKeysByKeyIDRotate": undefined;
  "getV1AuditEvents": undefined;
  "getV1AuditEventsExport": undefined;
  "getV1BatchOperations": undefined;
  "getV1BatchOperationsByBatchID": undefined;
  "getV1Deployments": undefined;
  "postV1Deployments": undefined;
  "postV1DeploymentsByDeploymentIDFinalize": undefined;
  "postV1DeploymentsByDeploymentIDPromote": undefined;
  "postV1DeploymentsByDeploymentIDRollback": undefined;
  "getV1Environments": undefined;
  "postV1Environments": undefined;
  "deleteV1EnvironmentsByEnvID": undefined;
  "getV1EnvironmentsByEnvID": undefined;
  "patchV1EnvironmentsByEnvID": undefined;
  "getV1EnvironmentsByEnvIDVariables": undefined;
  "getV1EventSources": undefined;
  "postV1EventSources": undefined;
  "deleteV1EventSourcesBySourceID": undefined;
  "getV1EventSourcesBySourceID": undefined;
  "patchV1EventSourcesBySourceID": undefined;
  "postV1EventSourcesBySourceIDSubscribe": undefined;
  "getV1EventSourcesBySourceIDSubscriptions": undefined;
  "deleteV1EventSourcesBySourceIDSubscriptionsBySubID": undefined;
  "getV1Events": undefined;
  "deleteV1EventsByEventKey": undefined;
  "getV1EventsByEventKey": undefined;
  "postV1EventsByEventKeySend": undefined;
  "getV1EventsByEventKeyStream": undefined;
  "postV1EventsDispatch": undefined;
  "postV1EventsPrefixByPrefixSend": undefined;
  "postV1EventsPurge": undefined;
  "getV1EventsStats": undefined;
  "getV1JobGroups": undefined;
  "postV1JobGroups": undefined;
  "deleteV1JobGroupsByGroupID": undefined;
  "getV1JobGroupsByGroupID": undefined;
  "patchV1JobGroupsByGroupID": undefined;
  "getV1JobGroupsByGroupIDJobs": undefined;
  "postV1JobGroupsByGroupIDPauseAll": undefined;
  "postV1JobGroupsByGroupIDResumeAll": undefined;
  "getV1JobGroupsByGroupIDStats": undefined;
  "getV1Jobs": undefined;
  "postV1Jobs": undefined;
  "deleteV1JobsByJobID": undefined;
  "getV1JobsByJobID": undefined;
  "patchV1JobsByJobID": undefined;
  "postV1JobsByJobIDClone": undefined;
  "getV1JobsByJobIDDependencies": undefined;
  "postV1JobsByJobIDDependencies": undefined;
  "deleteV1JobsByJobIDDependenciesByDepID": undefined;
  "getV1JobsByJobIDHealth": undefined;
  "postV1JobsByJobIDTrigger": undefined;
  "postV1JobsByJobIDTriggerBulk": undefined;
  "getV1JobsByJobIDVersions": undefined;
  "getV1JobsByJobIDVersionsByVersionID": undefined;
  "postV1JobsBatch": undefined;
  "postV1JobsBatchDisable": undefined;
  "postV1JobsBatchEnable": undefined;
  "getV1LogDrains": undefined;
  "postV1LogDrains": undefined;
  "deleteV1LogDrainsByDrainID": undefined;
  "getV1LogDrainsByDrainID": undefined;
  "patchV1LogDrainsByDrainID": undefined;
  "getV1Members": undefined;
  "postV1Members": undefined;
  "deleteV1MembersByUserID": undefined;
  "postV1MembersBulk": undefined;
  "getV1NotificationChannels": undefined;
  "postV1NotificationChannels": undefined;
  "deleteV1NotificationChannelsByChannelID": undefined;
  "getV1NotificationChannelsByChannelID": undefined;
  "patchV1NotificationChannelsByChannelID": undefined;
  "getV1NotificationDeliveries": undefined;
  "getV1ProjectsByProjectIDSettings": undefined;
  "putV1ProjectsByProjectIDSettings": undefined;
  "getV1Regions": undefined;
  "getV1ResourcePolicies": undefined;
  "postV1ResourcePolicies": undefined;
  "deleteV1ResourcePoliciesByPolicyID": undefined;
  "getV1Roles": undefined;
  "postV1Roles": undefined;
  "deleteV1RolesByRoleID": undefined;
  "getV1RolesByRoleID": undefined;
  "patchV1RolesByRoleID": undefined;
  "getV1Runs": undefined;
  "deleteV1RunsByRunID": undefined;
  "getV1RunsByRunID": undefined;
  "getV1RunsByRunIDCheckpoints": undefined;
  "getV1RunsByRunIDChildren": undefined;
  "postV1RunsByRunIDDebug": undefined;
  "getV1RunsByRunIDDebugBundle": undefined;
  "getV1RunsByRunIDDependencyStatus": undefined;
  "postV1RunsByRunIDDlqReplay": undefined;
  "getV1RunsByRunIDEvents": undefined;
  "deleteV1RunsByRunIDIdempotencyKey": undefined;
  "getV1RunsByRunIDLineage": undefined;
  "getV1RunsByRunIDOutputs": undefined;
  "postV1RunsByRunIDPause": undefined;
  "postV1RunsByRunIDReplay": undefined;
  "postV1RunsByRunIDReschedule": undefined;
  "getV1RunsByRunIDResources": undefined;
  "postV1RunsByRunIDRestart": undefined;
  "postV1RunsByRunIDResume": undefined;
  "getV1RunsByRunIDState": undefined;
  "getV1RunsByRunIDStream": undefined;
  "getV1RunsByRunIDStreamChunks": undefined;
  "getV1RunsByRunIDToolCalls": undefined;
  "getV1RunsByRunIDUsage": undefined;
  "postV1RunsBulkCancel": undefined;
  "postV1RunsBulkCancelAll": undefined;
  "postV1RunsBulkDlqReplay": undefined;
  "postV1RunsBulkReplay": undefined;
  "getV1RunsDlq": undefined;
  "getV1Secrets": undefined;
  "postV1Secrets": undefined;
  "deleteV1SecretsBySecretID": undefined;
  "postV1SeedRoles": undefined;
  "getV1Stats": undefined;
  "getV1TagPolicies": undefined;
  "postV1TagPolicies": undefined;
  "deleteV1TagPoliciesByPolicyID": undefined;
  "getV1WebhookDeliveries": undefined;
  "postV1WebhookDeliveriesByDeliveryIDRetry": undefined;
  "getV1WebhooksDeliveries": undefined;
  "getV1WebhooksDeliveriesById": undefined;
  "postV1WebhooksDeliveriesByIdReplay": undefined;
  "postV1WebhooksDeliveriesByIdRetry": undefined;
  "getV1WebhooksSubscriptions": undefined;
  "postV1WebhooksSubscriptions": undefined;
  "deleteV1WebhooksSubscriptionsById": undefined;
  "postV1WebhooksTest": undefined;
  "getV1WorkflowPoliciesByProjectID": undefined;
  "putV1WorkflowPoliciesByProjectID": undefined;
  "getV1WorkflowRuns": undefined;
  "deleteV1WorkflowRunsByWorkflowRunID": undefined;
  "getV1WorkflowRunsByWorkflowRunID": undefined;
  "getV1WorkflowRunsByWorkflowRunIDExplain": undefined;
  "getV1WorkflowRunsByWorkflowRunIDGraph": undefined;
  "getV1WorkflowRunsByWorkflowRunIDLabels": undefined;
  "postV1WorkflowRunsByWorkflowRunIDPause": undefined;
  "postV1WorkflowRunsByWorkflowRunIDResume": undefined;
  "postV1WorkflowRunsByWorkflowRunIDRetry": undefined;
  "getV1WorkflowRunsByWorkflowRunIDSteps": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefApprove": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefForceComplete": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefReplaySubtree": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefRetry": undefined;
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefSkip": undefined;
  "getV1WorkflowRunsByWorkflowRunIDTimeline": undefined;
  "postV1WorkflowRunsBulkCancel": undefined;
  "postV1WorkflowRunsBulkReplay": undefined;
  "getV1Workflows": undefined;
  "postV1Workflows": undefined;
  "deleteV1WorkflowsByWorkflowID": undefined;
  "getV1WorkflowsByWorkflowID": undefined;
  "patchV1WorkflowsByWorkflowID": undefined;
  "getV1WorkflowsByWorkflowIDActiveVersions": undefined;
  "postV1WorkflowsByWorkflowIDClone": undefined;
  "postV1WorkflowsByWorkflowIDDryRun": undefined;
  "getV1WorkflowsByWorkflowIDGraph": undefined;
  "postV1WorkflowsByWorkflowIDPlan": undefined;
  "getV1WorkflowsByWorkflowIDRuns": undefined;
  "postV1WorkflowsByWorkflowIDSimulate": undefined;
  "postV1WorkflowsByWorkflowIDTrigger": undefined;
  "getV1WorkflowsByWorkflowIDVersions": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByFromVersionIDDiffByToVersionID": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionID": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDImpact": undefined;
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDSteps": undefined;
};

export type OperationPathParams<TOperationId extends GeneratedOperationId> =
  OperationPathParamsById[TOperationId];

export type OperationQueryParams<TOperationId extends GeneratedOperationId> =
  OperationQueryParamsById[TOperationId];

export type OperationHeaderParams<TOperationId extends GeneratedOperationId> =
  OperationHeaderParamsById[TOperationId];

export type OperationInputById = {
  readonly [K in GeneratedOperationId]: {
    readonly pathParams: OperationPathParamsById[K];
    readonly query: OperationQueryParamsById[K];
    readonly headers: OperationHeaderParamsById[K];
    readonly body: OperationRequestBodyById[K];
    readonly response: OperationResponseBodyById[K];
  };
};

export type OperationInput<TOperationId extends GeneratedOperationId> =
  OperationInputById[TOperationId];

export const generatedOperationMetadataById = {
  "getHealth": { functionName: "listHealth", domainName: "health", domainMethodName: "list", pathParamNames: [], summary: "Liveness check" },
  "getHealthReady": { functionName: "getReady", domainName: "health", domainMethodName: "getReady", pathParamNames: [], summary: "Readiness check" },
  "getMetrics": { functionName: "listMetrics", domainName: "health", domainMethodName: "listMetrics", pathParamNames: [], summary: "Prometheus metrics" },
  "postSdkV1RunsByRunIDAnnotate": { functionName: "annotateRun", domainName: "sdk", domainMethodName: "annotateRun", pathParamNames: ["runID"], summary: "Attach annotations" },
  "postSdkV1RunsByRunIDCheckpoint": { functionName: "checkpointRun", domainName: "sdk", domainMethodName: "checkpointRun", pathParamNames: ["runID"], summary: "Save a checkpoint" },
  "postSdkV1RunsByRunIDComplete": { functionName: "completeRun", domainName: "sdk", domainMethodName: "completeRun", pathParamNames: ["runID"], summary: "Mark run completed" },
  "postSdkV1RunsByRunIDContinue": { functionName: "continueRun", domainName: "sdk", domainMethodName: "continueRun", pathParamNames: ["runID"], summary: "Create a continuation run" },
  "postSdkV1RunsByRunIDFail": { functionName: "failRun", domainName: "sdk", domainMethodName: "failRun", pathParamNames: ["runID"], summary: "Mark run failed" },
  "postSdkV1RunsByRunIDHeartbeat": { functionName: "heartbeatRun", domainName: "sdk", domainMethodName: "heartbeatRun", pathParamNames: ["runID"], summary: "Send heartbeat" },
  "postSdkV1RunsByRunIDIteration": { functionName: "iterationRun", domainName: "sdk", domainMethodName: "iterationRun", pathParamNames: ["runID"], summary: "Record an agent iteration" },
  "postSdkV1RunsByRunIDLog": { functionName: "logRun", domainName: "sdk", domainMethodName: "logRun", pathParamNames: ["runID"], summary: "Log an event" },
  "getSdkV1RunsByRunIDMemory": { functionName: "getMemory", domainName: "sdk", domainMethodName: "getMemory", pathParamNames: ["runID"], summary: "List all job memory keys" },
  "deleteSdkV1RunsByRunIDMemoryByKey": { functionName: "deleteMemory", domainName: "sdk", domainMethodName: "deleteMemory", pathParamNames: ["runID","key"], summary: "Delete job memory key" },
  "getSdkV1RunsByRunIDMemoryByKey": { functionName: "getMemoryByRunIDAndKey", domainName: "sdk", domainMethodName: "getMemoryByRunIdAndKey", pathParamNames: ["runID","key"], summary: "Get job memory key" },
  "postSdkV1RunsByRunIDMemoryByKey": { functionName: "memoryRun", domainName: "sdk", domainMethodName: "memoryRun", pathParamNames: ["runID","key"], summary: "Set job memory key" },
  "postSdkV1RunsByRunIDOutput": { functionName: "outputRun", domainName: "sdk", domainMethodName: "outputRun", pathParamNames: ["runID"], summary: "Upsert structured output" },
  "getSdkV1RunsByRunIDPayload": { functionName: "getPayload", domainName: "sdk", domainMethodName: "getPayload", pathParamNames: ["runID"], summary: "Get run payload" },
  "postSdkV1RunsByRunIDProgress": { functionName: "progressRun", domainName: "sdk", domainMethodName: "progressRun", pathParamNames: ["runID"], summary: "Report progress" },
  "postSdkV1RunsByRunIDResourceSnapshot": { functionName: "resourceSnapshotRun", domainName: "sdk", domainMethodName: "resourceSnapshotRun", pathParamNames: ["runID"], summary: "Report resource snapshot (CPU, memory, network)" },
  "postSdkV1RunsByRunIDResources": { functionName: "resourcesRun", domainName: "sdk", domainMethodName: "resourcesRun", pathParamNames: ["runID"], summary: "Report in-container resource usage" },
  "postSdkV1RunsByRunIDSpawn": { functionName: "spawnRun", domainName: "sdk", domainMethodName: "spawnRun", pathParamNames: ["runID"], summary: "Spawn a child job run" },
  "getSdkV1RunsByRunIDState": { functionName: "getStateByRunID", domainName: "sdk", domainMethodName: "getStateByRunId", pathParamNames: ["runID"], summary: "List all run state keys" },
  "postSdkV1RunsByRunIDState": { functionName: "stateRun", domainName: "sdk", domainMethodName: "stateRun", pathParamNames: ["runID"], summary: "Set run state key" },
  "deleteSdkV1RunsByRunIDStateByKey": { functionName: "deleteState", domainName: "sdk", domainMethodName: "deleteState", pathParamNames: ["runID","key"], summary: "Delete run state key" },
  "getSdkV1RunsByRunIDStateByKey": { functionName: "getStateByRunIDAndKey", domainName: "sdk", domainMethodName: "getStateByRunIdAndKey", pathParamNames: ["runID","key"], summary: "Get run state key" },
  "postSdkV1RunsByRunIDStream": { functionName: "streamRun", domainName: "sdk", domainMethodName: "streamRun", pathParamNames: ["runID"], summary: "Push LLM stream chunk" },
  "postSdkV1RunsByRunIDToolCall": { functionName: "toolCallRun", domainName: "sdk", domainMethodName: "toolCallRun", pathParamNames: ["runID"], summary: "Record a tool call" },
  "postSdkV1RunsByRunIDUsage": { functionName: "usageRun", domainName: "sdk", domainMethodName: "usageRun", pathParamNames: ["runID"], summary: "Report AI model usage" },
  "postSdkV1RunsByRunIDWaitForEvent": { functionName: "waitForEventRun", domainName: "sdk", domainMethodName: "waitForEventRun", pathParamNames: ["runID"], summary: "Pause a run to wait for an external event" },
  "getV1AnalyticsApprovals": { functionName: "listApprovals", domainName: "analytics", domainMethodName: "listApprovals", pathParamNames: [], summary: "Approval analytics" },
  "getV1AnalyticsCompute": { functionName: "getCompute", domainName: "analytics", domainMethodName: "getCompute", pathParamNames: [], summary: "Compute cost analytics" },
  "getV1AnalyticsCostInsights": { functionName: "listCostInsights", domainName: "analytics", domainMethodName: "listCostInsights", pathParamNames: [], summary: "Cost optimization insights" },
  "getV1AnalyticsCosts": { functionName: "listCosts", domainName: "analytics", domainMethodName: "listCosts", pathParamNames: [], summary: "Cost analytics" },
  "getV1AnalyticsCostsTop": { functionName: "getTop", domainName: "analytics", domainMethodName: "getTop", pathParamNames: [], summary: "Top cost items" },
  "getV1AnalyticsCostsTrends": { functionName: "listTrends", domainName: "analytics", domainMethodName: "listTrends", pathParamNames: [], summary: "Cost trends over time" },
  "getV1AnalyticsPerformance": { functionName: "getPerformance", domainName: "analytics", domainMethodName: "getPerformance", pathParamNames: [], summary: "Performance analytics" },
  "getV1ApiKeys": { functionName: "listApiKeys", domainName: "apiKeys", domainMethodName: "list", pathParamNames: [], summary: "List API keys" },
  "postV1ApiKeys": { functionName: "createApiKey", domainName: "apiKeys", domainMethodName: "create", pathParamNames: [], summary: "Create an API key" },
  "deleteV1ApiKeysByKeyID": { functionName: "deleteApiKey", domainName: "apiKeys", domainMethodName: "delete", pathParamNames: ["keyID"], summary: "Revoke an API key" },
  "postV1ApiKeysByKeyIDRotate": { functionName: "rotateApiKey", domainName: "apiKeys", domainMethodName: "rotate", pathParamNames: ["keyID"], summary: "Rotate an API key with optional grace period" },
  "getV1AuditEvents": { functionName: "listAuditEvents", domainName: "rbac", domainMethodName: "listAuditEvents", pathParamNames: [], summary: "List audit events" },
  "getV1AuditEventsExport": { functionName: "getExport", domainName: "rbac", domainMethodName: "getExport", pathParamNames: [], summary: "Export audit events in CSV, JSON, or NDJSON format" },
  "getV1BatchOperations": { functionName: "listBatchOperations", domainName: "batchOperations", domainMethodName: "list", pathParamNames: [], summary: "List batch operations" },
  "getV1BatchOperationsByBatchID": { functionName: "getBatchOperation", domainName: "batchOperations", domainMethodName: "get", pathParamNames: ["batchID"], summary: "Get a batch operation" },
  "getV1Deployments": { functionName: "listDeployments", domainName: "deployments", domainMethodName: "list", pathParamNames: [], summary: "List deployment versions" },
  "postV1Deployments": { functionName: "createDeployment", domainName: "deployments", domainMethodName: "create", pathParamNames: [], summary: "Create deployment version" },
  "postV1DeploymentsByDeploymentIDFinalize": { functionName: "finalizeDeployment", domainName: "deployments", domainMethodName: "finalize", pathParamNames: ["deploymentID"], summary: "Finalize deployment version" },
  "postV1DeploymentsByDeploymentIDPromote": { functionName: "promoteDeployment", domainName: "deployments", domainMethodName: "promote", pathParamNames: ["deploymentID"], summary: "Promote deployment version" },
  "postV1DeploymentsByDeploymentIDRollback": { functionName: "rollbackDeployment", domainName: "deployments", domainMethodName: "rollback", pathParamNames: ["deploymentID"], summary: "Rollback deployment to selected version" },
  "getV1Environments": { functionName: "listEnvironments", domainName: "environments", domainMethodName: "list", pathParamNames: [], summary: "List environments" },
  "postV1Environments": { functionName: "createEnvironment", domainName: "environments", domainMethodName: "create", pathParamNames: [], summary: "Create an environment" },
  "deleteV1EnvironmentsByEnvID": { functionName: "deleteEnvironment", domainName: "environments", domainMethodName: "delete", pathParamNames: ["envID"], summary: "Delete an environment" },
  "getV1EnvironmentsByEnvID": { functionName: "getEnvironment", domainName: "environments", domainMethodName: "get", pathParamNames: ["envID"], summary: "Get an environment" },
  "patchV1EnvironmentsByEnvID": { functionName: "updateEnvironment", domainName: "environments", domainMethodName: "update", pathParamNames: ["envID"], summary: "Update an environment" },
  "getV1EnvironmentsByEnvIDVariables": { functionName: "listVariables", domainName: "environments", domainMethodName: "listVariables", pathParamNames: ["envID"], summary: "Get resolved variables" },
  "getV1EventSources": { functionName: "listEventSources", domainName: "eventSources", domainMethodName: "list", pathParamNames: [], summary: "List event sources" },
  "postV1EventSources": { functionName: "createEventSource", domainName: "eventSources", domainMethodName: "create", pathParamNames: [], summary: "Create an event source" },
  "deleteV1EventSourcesBySourceID": { functionName: "deleteEventSource", domainName: "eventSources", domainMethodName: "delete", pathParamNames: ["sourceID"], summary: "Delete an event source" },
  "getV1EventSourcesBySourceID": { functionName: "getEventSource", domainName: "eventSources", domainMethodName: "get", pathParamNames: ["sourceID"], summary: "Get an event source" },
  "patchV1EventSourcesBySourceID": { functionName: "updateEventSource", domainName: "eventSources", domainMethodName: "update", pathParamNames: ["sourceID"], summary: "Update an event source" },
  "postV1EventSourcesBySourceIDSubscribe": { functionName: "subscribeEventSource", domainName: "eventSources", domainMethodName: "subscribe", pathParamNames: ["sourceID"], summary: "Subscribe to an event source" },
  "getV1EventSourcesBySourceIDSubscriptions": { functionName: "listSubscriptionsBySourceID", domainName: "eventSources", domainMethodName: "listSubscriptionsBySourceId", pathParamNames: ["sourceID"], summary: "List subscriptions for an event source" },
  "deleteV1EventSourcesBySourceIDSubscriptionsBySubID": { functionName: "deleteSubscriptionBySourceIDAndSubID", domainName: "eventSources", domainMethodName: "deleteSubscriptionBySourceIdAndSubId", pathParamNames: ["sourceID","subID"], summary: "Delete a subscription" },
  "getV1Events": { functionName: "listEvents", domainName: "eventTriggers", domainMethodName: "listEvents", pathParamNames: [], summary: "List event triggers for a project" },
  "deleteV1EventsByEventKey": { functionName: "deleteEvent", domainName: "eventTriggers", domainMethodName: "deleteEvent", pathParamNames: ["eventKey"], summary: "Cancel a waiting event trigger" },
  "getV1EventsByEventKey": { functionName: "getEvent", domainName: "eventTriggers", domainMethodName: "getEvent", pathParamNames: ["eventKey"], summary: "Get event trigger by key" },
  "postV1EventsByEventKeySend": { functionName: "sendEvent", domainName: "eventTriggers", domainMethodName: "sendEvent", pathParamNames: ["eventKey"], summary: "Send an event to a waiting trigger" },
  "getV1EventsByEventKeyStream": { functionName: "getStream", domainName: "eventTriggers", domainMethodName: "getStream", pathParamNames: ["eventKey"], summary: "Stream event trigger status updates via SSE" },
  "postV1EventsDispatch": { functionName: "dispatchEvent", domainName: "eventSources", domainMethodName: "dispatchEvent", pathParamNames: [], summary: "Dispatch an event" },
  "postV1EventsPrefixByPrefixSend": { functionName: "sendPrefix", domainName: "eventTriggers", domainMethodName: "sendPrefix", pathParamNames: ["prefix"], summary: "Send an event to all waiting triggers matching a prefix" },
  "postV1EventsPurge": { functionName: "purgeEvent", domainName: "eventTriggers", domainMethodName: "purgeEvent", pathParamNames: [], summary: "Purge terminal event triggers" },
  "getV1EventsStats": { functionName: "getStat", domainName: "eventTriggers", domainMethodName: "getStat", pathParamNames: [], summary: "Get event trigger statistics" },
  "getV1JobGroups": { functionName: "listJobGroups", domainName: "jobGroups", domainMethodName: "list", pathParamNames: [], summary: "List job groups" },
  "postV1JobGroups": { functionName: "createJobGroup", domainName: "jobGroups", domainMethodName: "create", pathParamNames: [], summary: "Create a job group" },
  "deleteV1JobGroupsByGroupID": { functionName: "deleteJobGroup", domainName: "jobGroups", domainMethodName: "delete", pathParamNames: ["groupID"], summary: "Delete a job group" },
  "getV1JobGroupsByGroupID": { functionName: "getJobGroup", domainName: "jobGroups", domainMethodName: "get", pathParamNames: ["groupID"], summary: "Get a job group" },
  "patchV1JobGroupsByGroupID": { functionName: "updateJobGroup", domainName: "jobGroups", domainMethodName: "update", pathParamNames: ["groupID"], summary: "Update a job group" },
  "getV1JobGroupsByGroupIDJobs": { functionName: "listJobsByGroupID", domainName: "jobGroups", domainMethodName: "listJobsByGroupId", pathParamNames: ["groupID"], summary: "List jobs in a group" },
  "postV1JobGroupsByGroupIDPauseAll": { functionName: "pauseAllJobGroup", domainName: "jobGroups", domainMethodName: "pauseAll", pathParamNames: ["groupID"], summary: "Pause all jobs in a group" },
  "postV1JobGroupsByGroupIDResumeAll": { functionName: "resumeAllJobGroup", domainName: "jobGroups", domainMethodName: "resumeAll", pathParamNames: ["groupID"], summary: "Resume all jobs in a group" },
  "getV1JobGroupsByGroupIDStats": { functionName: "getStatByGroupID", domainName: "jobGroups", domainMethodName: "getStatByGroupId", pathParamNames: ["groupID"], summary: "Get aggregate run stats for a job group" },
  "getV1Jobs": { functionName: "listJobs", domainName: "jobs", domainMethodName: "list", pathParamNames: [], summary: "List jobs" },
  "postV1Jobs": { functionName: "createJob", domainName: "jobs", domainMethodName: "create", pathParamNames: [], summary: "Create a job" },
  "deleteV1JobsByJobID": { functionName: "deleteJob", domainName: "jobs", domainMethodName: "delete", pathParamNames: ["jobID"], summary: "Delete a job" },
  "getV1JobsByJobID": { functionName: "getJob", domainName: "jobs", domainMethodName: "get", pathParamNames: ["jobID"], summary: "Get a job" },
  "patchV1JobsByJobID": { functionName: "updateJob", domainName: "jobs", domainMethodName: "update", pathParamNames: ["jobID"], summary: "Update a job" },
  "postV1JobsByJobIDClone": { functionName: "cloneJob", domainName: "jobs", domainMethodName: "clone", pathParamNames: ["jobID"], summary: "Clone a job" },
  "getV1JobsByJobIDDependencies": { functionName: "listDependencies", domainName: "jobs", domainMethodName: "listDependencies", pathParamNames: ["jobID"], summary: "List job dependencies" },
  "postV1JobsByJobIDDependencies": { functionName: "dependenciesJob", domainName: "jobs", domainMethodName: "dependencies", pathParamNames: ["jobID"], summary: "Create a job dependency" },
  "deleteV1JobsByJobIDDependenciesByDepID": { functionName: "deleteDependency", domainName: "jobs", domainMethodName: "deleteDependency", pathParamNames: ["jobID","depID"], summary: "Delete a job dependency" },
  "getV1JobsByJobIDHealth": { functionName: "getHealth", domainName: "jobs", domainMethodName: "getHealth", pathParamNames: ["jobID"], summary: "Get job health score" },
  "postV1JobsByJobIDTrigger": { functionName: "triggerJob", domainName: "jobs", domainMethodName: "trigger", pathParamNames: ["jobID"], summary: "Trigger a job run" },
  "postV1JobsByJobIDTriggerBulk": { functionName: "bulkTrigger", domainName: "jobs", domainMethodName: "bulkTrigger", pathParamNames: ["jobID"], summary: "Trigger multiple runs" },
  "getV1JobsByJobIDVersions": { functionName: "listVersions", domainName: "jobs", domainMethodName: "listVersions", pathParamNames: ["jobID"], summary: "List job versions" },
  "getV1JobsByJobIDVersionsByVersionID": { functionName: "getVersion", domainName: "jobs", domainMethodName: "getVersion", pathParamNames: ["jobID","versionID"], summary: "Get job version by version ID" },
  "postV1JobsBatch": { functionName: "batchJob", domainName: "jobs", domainMethodName: "batch", pathParamNames: [], summary: "Batch create jobs" },
  "postV1JobsBatchDisable": { functionName: "batchDisableJob", domainName: "jobs", domainMethodName: "batchDisable", pathParamNames: [], summary: "Batch disable jobs" },
  "postV1JobsBatchEnable": { functionName: "batchEnableJob", domainName: "jobs", domainMethodName: "batchEnable", pathParamNames: [], summary: "Batch enable jobs" },
  "getV1LogDrains": { functionName: "listLogDrains", domainName: "logDrains", domainMethodName: "list", pathParamNames: [], summary: "List log drains" },
  "postV1LogDrains": { functionName: "createLogDrain", domainName: "logDrains", domainMethodName: "create", pathParamNames: [], summary: "Create a log drain" },
  "deleteV1LogDrainsByDrainID": { functionName: "deleteLogDrain", domainName: "logDrains", domainMethodName: "delete", pathParamNames: ["drainID"], summary: "Delete a log drain" },
  "getV1LogDrainsByDrainID": { functionName: "getLogDrain", domainName: "logDrains", domainMethodName: "get", pathParamNames: ["drainID"], summary: "Get a log drain" },
  "patchV1LogDrainsByDrainID": { functionName: "updateLogDrain", domainName: "logDrains", domainMethodName: "update", pathParamNames: ["drainID"], summary: "Update a log drain" },
  "getV1Members": { functionName: "listMembers", domainName: "rbac", domainMethodName: "listMembers", pathParamNames: [], summary: "List project members" },
  "postV1Members": { functionName: "createMember", domainName: "rbac", domainMethodName: "createMember", pathParamNames: [], summary: "Assign member role" },
  "deleteV1MembersByUserID": { functionName: "deleteMember", domainName: "rbac", domainMethodName: "deleteMember", pathParamNames: ["userID"], summary: "Remove project member" },
  "postV1MembersBulk": { functionName: "bulkMember", domainName: "rbac", domainMethodName: "bulkMember", pathParamNames: [], summary: "Bulk assign members" },
  "getV1NotificationChannels": { functionName: "listNotificationChannels", domainName: "notificationChannels", domainMethodName: "list", pathParamNames: [], summary: "List notification channels" },
  "postV1NotificationChannels": { functionName: "createNotificationChannel", domainName: "notificationChannels", domainMethodName: "create", pathParamNames: [], summary: "Create a notification channel" },
  "deleteV1NotificationChannelsByChannelID": { functionName: "deleteNotificationChannel", domainName: "notificationChannels", domainMethodName: "delete", pathParamNames: ["channelID"], summary: "Delete a notification channel" },
  "getV1NotificationChannelsByChannelID": { functionName: "getNotificationChannel", domainName: "notificationChannels", domainMethodName: "get", pathParamNames: ["channelID"], summary: "Get a notification channel" },
  "patchV1NotificationChannelsByChannelID": { functionName: "updateNotificationChannel", domainName: "notificationChannels", domainMethodName: "update", pathParamNames: ["channelID"], summary: "Update a notification channel" },
  "getV1NotificationDeliveries": { functionName: "listNotificationDeliveries", domainName: "notificationChannels", domainMethodName: "listNotificationDeliveries", pathParamNames: [], summary: "List notification deliveries" },
  "getV1ProjectsByProjectIDSettings": { functionName: "listSettings", domainName: "projects", domainMethodName: "listSettings", pathParamNames: ["projectID"], summary: "Get project settings" },
  "putV1ProjectsByProjectIDSettings": { functionName: "upsertSetting", domainName: "projects", domainMethodName: "upsertSetting", pathParamNames: ["projectID"], summary: "Update project settings" },
  "getV1Regions": { functionName: "listRegions", domainName: "regions", domainMethodName: "list", pathParamNames: [], summary: "List available regions" },
  "getV1ResourcePolicies": { functionName: "listResourcePolicies", domainName: "rbac", domainMethodName: "listResourcePolicies", pathParamNames: [], summary: "List resource policies" },
  "postV1ResourcePolicies": { functionName: "createResourcePolicy", domainName: "rbac", domainMethodName: "createResourcePolicy", pathParamNames: [], summary: "Create resource policy" },
  "deleteV1ResourcePoliciesByPolicyID": { functionName: "deleteResourcePolicy", domainName: "rbac", domainMethodName: "deleteResourcePolicy", pathParamNames: ["policyID"], summary: "Delete resource policy" },
  "getV1Roles": { functionName: "listRoles", domainName: "rbac", domainMethodName: "listRoles", pathParamNames: [], summary: "List roles for a project" },
  "postV1Roles": { functionName: "createRole", domainName: "rbac", domainMethodName: "createRole", pathParamNames: [], summary: "Create a custom project role" },
  "deleteV1RolesByRoleID": { functionName: "deleteRole", domainName: "rbac", domainMethodName: "deleteRole", pathParamNames: ["roleID"], summary: "Delete role" },
  "getV1RolesByRoleID": { functionName: "getRole", domainName: "rbac", domainMethodName: "getRole", pathParamNames: ["roleID"], summary: "Get role by ID" },
  "patchV1RolesByRoleID": { functionName: "updateRole", domainName: "rbac", domainMethodName: "updateRole", pathParamNames: ["roleID"], summary: "Update role" },
  "getV1Runs": { functionName: "listRuns", domainName: "runs", domainMethodName: "list", pathParamNames: [], summary: "List runs" },
  "deleteV1RunsByRunID": { functionName: "deleteRun", domainName: "runs", domainMethodName: "delete", pathParamNames: ["runID"], summary: "Cancel a run" },
  "getV1RunsByRunID": { functionName: "getRun", domainName: "runs", domainMethodName: "get", pathParamNames: ["runID"], summary: "Get a run" },
  "getV1RunsByRunIDCheckpoints": { functionName: "listCheckpoints", domainName: "runs", domainMethodName: "listCheckpoints", pathParamNames: ["runID"], summary: "List run checkpoints" },
  "getV1RunsByRunIDChildren": { functionName: "getChildren", domainName: "runs", domainMethodName: "getChildren", pathParamNames: ["runID"], summary: "List child runs" },
  "postV1RunsByRunIDDebug": { functionName: "debugRun", domainName: "runs", domainMethodName: "debug", pathParamNames: ["runID"], summary: "Enable/disable debug mode" },
  "getV1RunsByRunIDDebugBundle": { functionName: "getDebugBundle", domainName: "runs", domainMethodName: "getDebugBundle", pathParamNames: ["runID"], summary: "Get debug bundle" },
  "getV1RunsByRunIDDependencyStatus": { functionName: "listDependencyStatus", domainName: "runs", domainMethodName: "listDependencyStatus", pathParamNames: ["runID"], summary: "Get dependency status for a run" },
  "postV1RunsByRunIDDlqReplay": { functionName: "dlqReplayRun", domainName: "runs", domainMethodName: "dlqReplay", pathParamNames: ["runID"], summary: "Replay a dead-lettered run" },
  "getV1RunsByRunIDEvents": { functionName: "listEventsByRunID", domainName: "runs", domainMethodName: "listEventsByRunId", pathParamNames: ["runID"], summary: "List run events" },
  "deleteV1RunsByRunIDIdempotencyKey": { functionName: "deleteIdempotencyKey", domainName: "runs", domainMethodName: "deleteIdempotencyKey", pathParamNames: ["runID"], summary: "Reset idempotency key for a run" },
  "getV1RunsByRunIDLineage": { functionName: "getLineage", domainName: "runs", domainMethodName: "getLineage", pathParamNames: ["runID"], summary: "List run continuation lineage" },
  "getV1RunsByRunIDOutputs": { functionName: "listOutputs", domainName: "runs", domainMethodName: "listOutputs", pathParamNames: ["runID"], summary: "List run structured outputs" },
  "postV1RunsByRunIDPause": { functionName: "pauseRun", domainName: "runs", domainMethodName: "pause", pathParamNames: ["runID"], summary: "Pause a managed run" },
  "postV1RunsByRunIDReplay": { functionName: "replayRun", domainName: "runs", domainMethodName: "replay", pathParamNames: ["runID"], summary: "Replay a failed run" },
  "postV1RunsByRunIDReschedule": { functionName: "rescheduleRun", domainName: "runs", domainMethodName: "reschedule", pathParamNames: ["runID"], summary: "Reschedule a run" },
  "getV1RunsByRunIDResources": { functionName: "listResources", domainName: "runs", domainMethodName: "listResources", pathParamNames: ["runID"], summary: "List resource snapshots for a run" },
  "postV1RunsByRunIDRestart": { functionName: "restartRun", domainName: "runs", domainMethodName: "restart", pathParamNames: ["runID"], summary: "Restart a managed run with optional preset override" },
  "postV1RunsByRunIDResume": { functionName: "resumeRun", domainName: "runs", domainMethodName: "resume", pathParamNames: ["runID"], summary: "Resume a paused run" },
  "getV1RunsByRunIDState": { functionName: "getState", domainName: "runs", domainMethodName: "getState", pathParamNames: ["runID"], summary: "List run state (management API)" },
  "getV1RunsByRunIDStream": { functionName: "getStreamByRunID", domainName: "runs", domainMethodName: "getStreamByRunId", pathParamNames: ["runID"], summary: "SSE event stream" },
  "getV1RunsByRunIDStreamChunks": { functionName: "listChunks", domainName: "runs", domainMethodName: "listChunks", pathParamNames: ["runID"], summary: "SSE stream of LLM chunks" },
  "getV1RunsByRunIDToolCalls": { functionName: "listToolCalls", domainName: "runs", domainMethodName: "listToolCalls", pathParamNames: ["runID"], summary: "List run tool calls" },
  "getV1RunsByRunIDUsage": { functionName: "getUsage", domainName: "runs", domainMethodName: "getUsage", pathParamNames: ["runID"], summary: "List run AI model usage" },
  "postV1RunsBulkCancel": { functionName: "bulkCancelRun", domainName: "runs", domainMethodName: "bulkCancel", pathParamNames: [], summary: "Cancel multiple runs" },
  "postV1RunsBulkCancelAll": { functionName: "bulkCancelAllRun", domainName: "runs", domainMethodName: "bulkCancelAll", pathParamNames: [], summary: "Cancel all runs matching filters" },
  "postV1RunsBulkDlqReplay": { functionName: "bulkDlqReplayRun", domainName: "runs", domainMethodName: "bulkDlqReplay", pathParamNames: [], summary: "Bulk replay dead-lettered runs" },
  "postV1RunsBulkReplay": { functionName: "bulkReplayRun", domainName: "runs", domainMethodName: "bulkReplay", pathParamNames: [], summary: "Replay multiple runs by ID" },
  "getV1RunsDlq": { functionName: "getDlq", domainName: "runs", domainMethodName: "getDlq", pathParamNames: [], summary: "List dead-lettered runs" },
  "getV1Secrets": { functionName: "listSecrets", domainName: "secrets", domainMethodName: "list", pathParamNames: [], summary: "List secrets" },
  "postV1Secrets": { functionName: "createSecret", domainName: "secrets", domainMethodName: "create", pathParamNames: [], summary: "Create a secret" },
  "deleteV1SecretsBySecretID": { functionName: "deleteSecret", domainName: "secrets", domainMethodName: "delete", pathParamNames: ["secretID"], summary: "Delete a secret" },
  "postV1SeedRoles": { functionName: "createSeedRole", domainName: "rbac", domainMethodName: "createSeedRole", pathParamNames: [], summary: "Seed system roles" },
  "getV1Stats": { functionName: "listStats", domainName: "stats", domainMethodName: "list", pathParamNames: [], summary: "Queue statistics" },
  "getV1TagPolicies": { functionName: "listTagPolicies", domainName: "rbac", domainMethodName: "listTagPolicies", pathParamNames: [], summary: "List tag policies" },
  "postV1TagPolicies": { functionName: "createTagPolicy", domainName: "rbac", domainMethodName: "createTagPolicy", pathParamNames: [], summary: "Create tag policy" },
  "deleteV1TagPoliciesByPolicyID": { functionName: "deleteTagPolicy", domainName: "rbac", domainMethodName: "deleteTagPolicy", pathParamNames: ["policyID"], summary: "Delete tag policy" },
  "getV1WebhookDeliveries": { functionName: "listWebhookDeliveries", domainName: "other", domainMethodName: "listWebhookDeliveries", pathParamNames: [], summary: "List webhook deliveries" },
  "postV1WebhookDeliveriesByDeliveryIDRetry": { functionName: "retryWebhookDelivery", domainName: "webhooks", domainMethodName: "retryDelivery", pathParamNames: ["deliveryID"], summary: "Retry a failed webhook delivery" },
  "getV1WebhooksDeliveries": { functionName: "listDeliveries", domainName: "webhooks", domainMethodName: "listDeliveries", pathParamNames: [], summary: "List webhook deliveries" },
  "getV1WebhooksDeliveriesById": { functionName: "getDelivery", domainName: "webhooks", domainMethodName: "getDelivery", pathParamNames: ["id"], summary: "Get webhook delivery details" },
  "postV1WebhooksDeliveriesByIdReplay": { functionName: "replayDelivery", domainName: "webhooks", domainMethodName: "replayDelivery", pathParamNames: ["id"], summary: "Replay webhook delivery" },
  "postV1WebhooksDeliveriesByIdRetry": { functionName: "retryDelivery", domainName: "webhooks", domainMethodName: "retryDeliveryById", pathParamNames: ["id"], summary: "Retry a webhook delivery" },
  "getV1WebhooksSubscriptions": { functionName: "listSubscriptions", domainName: "webhooks", domainMethodName: "listSubscriptions", pathParamNames: [], summary: "List active webhook subscriptions" },
  "postV1WebhooksSubscriptions": { functionName: "subscriptionsWebhook", domainName: "webhooks", domainMethodName: "subscriptions", pathParamNames: [], summary: "Create a webhook subscription" },
  "deleteV1WebhooksSubscriptionsById": { functionName: "deleteSubscription", domainName: "webhooks", domainMethodName: "deleteSubscription", pathParamNames: ["id"], summary: "Delete a webhook subscription" },
  "postV1WebhooksTest": { functionName: "testWebhook", domainName: "webhooks", domainMethodName: "test", pathParamNames: [], summary: "Test webhook endpoint" },
  "getV1WorkflowPoliciesByProjectID": { functionName: "getWorkflowPolicy", domainName: "workflows", domainMethodName: "getPolicy", pathParamNames: ["projectID"], summary: "Get workflow policy" },
  "putV1WorkflowPoliciesByProjectID": { functionName: "upsertWorkflowPolicy", domainName: "workflows", domainMethodName: "upsertPolicy", pathParamNames: ["projectID"], summary: "Upsert workflow policy" },
  "getV1WorkflowRuns": { functionName: "listWorkflowRuns", domainName: "workflowRuns", domainMethodName: "list", pathParamNames: [], summary: "List workflow runs" },
  "deleteV1WorkflowRunsByWorkflowRunID": { functionName: "deleteWorkflowRun", domainName: "workflowRuns", domainMethodName: "delete", pathParamNames: ["workflowRunID"], summary: "Cancel a workflow run" },
  "getV1WorkflowRunsByWorkflowRunID": { functionName: "getWorkflowRun", domainName: "workflowRuns", domainMethodName: "get", pathParamNames: ["workflowRunID"], summary: "Get a workflow run" },
  "getV1WorkflowRunsByWorkflowRunIDExplain": { functionName: "getExplain", domainName: "workflows", domainMethodName: "getExplain", pathParamNames: ["workflowRunID"], summary: "List workflow step decisions" },
  "getV1WorkflowRunsByWorkflowRunIDGraph": { functionName: "getGraph", domainName: "workflows", domainMethodName: "getGraph", pathParamNames: ["workflowRunID"], summary: "Get workflow run graph" },
  "getV1WorkflowRunsByWorkflowRunIDLabels": { functionName: "listLabels", domainName: "workflows", domainMethodName: "listLabels", pathParamNames: ["workflowRunID"], summary: "Get workflow run labels" },
  "postV1WorkflowRunsByWorkflowRunIDPause": { functionName: "pauseWorkflowRun", domainName: "workflowRuns", domainMethodName: "pause", pathParamNames: ["workflowRunID"], summary: "Pause a workflow run" },
  "postV1WorkflowRunsByWorkflowRunIDResume": { functionName: "resumeWorkflowRun", domainName: "workflowRuns", domainMethodName: "resume", pathParamNames: ["workflowRunID"], summary: "Resume a workflow run" },
  "postV1WorkflowRunsByWorkflowRunIDRetry": { functionName: "retryWorkflowRun", domainName: "workflowRuns", domainMethodName: "retry", pathParamNames: ["workflowRunID"], summary: "Retry from first failed step" },
  "getV1WorkflowRunsByWorkflowRunIDSteps": { functionName: "listSteps", domainName: "workflowRuns", domainMethodName: "listSteps", pathParamNames: ["workflowRunID"], summary: "List step runs" },
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefApprove": { functionName: "approveStep", domainName: "workflowRuns", domainMethodName: "approveStep", pathParamNames: ["workflowRunID","stepRef"], summary: "Approve an approval step" },
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefForceComplete": { functionName: "forceCompleteStep", domainName: "workflowRuns", domainMethodName: "forceCompleteStep", pathParamNames: ["workflowRunID","stepRef"], summary: "Force-complete a step" },
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefReplaySubtree": { functionName: "replaySubtreeStep", domainName: "workflowRuns", domainMethodName: "replaySubtreeStep", pathParamNames: ["workflowRunID","stepRef"], summary: "Replay a step subtree" },
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefRetry": { functionName: "retryStep", domainName: "workflowRuns", domainMethodName: "retryStep", pathParamNames: ["workflowRunID","stepRef"], summary: "Retry a single workflow step" },
  "postV1WorkflowRunsByWorkflowRunIDStepsByStepRefSkip": { functionName: "skipStep", domainName: "workflowRuns", domainMethodName: "skipStep", pathParamNames: ["workflowRunID","stepRef"], summary: "Skip a step" },
  "getV1WorkflowRunsByWorkflowRunIDTimeline": { functionName: "getTimeline", domainName: "workflows", domainMethodName: "getTimeline", pathParamNames: ["workflowRunID"], summary: "Get workflow run timeline for Gantt chart rendering" },
  "postV1WorkflowRunsBulkCancel": { functionName: "bulkCancelWorkflowRun", domainName: "workflowRuns", domainMethodName: "bulkCancel", pathParamNames: [], summary: "Bulk cancel workflow runs" },
  "postV1WorkflowRunsBulkReplay": { functionName: "bulkReplayWorkflowRun", domainName: "workflowRuns", domainMethodName: "bulkReplay", pathParamNames: [], summary: "Bulk replay workflow runs" },
  "getV1Workflows": { functionName: "listWorkflows", domainName: "workflows", domainMethodName: "list", pathParamNames: [], summary: "List workflows" },
  "postV1Workflows": { functionName: "createWorkflow", domainName: "workflows", domainMethodName: "create", pathParamNames: [], summary: "Create a workflow" },
  "deleteV1WorkflowsByWorkflowID": { functionName: "deleteWorkflow", domainName: "workflows", domainMethodName: "delete", pathParamNames: ["workflowID"], summary: "Delete a workflow" },
  "getV1WorkflowsByWorkflowID": { functionName: "getWorkflow", domainName: "workflows", domainMethodName: "get", pathParamNames: ["workflowID"], summary: "Get a workflow" },
  "patchV1WorkflowsByWorkflowID": { functionName: "updateWorkflow", domainName: "workflows", domainMethodName: "update", pathParamNames: ["workflowID"], summary: "Update a workflow" },
  "getV1WorkflowsByWorkflowIDActiveVersions": { functionName: "listActiveVersions", domainName: "workflows", domainMethodName: "listActiveVersions", pathParamNames: ["workflowID"], summary: "List active workflow versions" },
  "postV1WorkflowsByWorkflowIDClone": { functionName: "cloneWorkflow", domainName: "workflows", domainMethodName: "clone", pathParamNames: ["workflowID"], summary: "Clone a workflow" },
  "postV1WorkflowsByWorkflowIDDryRun": { functionName: "dryRunWorkflow", domainName: "workflows", domainMethodName: "dryRun", pathParamNames: ["workflowID"], summary: "Validate a workflow DAG structure" },
  "getV1WorkflowsByWorkflowIDGraph": { functionName: "getGraphByWorkflowID", domainName: "workflows", domainMethodName: "getGraphByWorkflowId", pathParamNames: ["workflowID"], summary: "Get DAG visualization" },
  "postV1WorkflowsByWorkflowIDPlan": { functionName: "planWorkflow", domainName: "workflows", domainMethodName: "plan", pathParamNames: ["workflowID"], summary: "Build topological workflow plan preview" },
  "getV1WorkflowsByWorkflowIDRuns": { functionName: "listRunsByWorkflowID", domainName: "workflows", domainMethodName: "listRunsByWorkflowId", pathParamNames: ["workflowID"], summary: "List runs for a workflow" },
  "postV1WorkflowsByWorkflowIDSimulate": { functionName: "simulateWorkflow", domainName: "workflows", domainMethodName: "simulate", pathParamNames: ["workflowID"], summary: "Simulate workflow execution" },
  "postV1WorkflowsByWorkflowIDTrigger": { functionName: "triggerWorkflow", domainName: "workflows", domainMethodName: "trigger", pathParamNames: ["workflowID"], summary: "Trigger a workflow run" },
  "getV1WorkflowsByWorkflowIDVersions": { functionName: "listVersionsByWorkflowID", domainName: "workflows", domainMethodName: "listVersionsByWorkflowId", pathParamNames: ["workflowID"], summary: "List workflow versions" },
  "getV1WorkflowsByWorkflowIDVersionsByFromVersionIDDiffByToVersionID": { functionName: "getDiff", domainName: "workflows", domainMethodName: "getDiff", pathParamNames: ["workflowID","fromVersionID","toVersionID"], summary: "Diff workflow versions" },
  "getV1WorkflowsByWorkflowIDVersionsByVersionID": { functionName: "getVersionByWorkflowIDAndVersionID", domainName: "workflows", domainMethodName: "getVersionByWorkflowIdAndVersionId", pathParamNames: ["workflowID","versionID"], summary: "Get workflow version by version ID" },
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDImpact": { functionName: "getImpact", domainName: "workflows", domainMethodName: "getImpact", pathParamNames: ["workflowID","versionID"], summary: "Workflow version impact" },
  "getV1WorkflowsByWorkflowIDVersionsByVersionIDSteps": { functionName: "listStepsByWorkflowIDAndVersionID", domainName: "workflows", domainMethodName: "listStepsByWorkflowIdAndVersionId", pathParamNames: ["workflowID","versionID"], summary: "List workflow version steps" },
} as const satisfies {
  readonly [K in GeneratedOperationId]: {
    readonly functionName: string;
    readonly domainName: string;
    readonly domainMethodName: string;
    readonly pathParamNames: readonly string[];
    readonly summary?: string;
  };
};

export type GeneratedOperationMetadataById = typeof generatedOperationMetadataById;
