// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerMessage_Registration
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskResult
	//	*WorkerMessage_LogLine
	//	*WorkerMessage_Ack
	Payload       isWorkerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetPayload() isWorkerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerMessage) GetRegistration() *WorkerRegistration {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetLogLine() *LogLine {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_LogLine); ok {
			return x.LogLine
		}
	}
	return nil
}

func (x *WorkerMessage) GetAck() *Acknowledged {
	if x != nil {
		if x, ok := x.Payload.(*WorkerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isWorkerMessage_Payload interface {
	isWorkerMessage_Payload()
}

type WorkerMessage_Registration struct {
	Registration *WorkerRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerMessage_LogLine struct {
	LogLine *LogLine `protobuf:"bytes,4,opt,name=log_line,json=logLine,proto3,oneof"`
}

type WorkerMessage_Ack struct {
	Ack *Acknowledged `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

func (*WorkerMessage_Registration) isWorkerMessage_Payload() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Payload() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Payload() {}

func (*WorkerMessage_LogLine) isWorkerMessage_Payload() {}

func (*WorkerMessage_Ack) isWorkerMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_TaskAssignment
	//	*ServerMessage_CancelTask
	//	*ServerMessage_Ack
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetTaskAssignment() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_TaskAssignment); ok {
			return x.TaskAssignment
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelTask() *CancelTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CancelTask); ok {
			return x.CancelTask
		}
	}
	return nil
}

func (x *ServerMessage) GetAck() *Acknowledged {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_TaskAssignment struct {
	TaskAssignment *TaskAssignment `protobuf:"bytes,1,opt,name=task_assignment,json=taskAssignment,proto3,oneof"`
}

type ServerMessage_CancelTask struct {
	CancelTask *CancelTask `protobuf:"bytes,2,opt,name=cancel_task,json=cancelTask,proto3,oneof"`
}

type ServerMessage_Ack struct {
	Ack *Acknowledged `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*ServerMessage_TaskAssignment) isServerMessage_Payload() {}

func (*ServerMessage_CancelTask) isServerMessage_Payload() {}

func (*ServerMessage_Ack) isServerMessage_Payload() {}

type WorkerRegistration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Queues         []string               `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	JobSlugs       []string               `protobuf:"bytes,4,rep,name=job_slugs,json=jobSlugs,proto3" json:"job_slugs,omitempty"`
	SdkVersion     string                 `protobuf:"bytes,5,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	SdkLanguage    string                 `protobuf:"bytes,6,opt,name=sdk_language,json=sdkLanguage,proto3" json:"sdk_language,omitempty"`
	Hostname       string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	SlotsTotal     int32                  `protobuf:"varint,8,opt,name=slots_total,json=slotsTotal,proto3" json:"slots_total,omitempty"`
	SlotsAvailable int32                  `protobuf:"varint,9,opt,name=slots_available,json=slotsAvailable,proto3" json:"slots_available,omitempty"`
	InFlightTasks  []*InFlightTask        `protobuf:"bytes,10,rep,name=in_flight_tasks,json=inFlightTasks,proto3" json:"in_flight_tasks,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerRegistration) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *WorkerRegistration) GetJobSlugs() []string {
	if x != nil {
		return x.JobSlugs
	}
	return nil
}

func (x *WorkerRegistration) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *WorkerRegistration) GetSdkLanguage() string {
	if x != nil {
		return x.SdkLanguage
	}
	return ""
}

func (x *WorkerRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerRegistration) GetSlotsTotal() int32 {
	if x != nil {
		return x.SlotsTotal
	}
	return 0
}

func (x *WorkerRegistration) GetSlotsAvailable() int32 {
	if x != nil {
		return x.SlotsAvailable
	}
	return 0
}

func (x *WorkerRegistration) GetInFlightTasks() []*InFlightTask {
	if x != nil {
		return x.InFlightTasks
	}
	return nil
}

func (x *WorkerRegistration) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InFlightTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // completed | failed | abandoned
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutputJson    []byte                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InFlightTask) Reset() {
	*x = InFlightTask{}
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFlightTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFlightTask) ProtoMessage() {}

func (x *InFlightTask) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFlightTask.ProtoReflect.Descriptor instead.
func (*InFlightTask) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *InFlightTask) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *InFlightTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InFlightTask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InFlightTask) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobSlug       string                 `protobuf:"bytes,2,opt,name=job_slug,json=jobSlug,proto3" json:"job_slug,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	TimeoutSecs   int32                  `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	RunTokenJwt   string                 `protobuf:"bytes,6,opt,name=run_token_jwt,json=runTokenJwt,proto3" json:"run_token_jwt,omitempty"`
	HmacSignature string                 `protobuf:"bytes,7,opt,name=hmac_signature,json=hmacSignature,proto3" json:"hmac_signature,omitempty"`
	HmacTimestamp string                 `protobuf:"bytes,8,opt,name=hmac_timestamp,json=hmacTimestamp,proto3" json:"hmac_timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TaskAssignment) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskAssignment) GetJobSlug() string {
	if x != nil {
		return x.JobSlug
	}
	return ""
}

func (x *TaskAssignment) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskAssignment) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *TaskAssignment) GetTimeoutSecs() int32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *TaskAssignment) GetRunTokenJwt() string {
	if x != nil {
		return x.RunTokenJwt
	}
	return ""
}

func (x *TaskAssignment) GetHmacSignature() string {
	if x != nil {
		return x.HmacSignature
	}
	return ""
}

func (x *TaskAssignment) GetHmacTimestamp() string {
	if x != nil {
		return x.HmacTimestamp
	}
	return ""
}

func (x *TaskAssignment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // success | failed
	OutputJson    []byte                 `protobuf:"bytes,3,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlotsAvailable int32                  `protobuf:"varint,1,opt,name=slots_available,json=slotsAvailable,proto3" json:"slots_available,omitempty"`
	TimestampUnix  int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetSlotsAvailable() int32 {
	if x != nil {
		return x.SlotsAvailable
	}
	return 0
}

func (x *Heartbeat) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type LogLine struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Level           string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *LogLine) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTask) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelTask) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Acknowledged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledged) Reset() {
	*x = Acknowledged{}
	mi := &file_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledged) ProtoMessage() {}

func (x *Acknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledged.ProtoReflect.Descriptor instead.
func (*Acknowledged) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *Acknowledged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_worker_v1_worker_proto protoreflect.FileDescriptor

const file_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x16worker/v1/worker.proto\x12\x10strait.worker.v1\"\xd0\x02\n" +
	"\rWorkerMessage\x12J\n" +
	"\fregistration\x18\x01 \x01(\v2$.strait.worker.v1.WorkerRegistrationH\x00R\fregistration\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.strait.worker.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\vtask_result\x18\x03 \x01(\v2\x1c.strait.worker.v1.TaskResultH\x00R\n" +
	"taskResult\x126\n" +
	"\blog_line\x18\x04 \x01(\v2\x19.strait.worker.v1.LogLineH\x00R\alogLine\x122\n" +
	"\x03ack\x18\x05 \x01(\v2\x1e.strait.worker.v1.AcknowledgedH\x00R\x03ackB\t\n" +
	"\apayload\"\xdc\x01\n" +
	"\rServerMessage\x12K\n" +
	"\x0ftask_assignment\x18\x01 \x01(\v2 .strait.worker.v1.TaskAssignmentH\x00R\x0etaskAssignment\x12?\n" +
	"\vcancel_task\x18\x02 \x01(\v2\x1c.strait.worker.v1.CancelTaskH\x00R\n" +
	"cancelTask\x122\n" +
	"\x03ack\x18\x03 \x01(\v2\x1e.strait.worker.v1.AcknowledgedH\x00R\x03ackB\t\n" +
	"\apayload\"\xf9\x03\n" +
	"\x12WorkerRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06queues\x18\x03 \x03(\tR\x06queues\x12\x1b\n" +
	"\tjob_slugs\x18\x04 \x03(\tR\bjobSlugs\x12\x1f\n" +
	"\vsdk_version\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12!\n" +
	"\fsdk_language\x18\x06 \x01(\tR\vsdkLanguage\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x1f\n" +
	"\vslots_total\x18\b \x01(\x05R\n" +
	"slotsTotal\x12'\n" +
	"\x0fslots_available\x18\t \x01(\x05R\x0eslotsAvailable\x12F\n" +
	"\x0fin_flight_tasks\x18\n" +
	" \x03(\v2\x1e.strait.worker.v1.InFlightTaskR\rinFlightTasks\x12N\n" +
	"\bmetadata\x18\v \x03(\v22.strait.worker.v1.WorkerRegistration.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\fInFlightTask\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\fR\n" +
	"outputJson\"\x99\x03\n" +
	"\x0eTaskAssignment\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bjob_slug\x18\x02 \x01(\tR\ajobSlug\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x05R\vtimeoutSecs\x12\"\n" +
	"\rrun_token_jwt\x18\x06 \x01(\tR\vrunTokenJwt\x12%\n" +
	"\x0ehmac_signature\x18\a \x01(\tR\rhmacSignature\x12%\n" +
	"\x0ehmac_timestamp\x18\b \x01(\tR\rhmacTimestamp\x12J\n" +
	"\bmetadata\x18\t \x03(\v2..strait.worker.v1.TaskAssignment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\n" +
	"TaskResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\voutput_json\x18\x03 \x01(\fR\n" +
	"outputJson\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"[\n" +
	"\tHeartbeat\x12'\n" +
	"\x0fslots_available\x18\x01 \x01(\x05R\x0eslotsAvailable\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\"|\n" +
	"\aLogLine\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\";\n" +
	"\n" +
	"CancelTask\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1e\n" +
	"\fAcknowledged\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2d\n" +
	"\rWorkerService\x12S\n" +
	"\vStreamTasks\x12\x1f.strait.worker.v1.WorkerMessage\x1a\x1f.strait.worker.v1.ServerMessage(\x010\x01B2Z0strait/internal/api/grpc/proto/workerv1;workerv1b\x06proto3"

var (
	file_worker_v1_worker_proto_rawDescOnce sync.Once
	file_worker_v1_worker_proto_rawDescData []byte
)

func file_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)))
	})
	return file_worker_v1_worker_proto_rawDescData
}

var file_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_worker_v1_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),      // 0: strait.worker.v1.WorkerMessage
	(*ServerMessage)(nil),      // 1: strait.worker.v1.ServerMessage
	(*WorkerRegistration)(nil), // 2: strait.worker.v1.WorkerRegistration
	(*InFlightTask)(nil),       // 3: strait.worker.v1.InFlightTask
	(*TaskAssignment)(nil),     // 4: strait.worker.v1.TaskAssignment
	(*TaskResult)(nil),         // 5: strait.worker.v1.TaskResult
	(*Heartbeat)(nil),          // 6: strait.worker.v1.Heartbeat
	(*LogLine)(nil),            // 7: strait.worker.v1.LogLine
	(*CancelTask)(nil),         // 8: strait.worker.v1.CancelTask
	(*Acknowledged)(nil),       // 9: strait.worker.v1.Acknowledged
	nil,                        // 10: strait.worker.v1.WorkerRegistration.MetadataEntry
	nil,                        // 11: strait.worker.v1.TaskAssignment.MetadataEntry
}
var file_worker_v1_worker_proto_depIdxs = []int32{
	2,  // 0: strait.worker.v1.WorkerMessage.registration:type_name -> strait.worker.v1.WorkerRegistration
	6,  // 1: strait.worker.v1.WorkerMessage.heartbeat:type_name -> strait.worker.v1.Heartbeat
	5,  // 2: strait.worker.v1.WorkerMessage.task_result:type_name -> strait.worker.v1.TaskResult
	7,  // 3: strait.worker.v1.WorkerMessage.log_line:type_name -> strait.worker.v1.LogLine
	9,  // 4: strait.worker.v1.WorkerMessage.ack:type_name -> strait.worker.v1.Acknowledged
	4,  // 5: strait.worker.v1.ServerMessage.task_assignment:type_name -> strait.worker.v1.TaskAssignment
	8,  // 6: strait.worker.v1.ServerMessage.cancel_task:type_name -> strait.worker.v1.CancelTask
	9,  // 7: strait.worker.v1.ServerMessage.ack:type_name -> strait.worker.v1.Acknowledged
	3,  // 8: strait.worker.v1.WorkerRegistration.in_flight_tasks:type_name -> strait.worker.v1.InFlightTask
	10, // 9: strait.worker.v1.WorkerRegistration.metadata:type_name -> strait.worker.v1.WorkerRegistration.MetadataEntry
	11, // 10: strait.worker.v1.TaskAssignment.metadata:type_name -> strait.worker.v1.TaskAssignment.MetadataEntry
	0,  // 11: strait.worker.v1.WorkerService.StreamTasks:input_type -> strait.worker.v1.WorkerMessage
	1,  // 12: strait.worker.v1.WorkerService.StreamTasks:output_type -> strait.worker.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_worker_v1_worker_proto_init() }
func file_worker_v1_worker_proto_init() {
	if File_worker_v1_worker_proto != nil {
		return
	}
	file_worker_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Registration)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskResult)(nil),
		(*WorkerMessage_LogLine)(nil),
		(*WorkerMessage_Ack)(nil),
	}
	file_worker_v1_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_TaskAssignment)(nil),
		(*ServerMessage_CancelTask)(nil),
		(*ServerMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_worker_v1_worker_proto_depIdxs,
		MessageInfos:      file_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_worker_v1_worker_proto = out.File
	file_worker_v1_worker_proto_goTypes = nil
	file_worker_v1_worker_proto_depIdxs = nil
}
