// Package sandboxv1 contains the gRPC client types for communicating with the
// Forge sandbox execution service. These types mirror the protobuf definitions
// in packages/proto/sandbox/v1/sandbox.proto.
//
// In production, these would be generated by protoc. They are hand-written here
// to avoid requiring protoc as a build dependency during initial development.
package sandboxv1

// ExecuteRequest is sent by the orchestrator to start a sandbox execution.
type ExecuteRequest struct {
	RunID    string            `json:"run_id"`
	Language string            `json:"language"`
	Code     string            `json:"code"`
	Payload  []byte            `json:"payload,omitempty"`
	Env      map[string]string `json:"env,omitempty"`
	Limits   *ResourceLimits   `json:"limits,omitempty"`
}

// ResourceLimits defines constraints for sandbox execution.
type ResourceLimits struct {
	TimeoutSecs    int32 `json:"timeout_secs"`
	MemoryBytes    int64 `json:"memory_bytes"`
	NetworkEnabled bool  `json:"network_enabled"`
}

// ExecutionEvent is a streamed event from a running sandbox.
type ExecutionEvent struct {
	Log        *LogEntry        `json:"log,omitempty"`
	Checkpoint *Checkpoint      `json:"checkpoint,omitempty"`
	ToolCall   *ToolCall        `json:"tool_call,omitempty"`
	Result     *ExecutionResult `json:"result,omitempty"`
}

// LogEntry is a log line emitted by the sandbox.
type LogEntry struct {
	Level       string `json:"level"`
	Message     string `json:"message"`
	TimestampMs int64  `json:"timestamp_ms"`
}

// Checkpoint is an intermediate state snapshot persisted during execution.
type Checkpoint struct {
	Sequence int32  `json:"sequence"`
	State    []byte `json:"state"`
}

// ToolCall records an external tool invocation made by the sandbox.
type ToolCall struct {
	ToolName   string `json:"tool_name"`
	Input      []byte `json:"input,omitempty"`
	Output     []byte `json:"output,omitempty"`
	DurationMs int32  `json:"duration_ms"`
	Status     string `json:"status"`
}

// ExecutionResult is the terminal event sent when execution finishes.
type ExecutionResult struct {
	Success    bool   `json:"success"`
	Result     []byte `json:"result,omitempty"`
	Error      string `json:"error,omitempty"`
	DurationMs int64  `json:"duration_ms"`
}
