package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

var (
	routeDeclRe = regexp.MustCompile(`r\.Route\("([^"]+)"`)
	methodRe    = regexp.MustCompile(`\.((Get|Post|Patch|Delete|Put|Options|Head|Handle))\("([^"]+)"`)
	opPathRe    = regexp.MustCompile(`^\s{2}(/[^:]+):\s*$`)
)

type routeScope struct {
	prefix string
	depth  int
}

func main() {
	os.Exit(exitCode(
		os.Stdout,
		os.Stderr,
		os.Stat,
		extractRoutePaths,
		extractOpenAPIPaths,
	))
}

type statFunc func(string) (os.FileInfo, error)

type pathExtractor func(string) (map[string]struct{}, error)

func exitCode(
	stdout io.Writer,
	stderr io.Writer,
	stat statFunc,
	extractRoutes pathExtractor,
	extractSpec pathExtractor,
) int {
	routePaths, err := extractRoutes("internal/api/routes.go")
	if err != nil {
		fmt.Fprintf(stderr, "openapi parity check failed: %v\n", err)
		return 1
	}
	// OpenAPI specs are now auto-generated by Huma framework from typed Go structs.
	// The hand-maintained YAML files have been removed. If they still exist (e.g.,
	// during migration), check parity. Otherwise, skip.
	anyFailed := false
	for _, specFile := range []string{"../../docs/openapi.yaml", "internal/api/openapi.yaml"} {
		if _, statErr := stat(specFile); os.IsNotExist(statErr) {
			continue // file removed, Huma generates the spec now
		}
		specPaths, specErr := extractSpec(specFile)
		if specErr != nil {
			fmt.Fprintf(stderr, "openapi parity check failed: %v\n", specErr)
			return 1
		}
		if fail := compare(stdout, specFile, routePaths, specPaths); fail {
			anyFailed = true
		}
	}
	if anyFailed {
		return 1
	}

	fmt.Fprintln(stdout, "OpenAPI parity check passed")
	return 0
}

func compare(out io.Writer, name string, routes, openapi map[string]struct{}) bool {
	missing := diff(routes, openapi)
	extra := diff(openapi, routes)
	if len(missing) == 0 && len(extra) == 0 {
		return false
	}

	fmt.Fprintf(out, "\n%s parity mismatch:\n", name)
	if len(missing) > 0 {
		fmt.Fprintln(out, "  Missing paths:")
		for _, p := range missing {
			fmt.Fprintf(out, "    - %s\n", p)
		}
	}
	if len(extra) > 0 {
		fmt.Fprintln(out, "  Extra paths:")
		for _, p := range extra {
			fmt.Fprintf(out, "    - %s\n", p)
		}
	}
	return true
}

func diff(a, b map[string]struct{}) []string {
	out := make([]string, 0)
	for k := range a {
		if _, ok := b[k]; !ok {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

var allowedFiles = map[string]struct{}{
	"internal/api/routes.go":    {},
	"../../docs/openapi.yaml":   {},
	"internal/api/openapi.yaml": {},
}

func extractOpenAPIPaths(path string) (map[string]struct{}, error) {
	if _, ok := allowedFiles[path]; !ok {
		return nil, fmt.Errorf("unsupported file: %s", path)
	}
	f, err := os.Open(path) // #nosec G304 -- path is restricted by allowedFiles map above
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return parseOpenAPIPaths(f)
}

func parseOpenAPIPaths(r io.Reader) (map[string]struct{}, error) {
	out := map[string]struct{}{}
	s := bufio.NewScanner(r)
	for s.Scan() {
		line := s.Text()
		m := opPathRe.FindStringSubmatch(line)
		if len(m) == 0 {
			continue
		}
		p := strings.TrimSpace(m[1])
		if isTrackedPath(p) {
			out[p] = struct{}{}
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func extractRoutePaths(path string) (map[string]struct{}, error) {
	if _, ok := allowedFiles[path]; !ok {
		return nil, fmt.Errorf("unsupported file: %s", path)
	}
	f, err := os.Open(path) // #nosec G304 -- path is restricted by allowedFiles map above
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return parseRoutePaths(f)
}

func parseRoutePaths(r io.Reader) (map[string]struct{}, error) {
	out := map[string]struct{}{}
	scopes := []routeScope{}
	depth := 0

	s := bufio.NewScanner(r)
	for s.Scan() {
		line := s.Text()

		for len(scopes) > 0 && depth < scopes[len(scopes)-1].depth {
			scopes = scopes[:len(scopes)-1]
		}

		if m := routeDeclRe.FindStringSubmatch(line); len(m) > 0 {
			prefix := currentPrefix(scopes)
			scopes = append(scopes, routeScope{prefix: join(prefix, m[1]), depth: depth + 1})
		}

		if m := methodRe.FindStringSubmatch(line); len(m) > 0 {
			prefix := currentPrefix(scopes)
			p := join(prefix, m[3])
			if isTrackedPath(p) {
				out[p] = struct{}{}
			}
		}

		depth += strings.Count(line, "{")
		depth -= strings.Count(line, "}")
		if depth < 0 {
			depth = 0
		}
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func currentPrefix(scopes []routeScope) string {
	if len(scopes) == 0 {
		return ""
	}
	return scopes[len(scopes)-1].prefix
}

func join(a, b string) string {
	if a == "" {
		return normalizePath(b)
	}
	if b == "/" {
		return normalizePath(a)
	}
	return normalizePath(strings.TrimRight(a, "/") + "/" + strings.TrimLeft(b, "/"))
}

func normalizePath(p string) string {
	if p == "" {
		return ""
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	for strings.Contains(p, "//") {
		p = strings.ReplaceAll(p, "//", "/")
	}
	if len(p) > 1 {
		p = strings.TrimRight(p, "/")
	}
	return p
}

func isTrackedPath(p string) bool {
	return strings.HasPrefix(p, "/v1/") || strings.HasPrefix(p, "/sdk/v1/")
}
