DROP POLICY IF EXISTS tenant_isolation ON run_events;
ALTER TABLE run_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE run_events DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON run_iterations;
ALTER TABLE run_iterations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE run_iterations DISABLE ROW LEVEL SECURITY;
