ALTER TABLE jobs DROP COLUMN IF EXISTS region;
ALTER TABLE jobs DROP COLUMN IF EXISTS image_uri;
ALTER TABLE jobs DROP COLUMN IF EXISTS machine_preset;
ALTER TABLE jobs DROP COLUMN IF EXISTS execution_mode;
