-- The 000304 backfill deactivated duplicate active rows so 000305 could
-- safely build a partial unique index. Reversing that deactivation would
-- re-create the duplicate-dispatch surface the upgrade closed, so this
-- down is intentionally a no-op. The freshest row per (project_id,
-- webhook_url) was kept active and remains usable.
