package main

import (
	"encoding/json"
	"strings"

	"orchestrator/internal/cli/client"

	"github.com/spf13/cobra"
)

func newFixturesCommand(state *appState) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "fixtures",
		Short: "Manage fixture data for demos and testing",
	}

	cmd.AddCommand(newFixturesCreateCommand(state))
	cmd.AddCommand(newFixturesCleanCommand(state))

	return cmd
}

func newFixturesCreateCommand(state *appState) *cobra.Command {
	var template string

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create fixture data",
		RunE: func(cmd *cobra.Command, _ []string) error {
			projectID, err := requireProjectID(state, "")
			if err != nil {
				return err
			}

			cli, err := newAPIClient(state)
			if err != nil {
				return err
			}

			name := "fixture-minimal-job"
			slug := "fixture-minimal-job"
			if strings.EqualFold(template, "full") {
				name = "fixture-full-job"
				slug = "fixture-full-job"
			}

			job, err := cli.CreateJob(cmd.Context(), client.CreateJobRequest{
				ProjectID:   projectID,
				Name:        name,
				Slug:        slug,
				Description: "autogenerated fixture",
				EndpointURL: "http://localhost:3000/webhook",
				TimeoutSecs: 30,
				MaxAttempts: 1,
			})
			if err != nil {
				if !strings.Contains(strings.ToLower(err.Error()), "duplicate") && !strings.Contains(strings.ToLower(err.Error()), "exists") {
					return err
				}
				jobs, listErr := cli.ListJobs(cmd.Context(), projectID)
				if listErr != nil {
					return listErr
				}
				for _, candidate := range jobs {
					if candidate.Slug == slug {
						job = &candidate
						break
					}
				}
				if job == nil {
					return err
				}
			}

			payload := map[string]any{"fixture": template, "source": "orchestrator fixtures create"}
			raw, _ := json.Marshal(payload)
			run, triggerErr := cli.TriggerJob(cmd.Context(), job.ID, client.TriggerJobRequest{Payload: raw}, "")
			if triggerErr != nil {
				return triggerErr
			}

			return printData(state, map[string]any{
				"template": template,
				"job_id":   job.ID,
				"run_id":   run.ID,
				"status":   run.Status,
			})
		},
	}

	cmd.Flags().StringVar(&template, "template", "minimal", "fixture template: minimal|full")

	return cmd
}

func newFixturesCleanCommand(state *appState) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove fixture jobs",
		RunE: func(cmd *cobra.Command, _ []string) error {
			projectID, err := requireProjectID(state, "")
			if err != nil {
				return err
			}

			cli, err := newAPIClient(state)
			if err != nil {
				return err
			}

			jobs, err := cli.ListJobs(cmd.Context(), projectID)
			if err != nil {
				return err
			}

			results := make([]map[string]any, 0)
			for _, job := range jobs {
				if !strings.HasPrefix(job.Slug, "fixture-") {
					continue
				}
				err := cli.DeleteJob(cmd.Context(), job.ID)
				results = append(results, map[string]any{"job_id": job.ID, "slug": job.Slug, "deleted": err == nil, "error": errDetail(err)})
			}

			return printData(state, results)
		},
	}

	return cmd
}
