// Code generated by packages/billing/scripts/generate-catalog.mjs; DO NOT EDIT.
// Source: packages/billing/catalog/strait-pricing.json
// Catalog SHA256: 640c96ee5256406209b6d31c6483b7375ef63df5bc06cb6018d4d3a633b513dd

export const PRICING_CATALOG_VERSION = "2026-05-21";
export const PRICING_CATALOG_HASH =
  "640c96ee5256406209b6d31c6483b7375ef63df5bc06cb6018d4d3a633b513dd";
export const METERED_UNIT = "orchestration_run";

export type PlanKey =
  | "free"
  | "starter"
  | "pro"
  | "scale"
  | "business"
  | "enterprise";

export type Plan = {
  name: string;
  description: string;
  prices: { monthly: number; yearly: number };
  trial: boolean;
  creditCardRequired: boolean;
  computeCredit: string;
  features: string[];
  roadmapFeatures: string[];
  limits: {
    organizations: number | null;
    projectsPerOrg: number | null;
    membersPerOrg: number | null;
    runsPerMonth: number | null;
    concurrentRuns: number | null;
    retentionDays: number | null;
    regions: string;
    spendingLimits: string;
    overagePerThousandRuns: number | null;
    executionModes: string;
    workflowSteps: number | null;
    approvalGates: boolean;
    subWorkflows: boolean;
    jobChaining: boolean;
    canaryDeployments: boolean;
    scheduledJobs: number | null;
    cronMinIntervalSeconds: number | null;
    environments: number | null;
    webhookEndpoints: number | null;
    apiRateLimit: number | null;
    workerConnections: number | null;
  };
  governance: {
    rbac: "none" | "basic" | "full" | "advanced";
    auditLogs: boolean;
    ssoSaml: boolean;
    aiMessagesPerDay: number | null;
    aiByok: boolean;
  };
  cta: { label: string; href: string };
  highlighted: boolean;
  badge?: string;
};

export type PlanApiResponse = {
  tier: PlanKey;
  display_name: string;
  price_monthly_usd: number;
  price_annual_usd: number;
  max_orgs_per_user: number;
  max_projects_per_org: number;
  max_members_per_org: number;
  max_runs_per_day: number;
  max_runs_per_month: number;
  compute_credit_microusd: number;
  overage_per_k_runs_microusd: number;
  max_concurrent_runs: number;
  retention_days: number;
  allowed_regions: string[] | null;
  max_alert_rules_per_project: number;
  max_webhook_subs_per_project: number;
  max_log_drains_per_org: number;
  max_ai_model_calls_per_day: number;
  ai_assistant_byok: boolean;
  has_rbac: boolean;
  rbac_level: string;
  has_audit_logs: boolean;
  has_sso: boolean;
  has_sla: boolean;
  has_canary_deployments: boolean;
  has_approval_gates: boolean;
  has_sub_workflows: boolean;
  has_job_chaining: boolean;
  has_compensating_txns: boolean;
  has_dedicated_compute: boolean;
  has_static_ips: boolean;
  has_vpc_peering: boolean;
  has_scim: boolean;
  has_data_residency: boolean;
  has_custom_rbac: boolean;
  has_reserved_capacity: boolean;
  has_priority_queue: boolean;
  has_ip_allowlisting: boolean;
  has_session_management: boolean;
  has_secret_rotation: boolean;
  has_siem_export: boolean;
  requires_credit_card: boolean;
  support_level: string;
  max_environments: number;
  max_scheduled_jobs: number;
  cron_min_interval_sec: number;
  max_webhook_endpoints: number;
  max_workflow_dag_steps: number;
  api_rate_limit: number;
  worker_connections: number;
  roadmap_features: string[];
};

export type BillingAddon = {
  type: string;
  displayName: string;
  lookupKey: string;
  packSize: number;
  priceCents: number;
  maxTotal: number;
  status: "active" | "roadmap";
  availableOn: PlanKey[];
};

export const PLAN_KEYS: PlanKey[] = [
  "free",
  "starter",
  "pro",
  "scale",
  "business",
  "enterprise",
] as PlanKey[];

export const PLANS: Record<PlanKey, Plan> = {
  free: {
    name: "Free",
    description: "For evaluation, demos, and side projects.",
    prices: {
      monthly: 0,
      yearly: 0,
    },
    trial: false,
    creditCardRequired: false,
    computeCredit: "5,000 orchestration runs/mo",
    features: [
      "5,000 orchestration runs/mo",
      "3 concurrent runs",
      "10 workflow steps",
      "1 project, 1 environment, 1 schedule",
      "Community support",
    ],
    roadmapFeatures: [],
    limits: {
      organizations: 1,
      projectsPerOrg: 1,
      membersPerOrg: 1,
      runsPerMonth: 5000,
      concurrentRuns: 3,
      retentionDays: 7,
      regions: "1 (iad)",
      spendingLimits: "$50 default when overage is enabled",
      overagePerThousandRuns: 50,
      executionModes: "HTTP + worker",
      workflowSteps: 10,
      approvalGates: false,
      subWorkflows: false,
      jobChaining: false,
      canaryDeployments: false,
      scheduledJobs: 1,
      cronMinIntervalSeconds: 300,
      environments: 1,
      webhookEndpoints: 0,
      apiRateLimit: 60,
      workerConnections: 1,
    },
    governance: {
      rbac: "none",
      auditLogs: false,
      ssoSaml: false,
      aiMessagesPerDay: 20,
      aiByok: false,
    },
    cta: {
      label: "Get started free",
      href: "/login?redirect=/app/upgrade",
    },
    highlighted: false,
    badge: "No credit card required",
  },
  starter: {
    name: "Starter",
    description: "For solo developers, small projects, and internal tools.",
    prices: {
      monthly: 1900,
      yearly: 18_000,
    },
    trial: false,
    creditCardRequired: true,
    computeCredit: "50,000 orchestration runs/mo",
    features: [
      "50,000 orchestration runs/mo",
      "15 concurrent runs",
      "25 workflow steps",
      "3 projects, 3 members",
      "Email support (72h)",
    ],
    roadmapFeatures: [],
    limits: {
      organizations: 2,
      projectsPerOrg: 3,
      membersPerOrg: 3,
      runsPerMonth: 50_000,
      concurrentRuns: 15,
      retentionDays: 14,
      regions: "All",
      spendingLimits: "$100 default",
      overagePerThousandRuns: 40,
      executionModes: "HTTP + worker",
      workflowSteps: 25,
      approvalGates: false,
      subWorkflows: false,
      jobChaining: false,
      canaryDeployments: false,
      scheduledJobs: 5,
      cronMinIntervalSeconds: 60,
      environments: 1,
      webhookEndpoints: 3,
      apiRateLimit: 300,
      workerConnections: 5,
    },
    governance: {
      rbac: "basic",
      auditLogs: false,
      ssoSaml: false,
      aiMessagesPerDay: 100,
      aiByok: false,
    },
    cta: {
      label: "Upgrade to Starter",
      href: "/login?redirect=/app/upgrade",
    },
    highlighted: false,
  },
  pro: {
    name: "Pro",
    description: "For production SaaS and mid-market teams.",
    prices: {
      monthly: 9900,
      yearly: 94_800,
    },
    trial: false,
    creditCardRequired: true,
    computeCredit: "1,000,000 orchestration runs/mo",
    features: [
      "1,000,000 orchestration runs/mo",
      "100 concurrent runs",
      "100 workflow steps",
      "Approval gates and sub-workflows",
      "Priority email support (24h)",
    ],
    roadmapFeatures: [],
    limits: {
      organizations: 5,
      projectsPerOrg: 10,
      membersPerOrg: 10,
      runsPerMonth: 1_000_000,
      concurrentRuns: 100,
      retentionDays: 30,
      regions: "All",
      spendingLimits: "$200 default",
      overagePerThousandRuns: 20,
      executionModes: "HTTP + worker",
      workflowSteps: 100,
      approvalGates: true,
      subWorkflows: true,
      jobChaining: true,
      canaryDeployments: false,
      scheduledJobs: 25,
      cronMinIntervalSeconds: 30,
      environments: 3,
      webhookEndpoints: 10,
      apiRateLimit: 1000,
      workerConnections: 25,
    },
    governance: {
      rbac: "full",
      auditLogs: false,
      ssoSaml: false,
      aiMessagesPerDay: 500,
      aiByok: true,
    },
    cta: {
      label: "Upgrade to Pro",
      href: "/login?redirect=/app/upgrade",
    },
    highlighted: true,
    badge: "Most popular",
  },
  scale: {
    name: "Scale",
    description: "For high-volume products and multi-product platforms.",
    prices: {
      monthly: 29_900,
      yearly: 286_800,
    },
    trial: false,
    creditCardRequired: true,
    computeCredit: "5,000,000 orchestration runs/mo",
    features: [
      "5,000,000 orchestration runs/mo",
      "300 concurrent runs",
      "500 workflow steps",
      "Audit logs and canary deployments",
      "Priority Slack support (8h)",
    ],
    roadmapFeatures: [],
    limits: {
      organizations: 10,
      projectsPerOrg: 50,
      membersPerOrg: 50,
      runsPerMonth: 5_000_000,
      concurrentRuns: 300,
      retentionDays: 60,
      regions: "All",
      spendingLimits: "$500 default",
      overagePerThousandRuns: 6,
      executionModes: "HTTP + worker",
      workflowSteps: 500,
      approvalGates: true,
      subWorkflows: true,
      jobChaining: true,
      canaryDeployments: true,
      scheduledJobs: 100,
      cronMinIntervalSeconds: 1,
      environments: 10,
      webhookEndpoints: 25,
      apiRateLimit: 3000,
      workerConnections: 100,
    },
    governance: {
      rbac: "full",
      auditLogs: true,
      ssoSaml: false,
      aiMessagesPerDay: 1000,
      aiByok: true,
    },
    cta: {
      label: "Upgrade to Scale",
      href: "/login?redirect=/app/upgrade",
    },
    highlighted: false,
  },
  business: {
    name: "Business",
    description: "For enterprise volume and regulated workloads, pre-contract.",
    prices: {
      monthly: 49_900,
      yearly: 478_800,
    },
    trial: false,
    creditCardRequired: true,
    computeCredit: "25,000,000 orchestration runs/mo",
    features: [
      "25,000,000 orchestration runs/mo",
      "500 concurrent runs",
      "Unlimited projects, environments, schedules, and members",
      "Advanced RBAC and audit logs",
      "SLA target (non-contractual)",
    ],
    roadmapFeatures: [
      "SSO/SAML",
      "SCIM",
      "IP allowlisting",
      "static IPs",
      "VPC peering",
      "data residency",
    ],
    limits: {
      organizations: null,
      projectsPerOrg: null,
      membersPerOrg: null,
      runsPerMonth: 25_000_000,
      concurrentRuns: 500,
      retentionDays: 90,
      regions: "All",
      spendingLimits: "$1,500 default",
      overagePerThousandRuns: 3,
      executionModes: "HTTP + worker",
      workflowSteps: null,
      approvalGates: true,
      subWorkflows: true,
      jobChaining: true,
      canaryDeployments: true,
      scheduledJobs: null,
      cronMinIntervalSeconds: 0,
      environments: null,
      webhookEndpoints: null,
      apiRateLimit: null,
      workerConnections: null,
    },
    governance: {
      rbac: "advanced",
      auditLogs: true,
      ssoSaml: false,
      aiMessagesPerDay: null,
      aiByok: true,
    },
    cta: {
      label: "Upgrade to Business",
      href: "/login?redirect=/app/upgrade",
    },
    highlighted: false,
  },
  enterprise: {
    name: "Enterprise",
    description:
      "For single-tenant deployments, custom contracts, and BYO-cloud.",
    prices: {
      monthly: -1,
      yearly: -1,
    },
    trial: false,
    creditCardRequired: false,
    computeCredit: "Custom",
    features: [
      "50M+ orchestration runs/mo",
      "Custom concurrency, step caps, and history",
      "Multi-org and consolidated invoicing",
      "Dedicated TAM and named on-call",
      "99.99% SLA target (non-contractual)",
    ],
    roadmapFeatures: [
      "SSO/SAML",
      "SCIM",
      "IP allowlisting",
      "static IPs",
      "VPC peering",
      "data residency",
      "single-tenant orchestration",
      "BYO-cloud",
    ],
    limits: {
      organizations: null,
      projectsPerOrg: null,
      membersPerOrg: null,
      runsPerMonth: null,
      concurrentRuns: null,
      retentionDays: null,
      regions: "All",
      spendingLimits: "Custom",
      overagePerThousandRuns: 3,
      executionModes: "HTTP + worker",
      workflowSteps: null,
      approvalGates: true,
      subWorkflows: true,
      jobChaining: true,
      canaryDeployments: true,
      scheduledJobs: null,
      cronMinIntervalSeconds: 0,
      environments: null,
      webhookEndpoints: null,
      apiRateLimit: null,
      workerConnections: null,
    },
    governance: {
      rbac: "full",
      auditLogs: true,
      ssoSaml: false,
      aiMessagesPerDay: null,
      aiByok: true,
    },
    cta: {
      label: "Contact sales",
      href: "/contact",
    },
    highlighted: false,
    badge: "Contact sales",
  },
} as Record<PlanKey, Plan>;

export const PLAN_API_RESPONSE: PlanApiResponse[] = [
  {
    tier: "free",
    display_name: "Free",
    price_monthly_usd: 0,
    price_annual_usd: 0,
    max_orgs_per_user: 1,
    max_projects_per_org: 1,
    max_members_per_org: 1,
    max_runs_per_day: -1,
    max_runs_per_month: 5000,
    compute_credit_microusd: 1_000_000,
    overage_per_k_runs_microusd: 500_000,
    max_concurrent_runs: 3,
    retention_days: 7,
    allowed_regions: ["iad"],
    max_alert_rules_per_project: 0,
    max_webhook_subs_per_project: 0,
    max_log_drains_per_org: 0,
    max_ai_model_calls_per_day: 20,
    ai_assistant_byok: false,
    has_rbac: false,
    rbac_level: "",
    has_audit_logs: false,
    has_sso: false,
    has_sla: false,
    has_canary_deployments: false,
    has_approval_gates: false,
    has_sub_workflows: false,
    has_job_chaining: false,
    has_compensating_txns: false,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: false,
    support_level: "community",
    max_environments: 1,
    max_scheduled_jobs: 1,
    cron_min_interval_sec: 300,
    max_webhook_endpoints: 0,
    max_workflow_dag_steps: 10,
    api_rate_limit: 60,
    worker_connections: 1,
    roadmap_features: [],
  },
  {
    tier: "starter",
    display_name: "Starter",
    price_monthly_usd: 1900,
    price_annual_usd: 18_000,
    max_orgs_per_user: 2,
    max_projects_per_org: 3,
    max_members_per_org: 3,
    max_runs_per_day: -1,
    max_runs_per_month: 50_000,
    compute_credit_microusd: 19_000_000,
    overage_per_k_runs_microusd: 400_000,
    max_concurrent_runs: 15,
    retention_days: 14,
    allowed_regions: null,
    max_alert_rules_per_project: 0,
    max_webhook_subs_per_project: 3,
    max_log_drains_per_org: 1,
    max_ai_model_calls_per_day: 100,
    ai_assistant_byok: false,
    has_rbac: true,
    rbac_level: "basic",
    has_audit_logs: false,
    has_sso: false,
    has_sla: false,
    has_canary_deployments: false,
    has_approval_gates: false,
    has_sub_workflows: false,
    has_job_chaining: false,
    has_compensating_txns: false,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: true,
    support_level: "email_72h",
    max_environments: 1,
    max_scheduled_jobs: 5,
    cron_min_interval_sec: 60,
    max_webhook_endpoints: 3,
    max_workflow_dag_steps: 25,
    api_rate_limit: 300,
    worker_connections: 5,
    roadmap_features: [],
  },
  {
    tier: "pro",
    display_name: "Pro",
    price_monthly_usd: 9900,
    price_annual_usd: 94_800,
    max_orgs_per_user: 5,
    max_projects_per_org: 10,
    max_members_per_org: 10,
    max_runs_per_day: -1,
    max_runs_per_month: 1_000_000,
    compute_credit_microusd: 99_000_000,
    overage_per_k_runs_microusd: 200_000,
    max_concurrent_runs: 100,
    retention_days: 30,
    allowed_regions: null,
    max_alert_rules_per_project: 50,
    max_webhook_subs_per_project: 10,
    max_log_drains_per_org: 5,
    max_ai_model_calls_per_day: 500,
    ai_assistant_byok: true,
    has_rbac: true,
    rbac_level: "full",
    has_audit_logs: false,
    has_sso: false,
    has_sla: false,
    has_canary_deployments: false,
    has_approval_gates: true,
    has_sub_workflows: true,
    has_job_chaining: true,
    has_compensating_txns: true,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: true,
    support_level: "priority_24h",
    max_environments: 3,
    max_scheduled_jobs: 25,
    cron_min_interval_sec: 30,
    max_webhook_endpoints: 10,
    max_workflow_dag_steps: 100,
    api_rate_limit: 1000,
    worker_connections: 25,
    roadmap_features: [],
  },
  {
    tier: "scale",
    display_name: "Scale",
    price_monthly_usd: 29_900,
    price_annual_usd: 286_800,
    max_orgs_per_user: 10,
    max_projects_per_org: 50,
    max_members_per_org: 50,
    max_runs_per_day: -1,
    max_runs_per_month: 5_000_000,
    compute_credit_microusd: 299_000_000,
    overage_per_k_runs_microusd: 60_000,
    max_concurrent_runs: 300,
    retention_days: 60,
    allowed_regions: null,
    max_alert_rules_per_project: 50,
    max_webhook_subs_per_project: 25,
    max_log_drains_per_org: 10,
    max_ai_model_calls_per_day: 1000,
    ai_assistant_byok: true,
    has_rbac: true,
    rbac_level: "full",
    has_audit_logs: true,
    has_sso: false,
    has_sla: false,
    has_canary_deployments: true,
    has_approval_gates: true,
    has_sub_workflows: true,
    has_job_chaining: true,
    has_compensating_txns: true,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: true,
    support_level: "priority_slack_8h",
    max_environments: 10,
    max_scheduled_jobs: 100,
    cron_min_interval_sec: 1,
    max_webhook_endpoints: 25,
    max_workflow_dag_steps: 500,
    api_rate_limit: 3000,
    worker_connections: 100,
    roadmap_features: [],
  },
  {
    tier: "business",
    display_name: "Business",
    price_monthly_usd: 49_900,
    price_annual_usd: 478_800,
    max_orgs_per_user: -1,
    max_projects_per_org: -1,
    max_members_per_org: -1,
    max_runs_per_day: -1,
    max_runs_per_month: 25_000_000,
    compute_credit_microusd: 499_000_000,
    overage_per_k_runs_microusd: 30_000,
    max_concurrent_runs: 500,
    retention_days: 90,
    allowed_regions: null,
    max_alert_rules_per_project: -1,
    max_webhook_subs_per_project: -1,
    max_log_drains_per_org: -1,
    max_ai_model_calls_per_day: -1,
    ai_assistant_byok: true,
    has_rbac: true,
    rbac_level: "advanced",
    has_audit_logs: true,
    has_sso: false,
    has_sla: true,
    has_canary_deployments: true,
    has_approval_gates: true,
    has_sub_workflows: true,
    has_job_chaining: true,
    has_compensating_txns: true,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: true,
    support_level: "priority_slack_8h",
    max_environments: -1,
    max_scheduled_jobs: -1,
    cron_min_interval_sec: 0,
    max_webhook_endpoints: -1,
    max_workflow_dag_steps: -1,
    api_rate_limit: -1,
    worker_connections: -1,
    roadmap_features: [
      "SSO/SAML",
      "SCIM",
      "IP allowlisting",
      "static IPs",
      "VPC peering",
      "data residency",
    ],
  },
  {
    tier: "enterprise",
    display_name: "Enterprise",
    price_monthly_usd: -1,
    price_annual_usd: -1,
    max_orgs_per_user: -1,
    max_projects_per_org: -1,
    max_members_per_org: -1,
    max_runs_per_day: -1,
    max_runs_per_month: -1,
    compute_credit_microusd: 0,
    overage_per_k_runs_microusd: 30_000,
    max_concurrent_runs: -1,
    retention_days: -1,
    allowed_regions: null,
    max_alert_rules_per_project: -1,
    max_webhook_subs_per_project: -1,
    max_log_drains_per_org: -1,
    max_ai_model_calls_per_day: -1,
    ai_assistant_byok: true,
    has_rbac: true,
    rbac_level: "full",
    has_audit_logs: true,
    has_sso: false,
    has_sla: true,
    has_canary_deployments: true,
    has_approval_gates: true,
    has_sub_workflows: true,
    has_job_chaining: true,
    has_compensating_txns: true,
    has_dedicated_compute: false,
    has_static_ips: false,
    has_vpc_peering: false,
    has_scim: false,
    has_data_residency: false,
    has_custom_rbac: false,
    has_reserved_capacity: false,
    has_priority_queue: false,
    has_ip_allowlisting: false,
    has_session_management: false,
    has_secret_rotation: false,
    has_siem_export: false,
    requires_credit_card: false,
    support_level: "dedicated",
    max_environments: -1,
    max_scheduled_jobs: -1,
    cron_min_interval_sec: 0,
    max_webhook_endpoints: -1,
    max_workflow_dag_steps: -1,
    api_rate_limit: -1,
    worker_connections: -1,
    roadmap_features: [
      "SSO/SAML",
      "SCIM",
      "IP allowlisting",
      "static IPs",
      "VPC peering",
      "data residency",
      "single-tenant orchestration",
      "BYO-cloud",
    ],
  },
] as PlanApiResponse[];

export const ACTIVE_ADDONS: BillingAddon[] = [
  {
    type: "concurrency_100",
    displayName: "+100 concurrent runs",
    lookupKey: "strait_addon_concurrency_100",
    packSize: 100,
    priceCents: 2000,
    maxTotal: -1,
    status: "active",
    availableOn: ["pro", "scale", "business"],
  },
  {
    type: "history_30d",
    displayName: "+30 days run history",
    lookupKey: "strait_addon_history_30d",
    packSize: 30,
    priceCents: 4000,
    maxTotal: 365,
    status: "active",
    availableOn: ["scale", "business"],
  },
  {
    type: "environments_5",
    displayName: "+5 active environments",
    lookupKey: "strait_addon_environments_5",
    packSize: 5,
    priceCents: 3000,
    maxTotal: -1,
    status: "active",
    availableOn: ["pro", "scale"],
  },
] as BillingAddon[];

export const ROADMAP_ADDONS: BillingAddon[] = [
  {
    type: "compliance_archive",
    displayName: "Compliance archive",
    lookupKey: "strait_addon_compliance_archive",
    packSize: 1,
    priceCents: 5000,
    maxTotal: 1,
    status: "roadmap",
    availableOn: ["pro", "scale", "business"],
  },
  {
    type: "dedicated_workers",
    displayName: "Dedicated worker pool",
    lookupKey: "strait_addon_dedicated_pool",
    packSize: 1,
    priceCents: 20_000,
    maxTotal: -1,
    status: "roadmap",
    availableOn: ["scale", "business"],
  },
] as BillingAddon[];

export const ROADMAP_FEATURES: string[] = [
  "SSO/SAML",
  "SCIM",
  "IP allowlisting",
  "static IPs",
  "VPC peering",
  "data residency",
  "single-tenant orchestration",
  "BYO-cloud",
  "dedicated worker pool",
  "compliance archive",
];

export function formatPlanPrice(
  plan: Plan,
  interval: "monthly" | "yearly"
): string {
  const price = plan.prices[interval];
  if (price === 0) {
    return "$0";
  }
  if (price < 0) {
    return "Custom";
  }
  if (interval === "yearly") {
    return formatPriceWithCents(Math.round(price / 12));
  }
  return formatPriceWithCents(price);
}

export function formatPrice(cents: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(cents / 100);
}

export function formatPriceWithCents(cents: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(cents / 100);
}
