#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "../../..");
const catalogPath = join(
  repoRoot,
  "packages/billing/catalog/strait-pricing.json"
);
const check = process.argv.includes("--check");

const source = readFileSync(catalogPath, "utf8");
const catalog = JSON.parse(source);
const hash = createHash("sha256").update(source).digest("hex");

const planOrder = ["free", "starter", "pro", "scale", "business", "enterprise"];
const planConst = {
  free: "domain.PlanFree",
  starter: "domain.PlanStarter",
  pro: "domain.PlanPro",
  scale: "domain.PlanScale",
  business: "domain.PlanBusiness",
  enterprise: "domain.PlanEnterprise",
};
const planSuffix = {
  free: "Free",
  starter: "Starter",
  pro: "Pro",
  scale: "Scale",
  business: "Business",
  enterprise: "Enterprise",
};
const addonConst = {
  concurrency_100: "AddonConcurrency100",
  history_30d: "AddonHistory30d",
  compliance_archive: "AddonComplianceArchive",
  dedicated_workers: "AddonDedicatedWorkers",
  environments_5: "AddonEnvironments5",
};

function generatedHeader(comment) {
  return `${comment} Code generated by packages/billing/scripts/generate-catalog.mjs; DO NOT EDIT.\n${comment} Source: packages/billing/catalog/strait-pricing.json\n${comment} Catalog SHA256: ${hash}\n`;
}

function gofmt(source) {
  const result = spawnSync("gofmt", { input: source, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(result.stderr || "gofmt failed");
  }
  return result.stdout;
}

function biomeFormat(source, path) {
  const result = spawnSync(
    "bunx",
    ["biome", "check", "--write", "--unsafe", "--stdin-file-path", path],
    {
      input: source,
      encoding: "utf8",
      cwd: repoRoot,
    }
  );
  if (result.status !== 0) {
    throw new Error(result.stderr || "biome format failed");
  }
  return result.stdout;
}

function goString(value) {
  return JSON.stringify(value ?? "");
}

function tsStringUnion(values) {
  return values.map((value) => `  | ${JSON.stringify(value)}`).join("\n");
}

function goBool(value) {
  return value ? "true" : "false";
}

function goInt(value) {
  return Number.isInteger(value) ? String(value) : "0";
}

function goInt64(value) {
  return `${goInt(value)}`;
}

function uiCTA(plan) {
  if (plan.tier === "free") {
    return { label: "Get started free", href: "/login?redirect=/app/upgrade" };
  }
  if (plan.tier === "enterprise") {
    return { label: "Contact sales", href: "/contact" };
  }
  return {
    label: `Upgrade to ${plan.displayName}`,
    href: "/login?redirect=/app/upgrade",
  };
}

function maxJobChainDepth(plan) {
  if (!plan.features.jobChaining) {
    return "0";
  }
  if (plan.limits.workflowSteps === -1) {
    return "-1";
  }
  return "10";
}

function webhookEventLevel(tier) {
  if (tier === "free") {
    return "none";
  }
  if (tier === "starter") {
    return "basic";
  }
  if (tier === "enterprise") {
    return "all_custom";
  }
  return "all";
}

function goRegions(regions) {
  if (regions === null || regions === undefined) {
    return "nil";
  }
  if (regions.length === 0) {
    return "[]string{}";
  }
  return `[]string{${regions.map(goString).join(", ")}}`;
}

function goStringSlice(values) {
  if (!values || values.length === 0) {
    return "[]string{}";
  }
  return `[]string{${values.map(goString).join(", ")}}`;
}

function goPlanTierSlice(values) {
  if (!values || values.length === 0) {
    return "[]domain.PlanTier{}";
  }
  return `[]domain.PlanTier{${values.map((tier) => planConst[tier]).join(", ")}}`;
}

function displaySpendingCap(plan) {
  const cap = plan.overage.defaultSpendingCapMicrousd;
  if (cap < 0) {
    return "Custom";
  }
  if (!plan.overage.defaultEnabled && plan.tier === "free") {
    return "$50 default when overage is enabled";
  }
  return `$${(cap / 1_000_000).toLocaleString("en-US", { maximumFractionDigits: 0 })} default`;
}

function toPlanTs(plan) {
  const limits = plan.limits;
  const features = plan.features;
  const annual = plan.prices.annualCents;
  const overageCents =
    plan.overage.microusdPer1K < 0 ? null : plan.overage.microusdPer1K / 10_000;
  return {
    name: plan.displayName,
    description: plan.description,
    prices: { monthly: plan.prices.monthlyCents, yearly: annual },
    creditCardRequired: plan.creditCardRequired,
    includedRuns:
      limits.runsPerMonth === -1
        ? "Custom"
        : `${limits.runsPerMonth.toLocaleString("en-US")} orchestration runs/mo`,
    features: plan.featureBullets,
    roadmapFeatures: plan.roadmapFeatures,
    limits: {
      organizations: limits.orgs === -1 ? null : limits.orgs,
      projectsPerOrg: limits.projects === -1 ? null : limits.projects,
      membersPerOrg: limits.members === -1 ? null : limits.members,
      runsPerMonth: limits.runsPerMonth === -1 ? null : limits.runsPerMonth,
      concurrentRuns:
        limits.concurrentRuns === -1 ? null : limits.concurrentRuns,
      retentionDays: limits.retentionDays === -1 ? null : limits.retentionDays,
      regions:
        limits.allowedRegions === null
          ? "All"
          : `${limits.allowedRegions.length} (${limits.allowedRegions.join(", ")})`,
      spendingLimits: displaySpendingCap(plan),
      overagePerThousandRuns: overageCents,
      executionModes: "HTTP + worker",
      workflowSteps: limits.workflowSteps === -1 ? null : limits.workflowSteps,
      logStreaming: features.logStreaming,
      approvalGates: features.approvalGates,
      subWorkflows: features.subWorkflows,
      jobChaining: features.jobChaining,
      canaryDeployments: features.canaryDeployments,
      scheduledJobs: limits.scheduledJobs === -1 ? null : limits.scheduledJobs,
      cronMinIntervalSeconds: limits.cronMinIntervalSec,
      environments: limits.environments === -1 ? null : limits.environments,
      webhookEndpoints:
        limits.webhookEndpoints === -1 ? null : limits.webhookEndpoints,
      apiRateLimit: limits.apiRateLimit === -1 ? null : limits.apiRateLimit,
      workerConnections:
        limits.workerConnections === -1 ? null : limits.workerConnections,
    },
    governance: {
      rbac: features.rbacLevel,
      auditLogs: features.auditLogs,
    },
    cta: uiCTA(plan),
    highlighted: plan.highlighted,
    badge: plan.badge || undefined,
  };
}

function toApiPlan(plan) {
  const limits = plan.limits;
  const features = plan.features;
  return {
    tier: plan.tier,
    display_name: plan.displayName,
    price_monthly_usd: plan.prices.monthlyCents,
    price_annual_usd: plan.prices.annualCents,
    max_orgs_per_user: limits.orgs,
    max_projects_per_org: limits.projects,
    max_members_per_org: limits.members,
    max_runs_per_month: limits.runsPerMonth,
    overage_per_k_runs_microusd: plan.overage.microusdPer1K,
    overage_default_enabled: plan.overage.defaultEnabled,
    default_spending_cap_microusd: plan.overage.defaultSpendingCapMicrousd,
    max_concurrent_runs: limits.concurrentRuns,
    retention_days: limits.retentionDays,
    max_webhook_subs_per_project: limits.webhookSubscriptions,
    max_log_drains_per_org: limits.logDrains,
    max_notification_channels: limits.notificationChannels,
    has_rbac: features.rbac,
    rbac_level: features.rbacLevel === "none" ? "" : features.rbacLevel,
    has_audit_logs: features.auditLogs,
    has_sla: features.slaTarget,
    has_log_streaming: features.logStreaming,
    has_canary_deployments: features.canaryDeployments,
    has_approval_gates: features.approvalGates,
    has_sub_workflows: features.subWorkflows,
    has_job_chaining: features.jobChaining,
    has_compensating_txns: features.compensatingTransactions,
    requires_credit_card: plan.creditCardRequired,
    support_level: plan.supportLevel,
    max_environments: limits.environments,
    max_scheduled_jobs: limits.scheduledJobs,
    cron_min_interval_sec: limits.cronMinIntervalSec,
    max_webhook_endpoints: limits.webhookEndpoints,
    max_workflow_dag_steps: limits.workflowSteps,
    api_rate_limit: limits.apiRateLimit,
    worker_connections: limits.workerConnections,
    roadmap_features: plan.roadmapFeatures,
  };
}

function generateProductsTs() {
  const plans = Object.fromEntries(
    catalog.plans.map((plan) => [plan.tier, toPlanTs(plan)])
  );
  const apiPlans = catalog.plans.map(toApiPlan);
  const activeAddons = catalog.addons.filter(
    (addon) => addon.status === "active"
  );
  const roadmapAddons = catalog.addons.filter(
    (addon) => addon.status !== "active"
  );
  const addonOrder = catalog.addons.map((addon) => addon.type);
  const activeAddonOrder = activeAddons.map((addon) => addon.type);
  const roadmapAddonOrder = roadmapAddons.map((addon) => addon.type);
  return `${generatedHeader("//")}

export const PRICING_CATALOG_VERSION = ${JSON.stringify(catalog.version)};
export const PRICING_CATALOG_HASH = ${JSON.stringify(hash)};
export const METERED_UNIT = ${JSON.stringify(catalog.meteredUnit)};

export type PlanKey =
  | "free"
  | "starter"
  | "pro"
  | "scale"
  | "business"
  | "enterprise";

export type AddonKey =
${tsStringUnion(addonOrder)};

export type ActiveAddonKey =
${tsStringUnion(activeAddonOrder)};

export type RoadmapAddonKey =
${tsStringUnion(roadmapAddonOrder)};

export type Plan = {
  name: string;
  description: string;
  prices: { monthly: number; yearly: number };
  creditCardRequired: boolean;
  includedRuns: string;
  features: string[];
  roadmapFeatures: string[];
  limits: {
    organizations: number | null;
    projectsPerOrg: number | null;
    membersPerOrg: number | null;
    runsPerMonth: number | null;
    concurrentRuns: number | null;
    retentionDays: number | null;
    regions: string;
    spendingLimits: string;
    overagePerThousandRuns: number | null;
    executionModes: string;
    workflowSteps: number | null;
    approvalGates: boolean;
    subWorkflows: boolean;
    jobChaining: boolean;
    canaryDeployments: boolean;
    scheduledJobs: number | null;
    cronMinIntervalSeconds: number | null;
    environments: number | null;
    webhookEndpoints: number | null;
    apiRateLimit: number | null;
    workerConnections: number | null;
    logStreaming: boolean;
  };
  governance: {
    rbac: "none" | "basic" | "full" | "advanced";
    auditLogs: boolean;
  };
  cta: { label: string; href: string };
  highlighted: boolean;
  badge?: string;
};

export type PlanApiResponse = {
  tier: PlanKey;
  display_name: string;
  price_monthly_usd: number;
  price_annual_usd: number;
  max_orgs_per_user: number;
  max_projects_per_org: number;
  max_members_per_org: number;
  max_runs_per_month: number;
  overage_per_k_runs_microusd: number;
  overage_default_enabled: boolean;
  default_spending_cap_microusd: number;
  max_concurrent_runs: number;
  retention_days: number;
  max_webhook_subs_per_project: number;
  max_log_drains_per_org: number;
  max_notification_channels: number;
  has_rbac: boolean;
  rbac_level: "" | "basic" | "full" | "advanced";
  has_audit_logs: boolean;
  has_sla: boolean;
  has_log_streaming: boolean;
  has_canary_deployments: boolean;
  has_approval_gates: boolean;
  has_sub_workflows: boolean;
  has_job_chaining: boolean;
  has_compensating_txns: boolean;
  requires_credit_card: boolean;
  support_level: string;
  max_environments: number;
  max_scheduled_jobs: number;
  cron_min_interval_sec: number;
  max_webhook_endpoints: number;
  max_workflow_dag_steps: number;
  api_rate_limit: number;
  worker_connections: number;
  roadmap_features: string[];
};

export type BillingAddon = {
  type: AddonKey;
  displayName: string;
  lookupKey: string;
  packSize: number;
  priceCents: number;
  maxTotal: number;
  status: "active" | "roadmap";
  availableOn: PlanKey[];
};

export type ActiveBillingAddon = BillingAddon & {
  type: ActiveAddonKey;
  status: "active";
};

export type RoadmapBillingAddon = BillingAddon & {
  type: RoadmapAddonKey;
  status: "roadmap";
};

export const PLAN_KEYS: PlanKey[] = ${JSON.stringify(planOrder, null, 2)} as PlanKey[];

export const ADDON_KEYS: AddonKey[] = ${JSON.stringify(addonOrder, null, 2)} as AddonKey[];

export const ACTIVE_ADDON_KEYS: ActiveAddonKey[] = ${JSON.stringify(activeAddonOrder, null, 2)} as ActiveAddonKey[];

export const ROADMAP_ADDON_KEYS: RoadmapAddonKey[] = ${JSON.stringify(roadmapAddonOrder, null, 2)} as RoadmapAddonKey[];

export const PLANS: Record<PlanKey, Plan> = ${JSON.stringify(plans, null, 2)} as Record<PlanKey, Plan>;

export const PLAN_API_RESPONSE: PlanApiResponse[] = ${JSON.stringify(apiPlans, null, 2)} as PlanApiResponse[];

export const ACTIVE_ADDONS: ActiveBillingAddon[] = ${JSON.stringify(activeAddons, null, 2)} as ActiveBillingAddon[];

export const ROADMAP_ADDONS: RoadmapBillingAddon[] = ${JSON.stringify(roadmapAddons, null, 2)} as RoadmapBillingAddon[];

export const ROADMAP_FEATURES: string[] = ${JSON.stringify(catalog.roadmapFeatures, null, 2)};

export function formatPlanPrice(
  plan: Plan,
  interval: "monthly" | "yearly"
): string {
  const price = plan.prices[interval];
  if (price === 0) {
    return "$0";
  }
  if (price < 0) {
    return "Custom";
  }
  if (interval === "yearly") {
    return formatPriceWithCents(Math.round(price / 12));
  }
  return formatPriceWithCents(price);
}

export function formatPrice(cents: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(cents / 100);
}

export function formatPriceWithCents(cents: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(cents / 100);
}
`;
}

function generateGoPlans() {
  const constants = catalog.plans
    .map((plan) => {
      const suffix = planSuffix[plan.tier];
      const goMonthlyCents =
        plan.tier === "enterprise" ? 0 : plan.prices.monthlyCents;
      const goAnnualCents =
        plan.tier === "enterprise" ? 0 : plan.prices.annualCents;
      const creditMicrousd =
        plan.tier === "free" ? 1_000_000 : Math.max(goMonthlyCents, 0) * 10_000;
      return `\tPrice${suffix}MonthlyCents = ${goInt(goMonthlyCents)}
\tPrice${suffix}AnnualCents = ${goInt(goAnnualCents)}
\tCredit${suffix}Microusd int64 = ${goInt64(creditMicrousd)}
\tMaxRunsPerMonth${suffix} = ${goInt(plan.limits.runsPerMonth)}
\tConcurrent${suffix} = ${goInt(plan.limits.concurrentRuns)}
\t${suffix}OveragePerKMicrousd int64 = ${goInt64(plan.overage.microusdPer1K)}
\tRetention${suffix} = ${goInt(plan.limits.retentionDays)}
\tMaxOrgs${suffix} = ${goInt(plan.limits.orgs)}
\tMaxProjects${suffix} = ${goInt(plan.limits.projects)}
\tMaxMembers${suffix} = ${goInt(plan.limits.members)}
\tMaxSpending${suffix} int64 = ${goInt64(plan.overage.defaultSpendingCapMicrousd)}
\tMaxDAGSteps${suffix} = ${goInt(plan.limits.workflowSteps)}
\tMaxScheduled${suffix} = ${goInt(plan.limits.scheduledJobs)}
\tCronMinInterval${suffix}Sec = ${goInt(plan.limits.cronMinIntervalSec)}
\tMaxDispatchPriority${suffix} = ${goInt(plan.limits.dispatchPriority)}
\tWorkerConnections${suffix} = ${goInt(plan.limits.workerConnections)}
\tAPIRate${suffix} = ${goInt(plan.limits.apiRateLimit)}`;
    })
    .join("\n\n");

  const planLiterals = catalog.plans
    .map((plan) => {
      const l = plan.limits;
      const f = plan.features;
      const addonEntries = catalog.addons
        .filter(
          (addon) =>
            addon.status === "active" && addon.availableOn.includes(plan.tier)
        )
        .map((addon) => {
          const maxPacks =
            addon.maxTotal > 0 &&
            addon.type === "history_30d" &&
            l.retentionDays > 0
              ? Math.max(
                  Math.floor(
                    (addon.maxTotal - l.retentionDays) / addon.packSize
                  ),
                  0
                )
              : -1;
          return `\t\t\t${addonConst[addon.type]}: ${maxPacks},`;
        });
      const maxAddonPacks =
        addonEntries.length === 0
          ? "nil"
          : `map[AddonType]int{\n${addonEntries.join("\n")}\n\t\t}`;
      return `\t${planConst[plan.tier]}: {
\t\tPlanTier:                ${planConst[plan.tier]},
\t\tDisplayName:             ${goString(plan.displayName)},
\t\tPriceMonthlyUsd:         Price${planSuffix[plan.tier]}MonthlyCents,
\t\tPriceAnnualUsd:          Price${planSuffix[plan.tier]}AnnualCents,
\t\tMaxOrgsPerUser:          MaxOrgs${planSuffix[plan.tier]},
\t\tMaxProjectsPerOrg:       MaxProjects${planSuffix[plan.tier]},
\t\tMaxMembersPerOrg:        MaxMembers${planSuffix[plan.tier]},
\t\tMaxRunsPerDay:           -1,
\t\tMaxRunsPerMonth:         MaxRunsPerMonth${planSuffix[plan.tier]},
\t\tOveragePerKMicrousd:     ${planSuffix[plan.tier]}OveragePerKMicrousd,
\t\tMaxConcurrentRuns:       Concurrent${planSuffix[plan.tier]},
\t\tRetentionDays:           Retention${planSuffix[plan.tier]},
\t\tAllowedRegions:          ${goRegions(l.allowedRegions)},
\t\tMaxAlertRulesPerProj:    ${goInt(l.alertRules)},
\t\tMaxWebhookSubsPerProj:   ${goInt(l.webhookSubscriptions)},
\t\tMaxLogDrainsPerOrg:      ${goInt(l.logDrains)},
\t\tMaxNotificationChannels: ${goInt(l.notificationChannels)},
\t\tHasRBAC:                 ${goBool(f.rbac)},
\t\tRBACLevel:               ${goString(f.rbacLevel === "none" ? "" : f.rbacLevel)},
\t\tHasAuditLogs:            ${goBool(f.auditLogs)},
\t\tHasSSO:                  false,
\t\tHasSLA:                  ${goBool(f.slaTarget)},
\t\tRequiresCreditCard:      ${goBool(plan.creditCardRequired)},
\t\tAllowsHTTPMode:          true,
\t\tLogStreamingEnabled:     ${goBool(f.logStreaming)},
\t\tMaxDispatchPriority:     MaxDispatchPriority${planSuffix[plan.tier]},
\t\tWorkerConnections:       WorkerConnections${planSuffix[plan.tier]},
\t\tSupportLevel:            ${goString(plan.supportLevel)},
\t\tMaxWorkflowDAGSteps:     MaxDAGSteps${planSuffix[plan.tier]},
\t\tHasApprovalGates:        ${goBool(f.approvalGates)},
\t\tHasSubWorkflows:         ${goBool(f.subWorkflows)},
\t\tHasJobChaining:          ${goBool(f.jobChaining)},
\t\tMaxJobChainDepth:        ${maxJobChainDepth(plan)},
\t\tHasCompensatingTxns:     ${goBool(f.compensatingTransactions)},
\t\tHasCanaryDeployments:    ${goBool(f.canaryDeployments)},
\t\tHasDedicatedCompute:     false,
\t\tHasStaticIPs:            false,
\t\tHasVPCPeering:           false,
\t\tHasSCIM:                 false,
\t\tHasDataResidency:        false,
\t\tHasCustomRBAC:           false,
\t\tHasPriorityQueue:        false,
\t\tHasIPAllowlisting:       false,
\t\tHasSessionManagement:    false,
\t\tHasSecretRotation:       false,
\t\tHasSIEMExport:           false,
\t\tMaxScheduledJobs:        MaxScheduled${planSuffix[plan.tier]},
\t\tCronMinIntervalSec:      CronMinInterval${planSuffix[plan.tier]}Sec,
\t\tAllCronOverlapPolicies:  ${plan.tier === "free" ? "false" : "true"},
\t\tMaxEnvironments:         ${goInt(l.environments)},
\t\tMaxWebhookEndpoints:     ${goInt(l.webhookEndpoints)},
\t\tWebhookEventLevel:       ${goString(webhookEventLevel(plan.tier))},
\t\tAPIRateLimit:            APIRate${planSuffix[plan.tier]},
\t\tMaxAddonPacks:           ${maxAddonPacks},
\t},`;
    })
    .join("\n");

  return `${generatedHeader("//")}package billing

import "strait/internal/domain"

const PricingCatalogVersion = ${goString(catalog.version)}
const PricingCatalogHash = ${goString(hash)}
const MeteredUnit = ${goString(catalog.meteredUnit)}

// HTTPCostPerRunMicrousd is the per-run cost for HTTP execution mode.
// 20 micro-USD = $0.00002/run = $20/1M runs.
const HTTPCostPerRunMicrousd int64 = 20

// WorkerCostPerRunMicrousd is the per-run cost for Worker execution mode.
// Flat rate matching HTTP dispatch.
const WorkerCostPerRunMicrousd int64 = 20

// WebhookDeliveryCostPerRunMicrousd is the per-successful-delivery cost for
// outbound webhook deliveries. Billed once on eventual success; failed
// deliveries that never succeed are not billed.
const WebhookDeliveryCostPerRunMicrousd int64 = 20

const DefaultOveragePerKMicrousd int64 = 500_000

const (
${constants}
)

// Plans maps plan tiers to their limits.
var Plans = map[domain.PlanTier]OrgPlanLimits{
${planLiterals}
}
`;
}

function generateGoCatalog() {
  const entries = catalog.plans
    .map(
      (plan) => `\t${planConst[plan.tier]}: {
\t\tTier:                 ${planConst[plan.tier]},
\t\tDisplayName:          ${goString(plan.displayName)},
\t\tPriceMonthlyCents:    Price${planSuffix[plan.tier]}MonthlyCents,
\t\tPriceAnnualCents:     Price${planSuffix[plan.tier]}AnnualCents,
\t\tLookupKeyMonthly:     ${goString(plan.lookupKeys.monthly)},
\t\tLookupKeyAnnual:      ${goString(plan.lookupKeys.annual)},
\t\tLookupKeyOverage:     ${goString(plan.lookupKeys.overage)},
\t\tOverageMicrousdPer1K: ${planSuffix[plan.tier]}OveragePerKMicrousd,
\t\tOverageDefaultEnabled: ${goBool(plan.overage.defaultEnabled)},
\t\tDefaultSpendingCapMicrousd: MaxSpending${planSuffix[plan.tier]},
\t\tIncludedRunsPerMonth: MaxRunsPerMonth${planSuffix[plan.tier]},
\t\tRetentionDays:        Retention${planSuffix[plan.tier]},
\t\tConcurrency:          Concurrent${planSuffix[plan.tier]},
\t\tEnvironments:         ${goInt(plan.limits.environments)},
\t\tLogDrainGB:           ${goInt(plan.limits.logDrainGB)},
\t\tRoadmapFeatures:      ${goStringSlice(plan.roadmapFeatures)},
\t},`
    )
    .join("\n");
  const addonOrder = catalog.addons
    .map((addon) => addonConst[addon.type])
    .join(", ");
  const addonEntries = catalog.addons
    .map(
      (addon) => `\t${addonConst[addon.type]}: {
\t\tType:        ${addonConst[addon.type]},
\t\tDisplayName: ${goString(addon.displayName)},
\t\tLookupKey:   ${goString(addon.lookupKey)},
\t\tPackSize:    ${goInt(addon.packSize)},
\t\tPriceCents:  ${goInt(addon.priceCents)},
\t\tMaxTotal:    ${goInt(addon.maxTotal)},
\t\tStatus:      ${goString(addon.status)},
\t\tAvailableOn: ${goPlanTierSlice(addon.availableOn)},
\t},`
    )
    .join("\n");
  return `${generatedHeader("//")}package billing

import "strait/internal/domain"

// PlanCatalogs is the generated pricing catalog: one entry per launch tier.
var PlanCatalogs = map[domain.PlanTier]PlanCatalog{
${entries}
}

// AddonCatalogOrder is the generated stable display and validation order for
// add-on products.
var AddonCatalogOrder = []AddonType{${addonOrder}}

// AddonCatalogs is the generated pricing catalog: one entry per add-on.
var AddonCatalogs = map[AddonType]AddonCatalog{
${addonEntries}
}
`;
}

const outputs = new Map([
  [
    join(repoRoot, "packages/billing/src/products.ts"),
    biomeFormat(generateProductsTs(), "packages/billing/src/products.ts"),
  ],
  [
    join(repoRoot, "apps/strait/internal/billing/plans_generated.go"),
    gofmt(generateGoPlans()),
  ],
  [
    join(repoRoot, "apps/strait/internal/billing/catalog_generated.go"),
    gofmt(generateGoCatalog()),
  ],
]);

let drift = false;
for (const [path, content] of outputs) {
  if (check) {
    let existing = "";
    try {
      existing = readFileSync(path, "utf8");
    } catch {
      existing = "";
    }
    if (existing !== content) {
      console.error(`Generated file is stale: ${relative(repoRoot, path)}`);
      drift = true;
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${relative(repoRoot, path)}`);
  }
}

if (drift) {
  process.exit(1);
}
