package api

import (
	"encoding/json"
	"net/http"
	"reflect"
	"sync"

	"github.com/danielgtaylor/huma/v2"
)

var errorResponseType = reflect.TypeFor[ErrorResponse]()
var humaErrorOverrideOnce sync.Once

// humaStatusError carries an ErrorResponse together with its HTTP status so
// it can flow through Huma's error pipeline. The JSON representation is the
// canonical Strait error envelope, which means the OpenAPI spec generated by
// Huma describes the exact shape the server actually emits.
type humaStatusError struct {
	status int
	body   ErrorResponse
}

func (e *humaStatusError) Error() string {
	if e.body.Error == nil {
		return http.StatusText(e.status)
	}
	return e.body.Error.Message
}

func (e *humaStatusError) GetStatus() int {
	return e.status
}

// MarshalJSON ensures Huma writes the canonical envelope rather than the
// embedded humaStatusError fields.
func (e *humaStatusError) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.body)
}

// ContentType keeps responses on application/json. Huma's default ErrorModel
// would otherwise rewrite this to application/problem+json (RFC 9457), which
// is not the contract Strait advertises.
func (e *humaStatusError) ContentType(ct string) string {
	return ct
}

// Schema makes Huma describe error responses with the canonical ErrorResponse
// envelope (and its nested APIError) instead of the internal humaStatusError
// type. This is what the SDK codegen pipeline ultimately renders.
func (e *humaStatusError) Schema(r huma.Registry) *huma.Schema {
	return r.Schema(errorResponseType, true, "ErrorResponse")
}

// installHumaErrorOverride replaces Huma's default RFC 9457 ErrorModel with
// the Strait ErrorResponse envelope. It must be called before any
// huma.Register call so the generated OpenAPI spec references the right
// schemas. Because huma.NewError is a package-level variable, this is a
// process-wide override; callers gate it behind a sync.Once.
func installHumaErrorOverride() {
	humaErrorOverrideOnce.Do(func() {
		//nolint:reassign // huma.NewError is a documented package-level extension point.
		huma.NewError = func(status int, msg string, errs ...error) huma.StatusError {
			details := make([]string, 0, len(errs))
			for _, err := range errs {
				if err == nil {
					continue
				}
				details = append(details, err.Error())
			}
			message := msg
			if message == "" {
				message = http.StatusText(status)
			}
			return &humaStatusError{
				status: status,
				body: ErrorResponse{
					Error: &APIError{
						Code:    defaultErrorCode(status),
						Message: message,
						Details: details,
					},
				},
			}
		}
	})
}
