// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq.

package api

import (
	"context"
	"sync"
	"time"

	"strait/internal/store"
)

// Ensure, that AnalyticsStoreMock does implement AnalyticsStore.
// If this is not the case, regenerate this file with moq.
var _ AnalyticsStore = &AnalyticsStoreMock{}

// AnalyticsStoreMock is a mock implementation of AnalyticsStore.
//
//	func TestSomethingThatUsesAnalyticsStore(t *testing.T) {
//
//		// make and configure a mocked AnalyticsStore
//		mockedAnalyticsStore := &AnalyticsStoreMock{
//			GetApprovalStatsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.ApprovalStats, error) {
//				panic("mock out the GetApprovalStats method")
//			},
//			GetCostAnalyticsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostAnalytics, error) {
//				panic("mock out the GetCostAnalytics method")
//			},
//			GetCostByTriggerFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostByTrigger, error) {
//				panic("mock out the GetCostByTrigger method")
//			},
//			GetCostForecastFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostForecast, error) {
//				panic("mock out the GetCostForecast method")
//			},
//			GetCostOutliersFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, threshold float64) ([]store.CostOutlier, error) {
//				panic("mock out the GetCostOutliers method")
//			},
//			GetCostTrendsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostTrendPoint, error) {
//				panic("mock out the GetCostTrends method")
//			},
//			GetEventLatencyFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.EventLatencyStats, error) {
//				panic("mock out the GetEventLatency method")
//			},
//			GetEventVolumeFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.EventVolumeBucket, error) {
//				panic("mock out the GetEventVolume method")
//			},
//			GetJobComparisonFunc: func(ctx context.Context, projectID string, jobIDs []string, from time.Time, to time.Time) ([]store.JobComparison, error) {
//				panic("mock out the GetJobComparison method")
//			},
//			GetJobCostRankingFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobCostRanking, error) {
//				panic("mock out the GetJobCostRanking method")
//			},
//			GetJobHistoryFunc: func(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time, bucket string) ([]store.JobHistoryBucket, error) {
//				panic("mock out the GetJobHistory method")
//			},
//			GetJobReliabilityFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobReliability, error) {
//				panic("mock out the GetJobReliability method")
//			},
//			GetPerformanceAnalyticsFunc: func(ctx context.Context, projectID string, periodHours int) (*store.PerformanceAnalytics, error) {
//				panic("mock out the GetPerformanceAnalytics method")
//			},
//			GetRunDurationDistributionFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunDurationBucket, error) {
//				panic("mock out the GetRunDurationDistribution method")
//			},
//			GetRunFailureReasonsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.RunFailureReason, error) {
//				panic("mock out the GetRunFailureReasons method")
//			},
//			GetRunSummaryFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.RunSummary, error) {
//				panic("mock out the GetRunSummary method")
//			},
//			GetRunTimelineFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.RunTimelineBucket, error) {
//				panic("mock out the GetRunTimeline method")
//			},
//			GetRunsByTriggerFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunsByTrigger, error) {
//				panic("mock out the GetRunsByTrigger method")
//			},
//			GetRunsByVersionFunc: func(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time) ([]store.RunsByVersion, error) {
//				panic("mock out the GetRunsByVersion method")
//			},
//			GetTagCostFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagCost, error) {
//				panic("mock out the GetTagCost method")
//			},
//			GetTagSummaryFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagSummary, error) {
//				panic("mock out the GetTagSummary method")
//			},
//			GetTopCostsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopCostItem, error) {
//				panic("mock out the GetTopCosts method")
//			},
//			GetTopFailingJobsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingJob, error) {
//				panic("mock out the GetTopFailingJobs method")
//			},
//			GetTopFailingTagsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingTag, error) {
//				panic("mock out the GetTopFailingTags method")
//			},
//			GetTopFailingWebhooksFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingEndpoint, error) {
//				panic("mock out the GetTopFailingWebhooks method")
//			},
//			GetWebhookDeliveryStatsFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.WebhookEndpointStats, error) {
//				panic("mock out the GetWebhookDeliveryStats method")
//			},
//			GetWebhookEndpointHealthFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WebhookHealthBucket, error) {
//				panic("mock out the GetWebhookEndpointHealth method")
//			},
//			GetWorkflowCompletionRatesFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WorkflowCompletionBucket, error) {
//				panic("mock out the GetWorkflowCompletionRates method")
//			},
//			GetWorkflowStepDurationsFunc: func(ctx context.Context, projectID string, workflowID string, from time.Time, to time.Time) ([]store.StepDuration, error) {
//				panic("mock out the GetWorkflowStepDurations method")
//			},
//			GetWorkflowSummaryFunc: func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.WorkflowSummary, error) {
//				panic("mock out the GetWorkflowSummary method")
//			},
//		}
//
//		// use mockedAnalyticsStore in code that requires AnalyticsStore
//		// and then make assertions.
//
//	}
type AnalyticsStoreMock struct {
	// GetApprovalStatsFunc mocks the GetApprovalStats method.
	GetApprovalStatsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.ApprovalStats, error)

	// GetCostAnalyticsFunc mocks the GetCostAnalytics method.
	GetCostAnalyticsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostAnalytics, error)

	// GetCostByTriggerFunc mocks the GetCostByTrigger method.
	GetCostByTriggerFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostByTrigger, error)

	// GetCostForecastFunc mocks the GetCostForecast method.
	GetCostForecastFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostForecast, error)

	// GetCostOutliersFunc mocks the GetCostOutliers method.
	GetCostOutliersFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, threshold float64) ([]store.CostOutlier, error)

	// GetCostTrendsFunc mocks the GetCostTrends method.
	GetCostTrendsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostTrendPoint, error)

	// GetEventLatencyFunc mocks the GetEventLatency method.
	GetEventLatencyFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.EventLatencyStats, error)

	// GetEventVolumeFunc mocks the GetEventVolume method.
	GetEventVolumeFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.EventVolumeBucket, error)

	// GetJobComparisonFunc mocks the GetJobComparison method.
	GetJobComparisonFunc func(ctx context.Context, projectID string, jobIDs []string, from time.Time, to time.Time) ([]store.JobComparison, error)

	// GetJobCostRankingFunc mocks the GetJobCostRanking method.
	GetJobCostRankingFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobCostRanking, error)

	// GetJobHistoryFunc mocks the GetJobHistory method.
	GetJobHistoryFunc func(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time, bucket string) ([]store.JobHistoryBucket, error)

	// GetJobReliabilityFunc mocks the GetJobReliability method.
	GetJobReliabilityFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobReliability, error)

	// GetPerformanceAnalyticsFunc mocks the GetPerformanceAnalytics method.
	GetPerformanceAnalyticsFunc func(ctx context.Context, projectID string, periodHours int) (*store.PerformanceAnalytics, error)

	// GetRunDurationDistributionFunc mocks the GetRunDurationDistribution method.
	GetRunDurationDistributionFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunDurationBucket, error)

	// GetRunFailureReasonsFunc mocks the GetRunFailureReasons method.
	GetRunFailureReasonsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.RunFailureReason, error)

	// GetRunSummaryFunc mocks the GetRunSummary method.
	GetRunSummaryFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.RunSummary, error)

	// GetRunTimelineFunc mocks the GetRunTimeline method.
	GetRunTimelineFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.RunTimelineBucket, error)

	// GetRunsByTriggerFunc mocks the GetRunsByTrigger method.
	GetRunsByTriggerFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunsByTrigger, error)

	// GetRunsByVersionFunc mocks the GetRunsByVersion method.
	GetRunsByVersionFunc func(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time) ([]store.RunsByVersion, error)

	// GetTagCostFunc mocks the GetTagCost method.
	GetTagCostFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagCost, error)

	// GetTagSummaryFunc mocks the GetTagSummary method.
	GetTagSummaryFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagSummary, error)

	// GetTopCostsFunc mocks the GetTopCosts method.
	GetTopCostsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopCostItem, error)

	// GetTopFailingJobsFunc mocks the GetTopFailingJobs method.
	GetTopFailingJobsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingJob, error)

	// GetTopFailingTagsFunc mocks the GetTopFailingTags method.
	GetTopFailingTagsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingTag, error)

	// GetTopFailingWebhooksFunc mocks the GetTopFailingWebhooks method.
	GetTopFailingWebhooksFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingEndpoint, error)

	// GetWebhookDeliveryStatsFunc mocks the GetWebhookDeliveryStats method.
	GetWebhookDeliveryStatsFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.WebhookEndpointStats, error)

	// GetWebhookEndpointHealthFunc mocks the GetWebhookEndpointHealth method.
	GetWebhookEndpointHealthFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WebhookHealthBucket, error)

	// GetWorkflowCompletionRatesFunc mocks the GetWorkflowCompletionRates method.
	GetWorkflowCompletionRatesFunc func(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WorkflowCompletionBucket, error)

	// GetWorkflowStepDurationsFunc mocks the GetWorkflowStepDurations method.
	GetWorkflowStepDurationsFunc func(ctx context.Context, projectID string, workflowID string, from time.Time, to time.Time) ([]store.StepDuration, error)

	// GetWorkflowSummaryFunc mocks the GetWorkflowSummary method.
	GetWorkflowSummaryFunc func(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.WorkflowSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetApprovalStats holds details about calls to the GetApprovalStats method.
		GetApprovalStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetCostAnalytics holds details about calls to the GetCostAnalytics method.
		GetCostAnalytics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetCostByTrigger holds details about calls to the GetCostByTrigger method.
		GetCostByTrigger []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetCostForecast holds details about calls to the GetCostForecast method.
		GetCostForecast []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetCostOutliers holds details about calls to the GetCostOutliers method.
		GetCostOutliers []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Threshold is the threshold argument value.
			Threshold float64
		}
		// GetCostTrends holds details about calls to the GetCostTrends method.
		GetCostTrends []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetEventLatency holds details about calls to the GetEventLatency method.
		GetEventLatency []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetEventVolume holds details about calls to the GetEventVolume method.
		GetEventVolume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Bucket is the bucket argument value.
			Bucket string
		}
		// GetJobComparison holds details about calls to the GetJobComparison method.
		GetJobComparison []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// JobIDs is the jobIDs argument value.
			JobIDs []string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetJobCostRanking holds details about calls to the GetJobCostRanking method.
		GetJobCostRanking []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetJobHistory holds details about calls to the GetJobHistory method.
		GetJobHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// JobID is the jobID argument value.
			JobID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Bucket is the bucket argument value.
			Bucket string
		}
		// GetJobReliability holds details about calls to the GetJobReliability method.
		GetJobReliability []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetPerformanceAnalytics holds details about calls to the GetPerformanceAnalytics method.
		GetPerformanceAnalytics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// PeriodHours is the periodHours argument value.
			PeriodHours int
		}
		// GetRunDurationDistribution holds details about calls to the GetRunDurationDistribution method.
		GetRunDurationDistribution []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetRunFailureReasons holds details about calls to the GetRunFailureReasons method.
		GetRunFailureReasons []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetRunSummary holds details about calls to the GetRunSummary method.
		GetRunSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetRunTimeline holds details about calls to the GetRunTimeline method.
		GetRunTimeline []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Bucket is the bucket argument value.
			Bucket string
		}
		// GetRunsByTrigger holds details about calls to the GetRunsByTrigger method.
		GetRunsByTrigger []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetRunsByVersion holds details about calls to the GetRunsByVersion method.
		GetRunsByVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// JobID is the jobID argument value.
			JobID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetTagCost holds details about calls to the GetTagCost method.
		GetTagCost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetTagSummary holds details about calls to the GetTagSummary method.
		GetTagSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetTopCosts holds details about calls to the GetTopCosts method.
		GetTopCosts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetTopFailingJobs holds details about calls to the GetTopFailingJobs method.
		GetTopFailingJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetTopFailingTags holds details about calls to the GetTopFailingTags method.
		GetTopFailingTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetTopFailingWebhooks holds details about calls to the GetTopFailingWebhooks method.
		GetTopFailingWebhooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetWebhookDeliveryStats holds details about calls to the GetWebhookDeliveryStats method.
		GetWebhookDeliveryStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetWebhookEndpointHealth holds details about calls to the GetWebhookEndpointHealth method.
		GetWebhookEndpointHealth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Bucket is the bucket argument value.
			Bucket string
		}
		// GetWorkflowCompletionRates holds details about calls to the GetWorkflowCompletionRates method.
		GetWorkflowCompletionRates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
			// Bucket is the bucket argument value.
			Bucket string
		}
		// GetWorkflowStepDurations holds details about calls to the GetWorkflowStepDurations method.
		GetWorkflowStepDurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// WorkflowID is the workflowID argument value.
			WorkflowID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// GetWorkflowSummary holds details about calls to the GetWorkflowSummary method.
		GetWorkflowSummary []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProjectID is the projectID argument value.
			ProjectID string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
	}
	lockGetApprovalStats           sync.RWMutex
	lockGetCostAnalytics           sync.RWMutex
	lockGetCostByTrigger           sync.RWMutex
	lockGetCostForecast            sync.RWMutex
	lockGetCostOutliers            sync.RWMutex
	lockGetCostTrends              sync.RWMutex
	lockGetEventLatency            sync.RWMutex
	lockGetEventVolume             sync.RWMutex
	lockGetJobComparison           sync.RWMutex
	lockGetJobCostRanking          sync.RWMutex
	lockGetJobHistory              sync.RWMutex
	lockGetJobReliability          sync.RWMutex
	lockGetPerformanceAnalytics    sync.RWMutex
	lockGetRunDurationDistribution sync.RWMutex
	lockGetRunFailureReasons       sync.RWMutex
	lockGetRunSummary              sync.RWMutex
	lockGetRunTimeline             sync.RWMutex
	lockGetRunsByTrigger           sync.RWMutex
	lockGetRunsByVersion           sync.RWMutex
	lockGetTagCost                 sync.RWMutex
	lockGetTagSummary              sync.RWMutex
	lockGetTopCosts                sync.RWMutex
	lockGetTopFailingJobs          sync.RWMutex
	lockGetTopFailingTags          sync.RWMutex
	lockGetTopFailingWebhooks      sync.RWMutex
	lockGetWebhookDeliveryStats    sync.RWMutex
	lockGetWebhookEndpointHealth   sync.RWMutex
	lockGetWorkflowCompletionRates sync.RWMutex
	lockGetWorkflowStepDurations   sync.RWMutex
	lockGetWorkflowSummary         sync.RWMutex
}

// GetApprovalStats calls GetApprovalStatsFunc.
func (mock *AnalyticsStoreMock) GetApprovalStats(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.ApprovalStats, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetApprovalStats.Lock()
	mock.calls.GetApprovalStats = append(mock.calls.GetApprovalStats, callInfo)
	mock.lockGetApprovalStats.Unlock()
	if mock.GetApprovalStatsFunc == nil {
		var (
			approvalStatsOut *store.ApprovalStats
			errOut           error
		)
		return approvalStatsOut, errOut
	}
	return mock.GetApprovalStatsFunc(ctx, projectID, from, to)
}

// GetApprovalStatsCalls gets all the calls that were made to GetApprovalStats.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetApprovalStatsCalls())
func (mock *AnalyticsStoreMock) GetApprovalStatsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetApprovalStats.RLock()
	calls = mock.calls.GetApprovalStats
	mock.lockGetApprovalStats.RUnlock()
	return calls
}

// GetCostAnalytics calls GetCostAnalyticsFunc.
func (mock *AnalyticsStoreMock) GetCostAnalytics(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostAnalytics, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetCostAnalytics.Lock()
	mock.calls.GetCostAnalytics = append(mock.calls.GetCostAnalytics, callInfo)
	mock.lockGetCostAnalytics.Unlock()
	if mock.GetCostAnalyticsFunc == nil {
		var (
			costAnalyticsOut *store.CostAnalytics
			errOut           error
		)
		return costAnalyticsOut, errOut
	}
	return mock.GetCostAnalyticsFunc(ctx, projectID, from, to)
}

// GetCostAnalyticsCalls gets all the calls that were made to GetCostAnalytics.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetCostAnalyticsCalls())
func (mock *AnalyticsStoreMock) GetCostAnalyticsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetCostAnalytics.RLock()
	calls = mock.calls.GetCostAnalytics
	mock.lockGetCostAnalytics.RUnlock()
	return calls
}

// GetCostByTrigger calls GetCostByTriggerFunc.
func (mock *AnalyticsStoreMock) GetCostByTrigger(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostByTrigger, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetCostByTrigger.Lock()
	mock.calls.GetCostByTrigger = append(mock.calls.GetCostByTrigger, callInfo)
	mock.lockGetCostByTrigger.Unlock()
	if mock.GetCostByTriggerFunc == nil {
		var (
			costByTriggersOut []store.CostByTrigger
			errOut            error
		)
		return costByTriggersOut, errOut
	}
	return mock.GetCostByTriggerFunc(ctx, projectID, from, to)
}

// GetCostByTriggerCalls gets all the calls that were made to GetCostByTrigger.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetCostByTriggerCalls())
func (mock *AnalyticsStoreMock) GetCostByTriggerCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetCostByTrigger.RLock()
	calls = mock.calls.GetCostByTrigger
	mock.lockGetCostByTrigger.RUnlock()
	return calls
}

// GetCostForecast calls GetCostForecastFunc.
func (mock *AnalyticsStoreMock) GetCostForecast(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.CostForecast, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetCostForecast.Lock()
	mock.calls.GetCostForecast = append(mock.calls.GetCostForecast, callInfo)
	mock.lockGetCostForecast.Unlock()
	if mock.GetCostForecastFunc == nil {
		var (
			costForecastOut *store.CostForecast
			errOut          error
		)
		return costForecastOut, errOut
	}
	return mock.GetCostForecastFunc(ctx, projectID, from, to)
}

// GetCostForecastCalls gets all the calls that were made to GetCostForecast.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetCostForecastCalls())
func (mock *AnalyticsStoreMock) GetCostForecastCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetCostForecast.RLock()
	calls = mock.calls.GetCostForecast
	mock.lockGetCostForecast.RUnlock()
	return calls
}

// GetCostOutliers calls GetCostOutliersFunc.
func (mock *AnalyticsStoreMock) GetCostOutliers(ctx context.Context, projectID string, from time.Time, to time.Time, threshold float64) ([]store.CostOutlier, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Threshold float64
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Threshold: threshold,
	}
	mock.lockGetCostOutliers.Lock()
	mock.calls.GetCostOutliers = append(mock.calls.GetCostOutliers, callInfo)
	mock.lockGetCostOutliers.Unlock()
	if mock.GetCostOutliersFunc == nil {
		var (
			costOutliersOut []store.CostOutlier
			errOut          error
		)
		return costOutliersOut, errOut
	}
	return mock.GetCostOutliersFunc(ctx, projectID, from, to, threshold)
}

// GetCostOutliersCalls gets all the calls that were made to GetCostOutliers.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetCostOutliersCalls())
func (mock *AnalyticsStoreMock) GetCostOutliersCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Threshold float64
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Threshold float64
	}
	mock.lockGetCostOutliers.RLock()
	calls = mock.calls.GetCostOutliers
	mock.lockGetCostOutliers.RUnlock()
	return calls
}

// GetCostTrends calls GetCostTrendsFunc.
func (mock *AnalyticsStoreMock) GetCostTrends(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.CostTrendPoint, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetCostTrends.Lock()
	mock.calls.GetCostTrends = append(mock.calls.GetCostTrends, callInfo)
	mock.lockGetCostTrends.Unlock()
	if mock.GetCostTrendsFunc == nil {
		var (
			costTrendPointsOut []store.CostTrendPoint
			errOut             error
		)
		return costTrendPointsOut, errOut
	}
	return mock.GetCostTrendsFunc(ctx, projectID, from, to)
}

// GetCostTrendsCalls gets all the calls that were made to GetCostTrends.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetCostTrendsCalls())
func (mock *AnalyticsStoreMock) GetCostTrendsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetCostTrends.RLock()
	calls = mock.calls.GetCostTrends
	mock.lockGetCostTrends.RUnlock()
	return calls
}

// GetEventLatency calls GetEventLatencyFunc.
func (mock *AnalyticsStoreMock) GetEventLatency(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.EventLatencyStats, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetEventLatency.Lock()
	mock.calls.GetEventLatency = append(mock.calls.GetEventLatency, callInfo)
	mock.lockGetEventLatency.Unlock()
	if mock.GetEventLatencyFunc == nil {
		var (
			eventLatencyStatsOut *store.EventLatencyStats
			errOut               error
		)
		return eventLatencyStatsOut, errOut
	}
	return mock.GetEventLatencyFunc(ctx, projectID, from, to)
}

// GetEventLatencyCalls gets all the calls that were made to GetEventLatency.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetEventLatencyCalls())
func (mock *AnalyticsStoreMock) GetEventLatencyCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetEventLatency.RLock()
	calls = mock.calls.GetEventLatency
	mock.lockGetEventLatency.RUnlock()
	return calls
}

// GetEventVolume calls GetEventVolumeFunc.
func (mock *AnalyticsStoreMock) GetEventVolume(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.EventVolumeBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Bucket:    bucket,
	}
	mock.lockGetEventVolume.Lock()
	mock.calls.GetEventVolume = append(mock.calls.GetEventVolume, callInfo)
	mock.lockGetEventVolume.Unlock()
	if mock.GetEventVolumeFunc == nil {
		var (
			eventVolumeBucketsOut []store.EventVolumeBucket
			errOut                error
		)
		return eventVolumeBucketsOut, errOut
	}
	return mock.GetEventVolumeFunc(ctx, projectID, from, to, bucket)
}

// GetEventVolumeCalls gets all the calls that were made to GetEventVolume.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetEventVolumeCalls())
func (mock *AnalyticsStoreMock) GetEventVolumeCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Bucket    string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}
	mock.lockGetEventVolume.RLock()
	calls = mock.calls.GetEventVolume
	mock.lockGetEventVolume.RUnlock()
	return calls
}

// GetJobComparison calls GetJobComparisonFunc.
func (mock *AnalyticsStoreMock) GetJobComparison(ctx context.Context, projectID string, jobIDs []string, from time.Time, to time.Time) ([]store.JobComparison, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		JobIDs    []string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		JobIDs:    jobIDs,
		From:      from,
		To:        to,
	}
	mock.lockGetJobComparison.Lock()
	mock.calls.GetJobComparison = append(mock.calls.GetJobComparison, callInfo)
	mock.lockGetJobComparison.Unlock()
	if mock.GetJobComparisonFunc == nil {
		var (
			jobComparisonsOut []store.JobComparison
			errOut            error
		)
		return jobComparisonsOut, errOut
	}
	return mock.GetJobComparisonFunc(ctx, projectID, jobIDs, from, to)
}

// GetJobComparisonCalls gets all the calls that were made to GetJobComparison.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetJobComparisonCalls())
func (mock *AnalyticsStoreMock) GetJobComparisonCalls() []struct {
	Ctx       context.Context
	ProjectID string
	JobIDs    []string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		JobIDs    []string
		From      time.Time
		To        time.Time
	}
	mock.lockGetJobComparison.RLock()
	calls = mock.calls.GetJobComparison
	mock.lockGetJobComparison.RUnlock()
	return calls
}

// GetJobCostRanking calls GetJobCostRankingFunc.
func (mock *AnalyticsStoreMock) GetJobCostRanking(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobCostRanking, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetJobCostRanking.Lock()
	mock.calls.GetJobCostRanking = append(mock.calls.GetJobCostRanking, callInfo)
	mock.lockGetJobCostRanking.Unlock()
	if mock.GetJobCostRankingFunc == nil {
		var (
			jobCostRankingsOut []store.JobCostRanking
			errOut             error
		)
		return jobCostRankingsOut, errOut
	}
	return mock.GetJobCostRankingFunc(ctx, projectID, from, to, limit)
}

// GetJobCostRankingCalls gets all the calls that were made to GetJobCostRanking.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetJobCostRankingCalls())
func (mock *AnalyticsStoreMock) GetJobCostRankingCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetJobCostRanking.RLock()
	calls = mock.calls.GetJobCostRanking
	mock.lockGetJobCostRanking.RUnlock()
	return calls
}

// GetJobHistory calls GetJobHistoryFunc.
func (mock *AnalyticsStoreMock) GetJobHistory(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time, bucket string) ([]store.JobHistoryBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		JobID     string
		From      time.Time
		To        time.Time
		Bucket    string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		JobID:     jobID,
		From:      from,
		To:        to,
		Bucket:    bucket,
	}
	mock.lockGetJobHistory.Lock()
	mock.calls.GetJobHistory = append(mock.calls.GetJobHistory, callInfo)
	mock.lockGetJobHistory.Unlock()
	if mock.GetJobHistoryFunc == nil {
		var (
			jobHistoryBucketsOut []store.JobHistoryBucket
			errOut               error
		)
		return jobHistoryBucketsOut, errOut
	}
	return mock.GetJobHistoryFunc(ctx, projectID, jobID, from, to, bucket)
}

// GetJobHistoryCalls gets all the calls that were made to GetJobHistory.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetJobHistoryCalls())
func (mock *AnalyticsStoreMock) GetJobHistoryCalls() []struct {
	Ctx       context.Context
	ProjectID string
	JobID     string
	From      time.Time
	To        time.Time
	Bucket    string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		JobID     string
		From      time.Time
		To        time.Time
		Bucket    string
	}
	mock.lockGetJobHistory.RLock()
	calls = mock.calls.GetJobHistory
	mock.lockGetJobHistory.RUnlock()
	return calls
}

// GetJobReliability calls GetJobReliabilityFunc.
func (mock *AnalyticsStoreMock) GetJobReliability(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.JobReliability, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetJobReliability.Lock()
	mock.calls.GetJobReliability = append(mock.calls.GetJobReliability, callInfo)
	mock.lockGetJobReliability.Unlock()
	if mock.GetJobReliabilityFunc == nil {
		var (
			jobReliabilitysOut []store.JobReliability
			errOut             error
		)
		return jobReliabilitysOut, errOut
	}
	return mock.GetJobReliabilityFunc(ctx, projectID, from, to, limit)
}

// GetJobReliabilityCalls gets all the calls that were made to GetJobReliability.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetJobReliabilityCalls())
func (mock *AnalyticsStoreMock) GetJobReliabilityCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetJobReliability.RLock()
	calls = mock.calls.GetJobReliability
	mock.lockGetJobReliability.RUnlock()
	return calls
}

// GetPerformanceAnalytics calls GetPerformanceAnalyticsFunc.
func (mock *AnalyticsStoreMock) GetPerformanceAnalytics(ctx context.Context, projectID string, periodHours int) (*store.PerformanceAnalytics, error) {
	callInfo := struct {
		Ctx         context.Context
		ProjectID   string
		PeriodHours int
	}{
		Ctx:         ctx,
		ProjectID:   projectID,
		PeriodHours: periodHours,
	}
	mock.lockGetPerformanceAnalytics.Lock()
	mock.calls.GetPerformanceAnalytics = append(mock.calls.GetPerformanceAnalytics, callInfo)
	mock.lockGetPerformanceAnalytics.Unlock()
	if mock.GetPerformanceAnalyticsFunc == nil {
		var (
			performanceAnalyticsOut *store.PerformanceAnalytics
			errOut                  error
		)
		return performanceAnalyticsOut, errOut
	}
	return mock.GetPerformanceAnalyticsFunc(ctx, projectID, periodHours)
}

// GetPerformanceAnalyticsCalls gets all the calls that were made to GetPerformanceAnalytics.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetPerformanceAnalyticsCalls())
func (mock *AnalyticsStoreMock) GetPerformanceAnalyticsCalls() []struct {
	Ctx         context.Context
	ProjectID   string
	PeriodHours int
} {
	var calls []struct {
		Ctx         context.Context
		ProjectID   string
		PeriodHours int
	}
	mock.lockGetPerformanceAnalytics.RLock()
	calls = mock.calls.GetPerformanceAnalytics
	mock.lockGetPerformanceAnalytics.RUnlock()
	return calls
}

// GetRunDurationDistribution calls GetRunDurationDistributionFunc.
func (mock *AnalyticsStoreMock) GetRunDurationDistribution(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunDurationBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetRunDurationDistribution.Lock()
	mock.calls.GetRunDurationDistribution = append(mock.calls.GetRunDurationDistribution, callInfo)
	mock.lockGetRunDurationDistribution.Unlock()
	if mock.GetRunDurationDistributionFunc == nil {
		var (
			runDurationBucketsOut []store.RunDurationBucket
			errOut                error
		)
		return runDurationBucketsOut, errOut
	}
	return mock.GetRunDurationDistributionFunc(ctx, projectID, from, to)
}

// GetRunDurationDistributionCalls gets all the calls that were made to GetRunDurationDistribution.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunDurationDistributionCalls())
func (mock *AnalyticsStoreMock) GetRunDurationDistributionCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetRunDurationDistribution.RLock()
	calls = mock.calls.GetRunDurationDistribution
	mock.lockGetRunDurationDistribution.RUnlock()
	return calls
}

// GetRunFailureReasons calls GetRunFailureReasonsFunc.
func (mock *AnalyticsStoreMock) GetRunFailureReasons(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.RunFailureReason, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetRunFailureReasons.Lock()
	mock.calls.GetRunFailureReasons = append(mock.calls.GetRunFailureReasons, callInfo)
	mock.lockGetRunFailureReasons.Unlock()
	if mock.GetRunFailureReasonsFunc == nil {
		var (
			runFailureReasonsOut []store.RunFailureReason
			errOut               error
		)
		return runFailureReasonsOut, errOut
	}
	return mock.GetRunFailureReasonsFunc(ctx, projectID, from, to, limit)
}

// GetRunFailureReasonsCalls gets all the calls that were made to GetRunFailureReasons.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunFailureReasonsCalls())
func (mock *AnalyticsStoreMock) GetRunFailureReasonsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetRunFailureReasons.RLock()
	calls = mock.calls.GetRunFailureReasons
	mock.lockGetRunFailureReasons.RUnlock()
	return calls
}

// GetRunSummary calls GetRunSummaryFunc.
func (mock *AnalyticsStoreMock) GetRunSummary(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.RunSummary, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetRunSummary.Lock()
	mock.calls.GetRunSummary = append(mock.calls.GetRunSummary, callInfo)
	mock.lockGetRunSummary.Unlock()
	if mock.GetRunSummaryFunc == nil {
		var (
			runSummaryOut *store.RunSummary
			errOut        error
		)
		return runSummaryOut, errOut
	}
	return mock.GetRunSummaryFunc(ctx, projectID, from, to)
}

// GetRunSummaryCalls gets all the calls that were made to GetRunSummary.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunSummaryCalls())
func (mock *AnalyticsStoreMock) GetRunSummaryCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetRunSummary.RLock()
	calls = mock.calls.GetRunSummary
	mock.lockGetRunSummary.RUnlock()
	return calls
}

// GetRunTimeline calls GetRunTimelineFunc.
func (mock *AnalyticsStoreMock) GetRunTimeline(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.RunTimelineBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Bucket:    bucket,
	}
	mock.lockGetRunTimeline.Lock()
	mock.calls.GetRunTimeline = append(mock.calls.GetRunTimeline, callInfo)
	mock.lockGetRunTimeline.Unlock()
	if mock.GetRunTimelineFunc == nil {
		var (
			runTimelineBucketsOut []store.RunTimelineBucket
			errOut                error
		)
		return runTimelineBucketsOut, errOut
	}
	return mock.GetRunTimelineFunc(ctx, projectID, from, to, bucket)
}

// GetRunTimelineCalls gets all the calls that were made to GetRunTimeline.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunTimelineCalls())
func (mock *AnalyticsStoreMock) GetRunTimelineCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Bucket    string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}
	mock.lockGetRunTimeline.RLock()
	calls = mock.calls.GetRunTimeline
	mock.lockGetRunTimeline.RUnlock()
	return calls
}

// GetRunsByTrigger calls GetRunsByTriggerFunc.
func (mock *AnalyticsStoreMock) GetRunsByTrigger(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.RunsByTrigger, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetRunsByTrigger.Lock()
	mock.calls.GetRunsByTrigger = append(mock.calls.GetRunsByTrigger, callInfo)
	mock.lockGetRunsByTrigger.Unlock()
	if mock.GetRunsByTriggerFunc == nil {
		var (
			runsByTriggersOut []store.RunsByTrigger
			errOut            error
		)
		return runsByTriggersOut, errOut
	}
	return mock.GetRunsByTriggerFunc(ctx, projectID, from, to)
}

// GetRunsByTriggerCalls gets all the calls that were made to GetRunsByTrigger.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunsByTriggerCalls())
func (mock *AnalyticsStoreMock) GetRunsByTriggerCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetRunsByTrigger.RLock()
	calls = mock.calls.GetRunsByTrigger
	mock.lockGetRunsByTrigger.RUnlock()
	return calls
}

// GetRunsByVersion calls GetRunsByVersionFunc.
func (mock *AnalyticsStoreMock) GetRunsByVersion(ctx context.Context, projectID string, jobID string, from time.Time, to time.Time) ([]store.RunsByVersion, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		JobID     string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		JobID:     jobID,
		From:      from,
		To:        to,
	}
	mock.lockGetRunsByVersion.Lock()
	mock.calls.GetRunsByVersion = append(mock.calls.GetRunsByVersion, callInfo)
	mock.lockGetRunsByVersion.Unlock()
	if mock.GetRunsByVersionFunc == nil {
		var (
			runsByVersionsOut []store.RunsByVersion
			errOut            error
		)
		return runsByVersionsOut, errOut
	}
	return mock.GetRunsByVersionFunc(ctx, projectID, jobID, from, to)
}

// GetRunsByVersionCalls gets all the calls that were made to GetRunsByVersion.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetRunsByVersionCalls())
func (mock *AnalyticsStoreMock) GetRunsByVersionCalls() []struct {
	Ctx       context.Context
	ProjectID string
	JobID     string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		JobID     string
		From      time.Time
		To        time.Time
	}
	mock.lockGetRunsByVersion.RLock()
	calls = mock.calls.GetRunsByVersion
	mock.lockGetRunsByVersion.RUnlock()
	return calls
}

// GetTagCost calls GetTagCostFunc.
func (mock *AnalyticsStoreMock) GetTagCost(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagCost, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTagCost.Lock()
	mock.calls.GetTagCost = append(mock.calls.GetTagCost, callInfo)
	mock.lockGetTagCost.Unlock()
	if mock.GetTagCostFunc == nil {
		var (
			tagCostsOut []store.TagCost
			errOut      error
		)
		return tagCostsOut, errOut
	}
	return mock.GetTagCostFunc(ctx, projectID, from, to, limit)
}

// GetTagCostCalls gets all the calls that were made to GetTagCost.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTagCostCalls())
func (mock *AnalyticsStoreMock) GetTagCostCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTagCost.RLock()
	calls = mock.calls.GetTagCost
	mock.lockGetTagCost.RUnlock()
	return calls
}

// GetTagSummary calls GetTagSummaryFunc.
func (mock *AnalyticsStoreMock) GetTagSummary(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TagSummary, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTagSummary.Lock()
	mock.calls.GetTagSummary = append(mock.calls.GetTagSummary, callInfo)
	mock.lockGetTagSummary.Unlock()
	if mock.GetTagSummaryFunc == nil {
		var (
			tagSummarysOut []store.TagSummary
			errOut         error
		)
		return tagSummarysOut, errOut
	}
	return mock.GetTagSummaryFunc(ctx, projectID, from, to, limit)
}

// GetTagSummaryCalls gets all the calls that were made to GetTagSummary.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTagSummaryCalls())
func (mock *AnalyticsStoreMock) GetTagSummaryCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTagSummary.RLock()
	calls = mock.calls.GetTagSummary
	mock.lockGetTagSummary.RUnlock()
	return calls
}

// GetTopCosts calls GetTopCostsFunc.
func (mock *AnalyticsStoreMock) GetTopCosts(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopCostItem, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTopCosts.Lock()
	mock.calls.GetTopCosts = append(mock.calls.GetTopCosts, callInfo)
	mock.lockGetTopCosts.Unlock()
	if mock.GetTopCostsFunc == nil {
		var (
			topCostItemsOut []store.TopCostItem
			errOut          error
		)
		return topCostItemsOut, errOut
	}
	return mock.GetTopCostsFunc(ctx, projectID, from, to, limit)
}

// GetTopCostsCalls gets all the calls that were made to GetTopCosts.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTopCostsCalls())
func (mock *AnalyticsStoreMock) GetTopCostsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTopCosts.RLock()
	calls = mock.calls.GetTopCosts
	mock.lockGetTopCosts.RUnlock()
	return calls
}

// GetTopFailingJobs calls GetTopFailingJobsFunc.
func (mock *AnalyticsStoreMock) GetTopFailingJobs(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingJob, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTopFailingJobs.Lock()
	mock.calls.GetTopFailingJobs = append(mock.calls.GetTopFailingJobs, callInfo)
	mock.lockGetTopFailingJobs.Unlock()
	if mock.GetTopFailingJobsFunc == nil {
		var (
			topFailingJobsOut []store.TopFailingJob
			errOut            error
		)
		return topFailingJobsOut, errOut
	}
	return mock.GetTopFailingJobsFunc(ctx, projectID, from, to, limit)
}

// GetTopFailingJobsCalls gets all the calls that were made to GetTopFailingJobs.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTopFailingJobsCalls())
func (mock *AnalyticsStoreMock) GetTopFailingJobsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTopFailingJobs.RLock()
	calls = mock.calls.GetTopFailingJobs
	mock.lockGetTopFailingJobs.RUnlock()
	return calls
}

// GetTopFailingTags calls GetTopFailingTagsFunc.
func (mock *AnalyticsStoreMock) GetTopFailingTags(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingTag, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTopFailingTags.Lock()
	mock.calls.GetTopFailingTags = append(mock.calls.GetTopFailingTags, callInfo)
	mock.lockGetTopFailingTags.Unlock()
	if mock.GetTopFailingTagsFunc == nil {
		var (
			topFailingTagsOut []store.TopFailingTag
			errOut            error
		)
		return topFailingTagsOut, errOut
	}
	return mock.GetTopFailingTagsFunc(ctx, projectID, from, to, limit)
}

// GetTopFailingTagsCalls gets all the calls that were made to GetTopFailingTags.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTopFailingTagsCalls())
func (mock *AnalyticsStoreMock) GetTopFailingTagsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTopFailingTags.RLock()
	calls = mock.calls.GetTopFailingTags
	mock.lockGetTopFailingTags.RUnlock()
	return calls
}

// GetTopFailingWebhooks calls GetTopFailingWebhooksFunc.
func (mock *AnalyticsStoreMock) GetTopFailingWebhooks(ctx context.Context, projectID string, from time.Time, to time.Time, limit int) ([]store.TopFailingEndpoint, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Limit:     limit,
	}
	mock.lockGetTopFailingWebhooks.Lock()
	mock.calls.GetTopFailingWebhooks = append(mock.calls.GetTopFailingWebhooks, callInfo)
	mock.lockGetTopFailingWebhooks.Unlock()
	if mock.GetTopFailingWebhooksFunc == nil {
		var (
			topFailingEndpointsOut []store.TopFailingEndpoint
			errOut                 error
		)
		return topFailingEndpointsOut, errOut
	}
	return mock.GetTopFailingWebhooksFunc(ctx, projectID, from, to, limit)
}

// GetTopFailingWebhooksCalls gets all the calls that were made to GetTopFailingWebhooks.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetTopFailingWebhooksCalls())
func (mock *AnalyticsStoreMock) GetTopFailingWebhooksCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Limit     int
	}
	mock.lockGetTopFailingWebhooks.RLock()
	calls = mock.calls.GetTopFailingWebhooks
	mock.lockGetTopFailingWebhooks.RUnlock()
	return calls
}

// GetWebhookDeliveryStats calls GetWebhookDeliveryStatsFunc.
func (mock *AnalyticsStoreMock) GetWebhookDeliveryStats(ctx context.Context, projectID string, from time.Time, to time.Time) ([]store.WebhookEndpointStats, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetWebhookDeliveryStats.Lock()
	mock.calls.GetWebhookDeliveryStats = append(mock.calls.GetWebhookDeliveryStats, callInfo)
	mock.lockGetWebhookDeliveryStats.Unlock()
	if mock.GetWebhookDeliveryStatsFunc == nil {
		var (
			webhookEndpointStatssOut []store.WebhookEndpointStats
			errOut                   error
		)
		return webhookEndpointStatssOut, errOut
	}
	return mock.GetWebhookDeliveryStatsFunc(ctx, projectID, from, to)
}

// GetWebhookDeliveryStatsCalls gets all the calls that were made to GetWebhookDeliveryStats.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetWebhookDeliveryStatsCalls())
func (mock *AnalyticsStoreMock) GetWebhookDeliveryStatsCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetWebhookDeliveryStats.RLock()
	calls = mock.calls.GetWebhookDeliveryStats
	mock.lockGetWebhookDeliveryStats.RUnlock()
	return calls
}

// GetWebhookEndpointHealth calls GetWebhookEndpointHealthFunc.
func (mock *AnalyticsStoreMock) GetWebhookEndpointHealth(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WebhookHealthBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Bucket:    bucket,
	}
	mock.lockGetWebhookEndpointHealth.Lock()
	mock.calls.GetWebhookEndpointHealth = append(mock.calls.GetWebhookEndpointHealth, callInfo)
	mock.lockGetWebhookEndpointHealth.Unlock()
	if mock.GetWebhookEndpointHealthFunc == nil {
		var (
			webhookHealthBucketsOut []store.WebhookHealthBucket
			errOut                  error
		)
		return webhookHealthBucketsOut, errOut
	}
	return mock.GetWebhookEndpointHealthFunc(ctx, projectID, from, to, bucket)
}

// GetWebhookEndpointHealthCalls gets all the calls that were made to GetWebhookEndpointHealth.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetWebhookEndpointHealthCalls())
func (mock *AnalyticsStoreMock) GetWebhookEndpointHealthCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Bucket    string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}
	mock.lockGetWebhookEndpointHealth.RLock()
	calls = mock.calls.GetWebhookEndpointHealth
	mock.lockGetWebhookEndpointHealth.RUnlock()
	return calls
}

// GetWorkflowCompletionRates calls GetWorkflowCompletionRatesFunc.
func (mock *AnalyticsStoreMock) GetWorkflowCompletionRates(ctx context.Context, projectID string, from time.Time, to time.Time, bucket string) ([]store.WorkflowCompletionBucket, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
		Bucket:    bucket,
	}
	mock.lockGetWorkflowCompletionRates.Lock()
	mock.calls.GetWorkflowCompletionRates = append(mock.calls.GetWorkflowCompletionRates, callInfo)
	mock.lockGetWorkflowCompletionRates.Unlock()
	if mock.GetWorkflowCompletionRatesFunc == nil {
		var (
			workflowCompletionBucketsOut []store.WorkflowCompletionBucket
			errOut                       error
		)
		return workflowCompletionBucketsOut, errOut
	}
	return mock.GetWorkflowCompletionRatesFunc(ctx, projectID, from, to, bucket)
}

// GetWorkflowCompletionRatesCalls gets all the calls that were made to GetWorkflowCompletionRates.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetWorkflowCompletionRatesCalls())
func (mock *AnalyticsStoreMock) GetWorkflowCompletionRatesCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
	Bucket    string
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
		Bucket    string
	}
	mock.lockGetWorkflowCompletionRates.RLock()
	calls = mock.calls.GetWorkflowCompletionRates
	mock.lockGetWorkflowCompletionRates.RUnlock()
	return calls
}

// GetWorkflowStepDurations calls GetWorkflowStepDurationsFunc.
func (mock *AnalyticsStoreMock) GetWorkflowStepDurations(ctx context.Context, projectID string, workflowID string, from time.Time, to time.Time) ([]store.StepDuration, error) {
	callInfo := struct {
		Ctx        context.Context
		ProjectID  string
		WorkflowID string
		From       time.Time
		To         time.Time
	}{
		Ctx:        ctx,
		ProjectID:  projectID,
		WorkflowID: workflowID,
		From:       from,
		To:         to,
	}
	mock.lockGetWorkflowStepDurations.Lock()
	mock.calls.GetWorkflowStepDurations = append(mock.calls.GetWorkflowStepDurations, callInfo)
	mock.lockGetWorkflowStepDurations.Unlock()
	if mock.GetWorkflowStepDurationsFunc == nil {
		var (
			stepDurationsOut []store.StepDuration
			errOut           error
		)
		return stepDurationsOut, errOut
	}
	return mock.GetWorkflowStepDurationsFunc(ctx, projectID, workflowID, from, to)
}

// GetWorkflowStepDurationsCalls gets all the calls that were made to GetWorkflowStepDurations.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetWorkflowStepDurationsCalls())
func (mock *AnalyticsStoreMock) GetWorkflowStepDurationsCalls() []struct {
	Ctx        context.Context
	ProjectID  string
	WorkflowID string
	From       time.Time
	To         time.Time
} {
	var calls []struct {
		Ctx        context.Context
		ProjectID  string
		WorkflowID string
		From       time.Time
		To         time.Time
	}
	mock.lockGetWorkflowStepDurations.RLock()
	calls = mock.calls.GetWorkflowStepDurations
	mock.lockGetWorkflowStepDurations.RUnlock()
	return calls
}

// GetWorkflowSummary calls GetWorkflowSummaryFunc.
func (mock *AnalyticsStoreMock) GetWorkflowSummary(ctx context.Context, projectID string, from time.Time, to time.Time) (*store.WorkflowSummary, error) {
	callInfo := struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}{
		Ctx:       ctx,
		ProjectID: projectID,
		From:      from,
		To:        to,
	}
	mock.lockGetWorkflowSummary.Lock()
	mock.calls.GetWorkflowSummary = append(mock.calls.GetWorkflowSummary, callInfo)
	mock.lockGetWorkflowSummary.Unlock()
	if mock.GetWorkflowSummaryFunc == nil {
		var (
			workflowSummaryOut *store.WorkflowSummary
			errOut             error
		)
		return workflowSummaryOut, errOut
	}
	return mock.GetWorkflowSummaryFunc(ctx, projectID, from, to)
}

// GetWorkflowSummaryCalls gets all the calls that were made to GetWorkflowSummary.
// Check the length with:
//
//	len(mockedAnalyticsStore.GetWorkflowSummaryCalls())
func (mock *AnalyticsStoreMock) GetWorkflowSummaryCalls() []struct {
	Ctx       context.Context
	ProjectID string
	From      time.Time
	To        time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ProjectID string
		From      time.Time
		To        time.Time
	}
	mock.lockGetWorkflowSummary.RLock()
	calls = mock.calls.GetWorkflowSummary
	mock.lockGetWorkflowSummary.RUnlock()
	return calls
}
